import type { PackageDeliverable, ProvisionablePackage } from "./package-catalog.ts";

export interface SolutionBriefForGuidance {
  problem: string;
  intendedBeneficiary: string;
  desiredOutcome: string;
  successMetric: string;
  currentProcess: string;
  constraints: string;
  brandVoice: string;
}

export interface DeliverableImplementationGuide {
  summary: string;
  customerPurpose: string;
  implementationSteps: string[];
  operatingWorkflow: string[];
  ownerActions: string[];
  handoffInstructions: string[];
  acceptanceChecklist: string[];
  failureStates: string[];
  nextMilestones: string[];
}

export interface PackageCustomerGuide {
  title: string;
  executiveOverview: string;
  startHere: string[];
  whatWasProvisioned: string[];
  operatingWorkflow: string[];
  implementationRoadmap: Array<{
    phase: string;
    timing: string;
    actions: string[];
  }>;
  rolesAndResponsibilities: Array<{
    role: string;
    responsibility: string;
  }>;
  measurementPlan: string[];
  supportAndEscalation: string[];
  ambiguityKillers: string[];
}

export interface PackageGuidanceOptions {
  engineRoleName?: string;
  managedHandoffLabel?: string;
}

const defaultBrief: SolutionBriefForGuidance = {
  problem: "The buyer wants a complete business outcome without assembling or operating separate systems.",
  intendedBeneficiary: "The selected audience from the intake form.",
  desiredOutcome: "The promised customer outcome.",
  successMetric: "The success metric submitted in the intake form.",
  currentProcess: "The current process supplied during intake.",
  constraints: "The rules, limits, compliance notes, and approval requirements supplied during intake.",
  brandVoice: "The customer experience style supplied during intake.",
};

function surfacePurpose(surface: PackageDeliverable["launchSurface"]): string {
  switch (surface) {
    case "capture":
      return "This is the frontstage intake surface. It turns demand into structured submissions with enough context to route the next step.";
    case "operator":
      return "This is the operator surface. It tells the delivery owner what to inspect, approve, prioritize, or hand off next.";
    case "automation":
      return "This is the workflow layer. It defines the repeatable sequence, routing rule, scoring rule, or message logic behind the outcome.";
    case "billing":
      return "This is the monetization surface. It explains how quotes, payments, commissions, buyer claims, or revenue events should be handled.";
    case "reporting":
      return "This is the proof surface. It shows whether the promised outcome is moving in the right direction.";
    default:
      return "This is the delivery hub surface. It explains what was created, where it lives, and how the client should use it.";
  }
}

function surfaceWorkflow(surface: PackageDeliverable["launchSurface"], title: string): string[] {
  switch (surface) {
    case "capture":
      return [
        "Traffic or a human operator sends the right person to the capture surface.",
        "The form collects identity, context, urgency, desired outcome, and consent-sensitive details.",
        "The submitted record is routed to the operator path, report path, or follow-up path for this solution.",
        `The ${title.toLowerCase()} is reviewed against the stated success metric before the next action is taken.`,
      ];
    case "operator":
      return [
        "Open the operations surface at the beginning of each delivery cycle.",
        "Review ready, blocked, and needs-human-review items before any outbound action.",
        "Use the listed next action instead of improvising from email or chat threads.",
        "Record the outcome so reporting and future optimization stay accurate.",
      ];
    case "automation":
      return [
        "Treat the workflow as the system of record for the repeatable handoff.",
        "Confirm the trigger, routing condition, message, or scoring rule matches the intake constraints.",
        "Run one sample scenario before using the workflow with real customer demand.",
        "Escalate any edge case that violates the stated rules, limits, claims, or approval requirements.",
      ];
    case "billing":
      return [
        "Use the billing surface to confirm price, buyer, event type, and payment or payout state.",
        "Send the buyer to the payment, invoice, claim, or commission path shown in the surface.",
        "Reconcile the event against the revenue report after payment, refund, claim, or payout status changes.",
        "Do not treat money movement as live unless approved payment account access is connected.",
      ];
    case "reporting":
      return [
        "Open the reporting surface on the agreed cadence.",
        "Compare raw demand, qualified intent, completed action, and value created.",
        "Use the report to decide what to improve, pause, expand, or escalate.",
        "Attach the report to renewal, optimization, and client update conversations.",
      ];
    default:
      return [
        "Open the delivery hub first.",
        "Confirm the client name, target market, desired outcome, and success metric.",
        "Walk through the provisioned outputs in order.",
        "Use the acceptance checklist before treating the solution as customer-ready.",
      ];
  }
}

export function buildDeliverableGuide(
  pkg: ProvisionablePackage,
  deliverable: PackageDeliverable,
  brief: Partial<SolutionBriefForGuidance> = {},
): DeliverableImplementationGuide {
  const context = { ...defaultBrief, ...brief };
  const purpose = surfacePurpose(deliverable.launchSurface);

  return {
    summary: `${deliverable.title} is provisioned as part of ${pkg.title}. It exists to move ${context.intendedBeneficiary} toward ${context.desiredOutcome} and to make progress measurable by ${context.successMetric}.`,
    customerPurpose: `${purpose} The client should use it as a finished part of the solution, not as a blank setup task.`,
    implementationSteps: [
      `Open the linked ${deliverable.launchSurface} surface and confirm the title, promise, and context match the buyer's submitted intake.`,
      `Read the created artifact: ${deliverable.createdArtifact}`,
      `Apply the brand voice rule: ${context.brandVoice}`,
      `Apply the constraint rule before any customer-facing use: ${context.constraints}`,
      "Run the acceptance checklist below. If anything fails, use the failure-state instructions instead of guessing.",
    ],
    operatingWorkflow: surfaceWorkflow(deliverable.launchSurface, deliverable.title),
    ownerActions: [
      "Assign one delivery owner for this output.",
      "Confirm whether the output is customer-facing, operator-facing, reporting-facing, or monetization-facing.",
      "Use the next milestone list to decide what the client should do today, this week, and this month.",
      "Record any client-specific exception in the delivery hub so the next operator sees the same truth.",
    ],
    handoffInstructions: [
      "Send the client the delivery hub URL first, then the specific output URL.",
      "Explain the output in one sentence using the summary above.",
      "Point the client to the first implementation step and the acceptance checklist.",
      "If an optional external account is not connected, use the managed handoff described in the provisioning result.",
    ],
    acceptanceChecklist: [
      "The output has a launched URL.",
      "The output title and created artifact match the selected package.",
      "The output names the intended beneficiary, success metric, and next action.",
      "The client can tell whether this output is for capture, operations, workflow, billing, reporting, or the delivery hub.",
      "The output has clear failure handling and does not require hidden follow-up configuration to be useful.",
    ],
    failureStates: [
      "If the client does not recognize the business context, return to the intake values and correct the brand, market, or offer before using the output.",
      "If the next action depends on a client-owned account, use the managed handoff until approved access is added.",
      "If the output would make a regulated, financial, medical, legal, or unsupported claim, pause and route to human approval.",
      "If the output does not support the stated success metric, mark it for optimization before presenting it as proof of value.",
    ],
    nextMilestones: [
      "Today: review the output and complete the acceptance checklist.",
      "This week: use the output with a real or sample customer scenario and record the result.",
      "This month: compare results against the success metric and decide whether to optimize, expand, or bundle another package.",
    ],
  };
}

export function buildPackageCustomerGuide(
  pkg: ProvisionablePackage,
  brief: Partial<SolutionBriefForGuidance> = {},
  createdOutputs: Array<{ title: string; createdArtifact: string; surface: string }> = pkg.deliverables.map((deliverable) => ({
    title: deliverable.title,
    createdArtifact: deliverable.createdArtifact,
    surface: deliverable.launchSurface,
  })),
  options: PackageGuidanceOptions = {},
): PackageCustomerGuide {
  const context = { ...defaultBrief, ...brief };
  const engineRoleName = options.engineRoleName ?? "Lead OS system";
  const managedHandoffLabel = options.managedHandoffLabel ?? "managed handoff";

  return {
    title: `${pkg.title} customer implementation guide`,
    executiveOverview: `${pkg.title} has been provisioned as a complete service-replacement solution for ${context.intendedBeneficiary}. The client should judge it by ${context.successMetric}, work delivered, accepted outputs, and operational lift, not by the number of screens, seats, or assets created.`,
    startHere: [
      "Open the delivery hub URL first.",
      "Confirm the business name, target market, primary outcome, and success metric.",
      "Review the customer-ready outputs in the order they appear in the hub.",
      "Use each output guide before sending links to customers, staff, buyers, partners, or operators.",
      `Use ${managedHandoffLabel}s for any optional account access that was not supplied during intake.`,
    ],
    whatWasProvisioned: createdOutputs.map((output) => `${output.title} (${output.surface}): ${output.createdArtifact}`),
    operatingWorkflow: [
      "Capture demand or source material through the provisioned capture or workspace surface.",
      "Route submissions, assets, or decisions through the operator surface.",
      "Use workflow outputs to standardize follow-up, scoring, production, reactivation, or handoff.",
      "Use reporting outputs to prove whether the promised outcome is happening.",
      "Record decisions, exceptions, approvals, and outcome evidence in the delivery hub so the workflow gets more legible and reliable after each cycle.",
      "Use billing or monetization outputs only with approved account access or managed payment handoff instructions.",
    ],
    implementationRoadmap: [
      {
        phase: "Immediate handoff",
        timing: "0-1 hour after intake",
        actions: [
          "Open every launched URL.",
          "Read the package guide and the output guides.",
          "Confirm the acceptance checks show passed.",
          "Send the delivery hub to the client with the start-here instructions.",
        ],
      },
      {
        phase: "First usage cycle",
        timing: "First 1-7 days",
        actions: [
          "Run one real or sample customer scenario through the capture or workspace surface.",
          "Check the operator surface for next actions and blocked items.",
          "Record the first outcome against the success metric.",
          "Update constraints if the client identifies a compliance, brand, or escalation edge case.",
        ],
      },
      {
        phase: "Optimization cycle",
        timing: "Weeks 2-4",
        actions: [
          "Review reporting and acceptance evidence.",
          "Tune copy, routing, sequence, scoring, or handoff rules using observed friction.",
          "Identify whether the client should add another package or expand the current package to another niche.",
          "Prepare the renewal report around outcomes, not activity.",
        ],
      },
    ],
    rolesAndResponsibilities: [
      { role: "Client decision maker", responsibility: "Confirms the business outcome, approval rules, and success metric." },
      { role: "Delivery operator", responsibility: "Uses the delivery hub, reviews output guides, and handles exceptions." },
      { role: "Customer-facing team", responsibility: "Uses capture, booking, nurture, or support outputs exactly as described in the guide." },
      { role: engineRoleName, responsibility: `Provisions the selected outputs, ${managedHandoffLabel}s, guidance, acceptance checks, and reporting surfaces from the submitted intake.` },
    ],
    measurementPlan: [
      `Primary metric: ${context.successMetric}.`,
      "Tie pricing, renewal, and expansion to work completed, tasks handled, revenue recovered, qualified outcomes, or hours saved instead of active user seats.",
      "Avoid pricing by customer headcount; if the system automates the workflow well, the client should need fewer operators, not more paid seats.",
      "Make the strategic trade-off explicit: per-seat SaaS monetizes headcount and gets punished when automation works, while work-based pricing monetizes completed services and grows with reliable throughput.",
      "Document the per-seat cannibalization trap: if AI reduces the customer's employee count, a seat-priced vendor loses revenue exactly when the product becomes better.",
      "Use the services-budget upside as the pricing benchmark: software tools may capture about 1% of spend, while AI-native service replacement can justify 4% to 10% when it performs the work.",
      "Track the reliability trade-off for work-based pricing: pilots, acceptance receipts, and last-10-percent engineering are required before buyers trust the outcome enough to pay on work delivered.",
      "Do not price superhuman agent capacity like one human seat; patience, 200-language fluency, 24/7 availability, and parallel handling should be monetized by outcomes, tasks, and volume.",
      "Use the service budget as the benchmark and document when the package is replacing outsourced work, internal labor, agency execution, or manual admin.",
      "Treat insurance brokerage, accounting, tax audit, compliance, and healthcare administration as reference markets where services budgets can be meaningfully larger than software budgets.",
      "Map financial and administrative service wedges such as accounting, tax audit, payroll, insurance brokerage, compliance, and banking operations.",
      "Map banking operations that require mission-critical reliability: KYC, loan origination, debt recovery, and fraud monitoring.",
      "Map healthcare administration and legal services separately because specialized knowledge and the last 10% of accuracy decide whether AI can replace the manual service.",
      "Look for fragmented non-tech verticals such as logistics, trucking, fuel cards, HVAC, home services, real estate, and debt financing where software spend has historically been too small.",
      "Use support and language wedges where patient, always-available, multilingual agents can replace high-friction human support or conversation-practice work.",
      "Prioritize the easiest replacement wedges: financial/admin services, banking infrastructure, healthcare administration, legal application-layer services, HVAC and construction field services, trucking/logistics, and multilingual support.",
      "Treat outsourced outcome budgets as the strongest signal: agencies, BPOs, brokers, contractors, admin teams, and specialists prove the customer already pays for completed work.",
      "Turn boring schlep into strategy by mapping payroll, tax, trucking compliance, insurance workflows, KYC, debt recovery, and regulated admin as painstaking drudgery competitors avoid.",
      "Use fragmented non-technical markets like HVAC, construction, home services, trucking, and local field operations where weak software adoption makes agent minting easier.",
      "Use multilingual support as a wedge when patient agents fluent across hundreds of languages can serve global customers, international contractors, or DoorDasher-style workforces better than hard-to-staff human teams.",
      "Prefer workflows that are already outsourced or staffed as human services, because the budget already exists outside software.",
      "Track whether high-attrition support or admin labor, especially 50% to 80% attrition roles, makes the AI-native service more welcome to the buyer.",
      "Frame business process automation as service performance, not productivity support: the package should monitor work, take next actions, produce proof, and escalate only exceptions humans should judge.",
      "Make automation self-regulating: compare outputs with stated goals and adjust prompts, routing, tests, approvals, handoffs, or package priorities when performance drifts.",
      "Tie automation value to tasks completed, work delivered, accepted outputs, and service capacity created rather than seats, logins, dashboards, or generic productivity claims.",
      "Run the delivery package as an intelligence operating system: every workflow produces artifacts, decisions, QA evidence, and exception notes the agent layer can query later.",
      "Replace open-loop operations with closed loops: measure outputs against the stated goal, then adjust prompts, routing, tests, handoffs, and package priorities until the workflow self-corrects.",
      "Make every process, decision, workflow, exception, and outcome queryable so the intelligence layer can improve stability and correctness from internal operating data.",
      "Give AI a continuous operating-system view of the company rather than a one-off tool snapshot; the delivery hub should point to the artifacts that keep the view current.",
      "Capture communication logs from email, Pylon-style support tools, shared channels, and support queues as first-class operating memory.",
      "Capture technical activity from GitHub commits, pull requests, issues, review notes, deployments, and shipped-work evidence.",
      "Capture planning data from Notion, Google Docs, specs, decision memos, delivery hubs, and package workspaces.",
      "Capture recorded interactions such as sales calls, customer calls, daily standups, transcripts, and follow-up commitments.",
      "Make the workflow legible by default so agents can analyze what actually shipped and whether it addressed customer needs before proposing the next plan.",
      "Keep work legible to AI by moving decisions, approvals, exceptions, outcomes, and follow-up commitments into transparent channels, package surfaces, shared records, and delivery receipts instead of private DMs or inbox fragments.",
      "Run an artifact-rich environment with AI notetakers, Slack transcripts, GitHub logs, ticket updates, customer outcomes, and dashboards for revenue, sales, engineering, hiring, and operations.",
      "Minimize private DMs and email-only decisions; move important work into transparent channels and package surfaces where embedded agents can observe, route, summarize, and learn.",
      "Generate artifacts for important actions: meeting notes, decision logs, ticket updates, approval receipts, exception notes, QA traces, customer outcomes, and follow-up commitments.",
      "Give models contextual parity with a human employee by connecting revenue, sales, engineering, hiring, operations, customer feedback, tickets, Slack, GitHub, recordings, and package-performance dashboards.",
      "Use autonomous sprint planning loops where agents compare shipped work with customer needs and propose predictable next-cycle plans instead of relying on lossy manual status rollups.",
      "Base autonomous coordination on queryable evidence: tickets, Pylon/email feedback, Notion or Google Docs plans, GitHub commits and issues, sales calls, standup recordings, and delivery evidence.",
      "Use Linear-style tickets, Slack, GitHub, standup recordings, shipped-work evidence, and customer needs to generate predictable plans, compress sprint cycles, and target nearly 10x more useful work.",
      "Let the intelligence layer coordinate information instead of classic middle-management status chains, moving signals directly to owners, agents, package surfaces, and decision records.",
      "Remove human middleware where the intelligence layer can route information directly; fewer status meetings, translation layers, and middle-management handoffs should move signals to decisions faster.",
      "Replace the classic management hierarchy with an intelligence layer that routes package status, decisions, evidence, and exceptions directly to the right owner.",
      "Define ICs as builder operators across engineering, support, sales, and operations; meetings should prefer working prototypes, live workflows, agent runs, dashboards, scripts, or customer-ready drafts over static decks.",
      "Define the DRI as one person owning one measurable outcome, with strategy, customer proof, decisions, and improvement loops assigned to a named accountable owner.",
      "Measure the DRI on strategy and customer outcomes, not status routing, headcount management, or middle-management coordination.",
      "Attach one named DRI to one specific result with visible proof, decision rights, and acceptance evidence in the package surfaces.",
      "Check that missed outcomes have a single DRI-owned adjustment path instead of responsibility diffused through committees or manager layers.",
      "Use the intelligence layer to route artifacts, updates, exceptions, and evidence so the DRI guides goals, constraints, evals, escalation rules, and outcomes.",
      "Keep the DRI at the edge of customer and operator reality, close enough to judge exceptions while agents coordinate repeatable work.",
      "Use DRI leverage as a token-maxing measure: one accountable operator with agents should replace large engineering, admin, or coordination teams where the workflow is repeatable.",
      "Track whether information velocity improves because signals move from artifacts to agents, decisions, and customer-visible changes without manual interpretation chains.",
      "Expect the AI Founder archetype to build, coach, test, and use frontier AI tools personally; do not outsource AI strategy to a distant committee or tooling owner.",
      "Use the IC, DRI, and AI Founder archetypes to maximize useful token usage before headcount while keeping humans focused on building, outcomes, judgment, and coaching.",
      "Track direct velocity gain from removing human middleware: artifacts should flow to agents, accountable owners, and decisions without middle-manager status relays.",
      "Design for single-person agent leverage: one capable operator with AI agents should do work that previously required a larger cross-functional team.",
      "Keep engineering, HR, admin, support, and operations departments lean by maximizing agent throughput and token spend before coordination headcount.",
      "Treat speed as the first moat before data, network, or brand defensibility exists; the package should outlearn labs and incumbents by shipping AI-native service improvements faster.",
      "Measure whether queryable organization data is compressing sprint cycles and helping the same expert team target nearly 10x more useful work.",
      "Use one-day sprint cadence where safe: a DRI defines the spec, test, or eval, agents implement, and acceptance evidence decides release readiness.",
      "Document incumbent craft overhead the package exploits: PM layers, operations reviews, PRDs, spec docs, approvals, and launch gates that slow customer-visible change.",
      "Keep the package AI-native from day one with prototypes over decks, specs and evals over committee syncs, tokens over coordination headcount, and agents inside repeatable workflows.",
      "Use a forward-deployed speed loop: sit with customers, spot boring manual pain, automate it inside the live workflow, and feed usage and eval data back into the next iteration.",
      "Measure the package against an AI-native powers portfolio: speed first, then process power, counterpositioning, switching costs, eval network economy, cornered resources, scale economies, branding, schlep blindness, and system-of-record lock-in.",
      "Treat speed as the foundation power: one-day sprint cycles, AI software factories, and forward-deployed customer learning should beat PRD-heavy craft cultures while other moats mature.",
      "Measure process power in the final 5% to 10% of reliability: track whether edge cases, QA gates, scenario validations, and domain rules are moving mission-critical work toward 99% accuracy.",
      "Measure counterpositioning by checking that work-delivered or task-completed pricing benefits when automation reduces customer headcount instead of punishing the operator like per-seat SaaS.",
      "Measure switching costs by counting customer-specific onboarding rules, integrations, approvals, exception paths, acceptance history, and workflows minted into daily operations.",
      "Measure the eval network economy by tracking pass/fail outcomes, overrides, exceptions, and customer acceptance receipts that improve prompts, context engineering, tests, and routing for future runs.",
      "Measure cornered resources by preserving proprietary workflow data, tailored time-in-motion observations, specialized evals, domain edge cases, and optimized model routes that outsiders cannot see from the demo.",
      "Measure scale economies where static crawls, model optimizations, evaluation harnesses, integrations, compliance checks, and deployment pipelines get cheaper or more reliable per outcome as usage grows.",
      "Measure branding as trust under risk: the package should become the remembered reliable service outcome for the category, not just another model-powered UI.",
      "Measure schlep blindness and system-of-record lock-in by documenting boring workflow details, bank or regulatory infrastructure work, customer history, decisions, approvals, outcomes, exceptions, eval traces, and reporting receipts.",
      "Discover painstaking drudgery by watching tailored time-in-motion workflows with customers instead of guessing from a pitch deck or landing page.",
      "Map the nitty-gritty request path: how work arrives by email, forms, calls, tickets, or spreadsheets; how it gets enriched; and where manual data entry, call centers, or judgment bridge gaps.",
      "Document hidden backend logic: informal checks, reconciliation habits, exception paths, operator know-how, and workflow rules that only appear when the work is observed directly.",
      "Use 50% to 80% attrition in support or admin roles as a signal that the human work is repetitive, torturous, and ready for AI-native service replacement.",
      "Search boring workflow spaces such as payroll, tax accounting, trucking compliance, insurance operations, and regulated admin where the day-to-day work is grinding execution.",
      "Validate boring spaces because unglamorous tax, payroll, trucking compliance, insurance, regulated admin, and healthcare back-office workflows can have higher hit rates than fun picked-over ideas.",
      "Do the schlep before packaging: physically or operationally observe the work, interview frontline operators, and watch the workflow in context instead of relying on high-level assumptions.",
      "Look for invisible pains programmers rarely see: phone orders, 1-800-number workflows, spreadsheets, faxes, inbox queues, and specialist tribal knowledge that customers have tolerated for years.",
      "Find lossy human middleware by identifying status rollups, fragmented handoffs, manager interpretation, duplicated updates, and manual coordination that a closed loop could make queryable.",
      "Use truck-stop-style field research: go where the work physically or operationally happens, talk to frontline operators, and find fuel-card-like wedges hidden in daily operations.",
      "Use forward-deployed validation to map tailored time-in-motion: request intake, enrichment, call-center bridges, manual entry, approvals, and judgment points before automation is declared real.",
      "Prioritize mission-critical infrastructure workflows such as KYC, loan origination, legal review, accounting close, compliance checks, and customer operations where failures are expensive.",
      "Separate an 80% hackathon demo from production reliability; the final 5% to 20% of consistency and edge-case handling is the drudgery that makes the service trusted.",
      "Treat last-10-percent discovery as validation: edge cases, specialized knowledge, exception paths, and 99% reliability requirements show whether the boring service can actually be replaced.",
      "Filter workflow candidates for existential pain: lost revenue, firing risk, compliance exposure, missed promotion, or business failure if the work remains manual.",
      "Run the Fire or Promotion test as a separate acuteness gate: the buyer should fear being fired, missing promotion, avoiding the work, or losing business momentum if the workflow stays broken.",
      "Measure the fire-side signal explicitly: missed numbers, credibility loss, firing risk, no desire to face the work, or business damage.",
      "Measure the promotion-side signal explicitly: advancement, next-year growth, taking over more of the business, or being recognized as the person who fixed a top-three problem.",
      "Confirm the problem is top three now; a useful workflow that can wait is still nice-to-have.",
      "Use willingness to pay as proof of acuteness: the buyer should budget, complain but pay, or change behavior because the unsolved pain is more expensive.",
      "Run the Binary Test by charging real money and watching whether the buyer opens their wallet; compliments, waitlists, and polite interest do not validate value the way payment does.",
      "Treat refusal to pay as a learning event: the package may not solve a top-three problem, the buyer segment may be wrong, or the delivered value may not overcome the price tag yet.",
      "Use payment behavior to identify the right customer segment: the best segment pays fastest, connects the outcome to budget, and tolerates reasonable implementation friction.",
      "Use premium-price tests when the package claims superior setup, documentation, APIs, delivery, or outcome proof; the Stripe-style lesson is that better execution can justify charging more, not less.",
      "Treat complain-but-pay as the cleanest validation signal: the buyer feels the price and still pays because the unsolved problem is more expensive.",
      "Watch for opportunities lying in plain sight where high-stakes daily work is obvious to operators but still unsolved because reliability, service replacement, or workflow change is hard.",
      "Mint specialized evals and datasets into customer operations so iteration speed compounds into process power rather than one-off feature churn.",
      "Track whether the package has found narrow vertical treasure before labs notice it, then harden edge cases while bigger competitors prioritize broad platform goals.",
      "Track whether closed-loop coordination is cutting sprint time and producing substantially more useful work from the same expert team.",
      "Reject wrapper thinking: the demo surface is easy to imitate, but accumulated workflow logic, evals, approvals, exceptions, and operating evidence should be difficult to copy.",
      "Track the 99% accuracy hurdle separately from the 80% demo; mission-critical work such as loan origination, KYC, legal review, accounting, and compliance needs far more edge-case coverage.",
      "Document backend logic that compounds into process power: policy rules, state transitions, retries, audit trails, permissions, reconciliations, handoffs, and exception paths.",
      "Record integration surface area: client systems, data formats, approval paths, import/export quirks, financial-institution-style integration differences, and reporting contracts.",
      "Build process-automation moat through the painstaking last 10% needed for 99% accuracy in banking, legal, accounting, compliance, healthcare, and other high-stakes service environments.",
      "Use pilots to learn the customer's internal operations, then preserve custom rules, integrations, reporting, approvals, and acceptance history as infrastructure the customer depends on.",
      "Use token spend before headcount when the spend replaces repetitive service labor; reserve humans for specs, tests, approvals, judgment, and complex exceptions.",
      "Treat uncomfortably high API bills as rational when token spend replaces HR, admin, engineering, and coordination headcount.",
      "Treat token maxing as the queryable-organization scaling rule when API spend replaces HR, admin, engineering, support coordination, and management routing.",
      "Design around token usage before headcount: agents run repeatable operations while humans move to the edges as builders, operators, QA owners, approvers, and agent wranglers.",
      "Treat the last 10% as the product: the demo is not done until scenario validations, evals, acceptance checks, and edge-case handling push the work toward production reliability.",
      "Run the package as a TDD-style AI software factory where humans define specs and tests while agents iterate until outputs pass.",
      "Make specs, test harnesses, scenarios, constraints, and judge criteria the main engineering artifacts; agents should own most implementation syntax.",
      "Use probabilistic satisfaction thresholds as the review gate: scenario performance, failing-case retries, confidence signals, human overrides, and acceptance receipts decide whether the output is reliable enough.",
      "Do not rely on line-by-line human code review for repeatable factory work; validations should become the reviewer and force agents to keep refining until every scenario passes.",
      "Track whether a single expert plus agents is producing output that previously required a full engineering team, because speed is part of the moat.",
      "Feed pass/fail outcomes, rejected outputs, human overrides, and customer acceptance evidence back into context engineering, prompts, tests, and operating rules.",
      "Confirm the buyer has acute enough pain to pay now; do not treat a merely plausible workflow improvement as validated demand.",
      "Use the fire-or-promotion test: the workflow should threaten revenue, cost, speed, risk, promotion, retention, compliance, or business survival if ignored.",
      "Fire means the buyer can imagine being fired, missing promotion, losing credibility, avoiding work, or watching the business suffer if the pain remains.",
      "Promotion means the buyer can imagine advancement, next-year growth, taking over more of the business, or becoming known for fixing the top-priority workflow.",
      "Do not let top-three priority become vague language; name what would be delayed, lost, or risked if the package is not bought now.",
      "Willingness to pay is the binary acuteness check: complaints about price are acceptable when the buyer still pays.",
      "Pricing is also the boring-space validation check: refusal to pay means weak pain, complaining but paying means strong pain, and an immediate yes often means the offer is underpriced.",
      "The best acute opportunities often look obvious in hindsight because they were lying in plain sight inside daily work.",
      "Prefer cases where the current alternative is nothing, unavailable, or broken enough that the buyer cannot solve the critical need with existing staff, software, agencies, or internal process.",
      "Classify the value before launch: make more money, reduce costs, move faster, or avoid risk.",
      "Reject technology-first packaging: do not begin with an interesting AI capability and then invent a use case around it.",
      "Prove the problem is not made up by documenting daily pain, current workarounds, willingness to pay, or behavior the buyer already changes because of the issue.",
      "Run the tar-pit research protocol before promoting a new package: Google prior attempts, talk to operators or founders who tried similar workflows, and document the hard part that blocked adoption, retention, distribution, or workflow change.",
      "Flag social coordination tar pits explicitly: weekend-plan pain, group chats, event lists, and friend invites are universal, but the structural hard part is changing social behavior.",
      "Flag fun discovery tar pits explicitly: restaurant, music, and hobby discovery are picked-over spaces where personal curiosity rarely proves urgent willingness to pay.",
      "Break abstract societal goals into tractable wedges: climate, poverty, and other huge problems need a specific workflow, buyer, budget, and painful transaction before packaging.",
      "Apply extra skepticism to low-hit-rate spaces such as consumer hardware, social networks, and ad tech; require stronger distribution, monetization, and hard-part evidence than usual.",
      "Use the tar-pit avoidance checklist: search prior attempts, interview failed founders or operators, name the hard part, run Fire or Promotion, and compare against boring service workflows.",
      "Track raw demand, qualified demand, completed action, value created, and blocked items.",
      "Separate live connected results from managed-handoff results so the client always understands what is automatic now and what improves with approved account access.",
      "Use the reporting surface as the renewal receipt.",
    ],
    supportAndEscalation: [
      "Use human review for any item that conflicts with the submitted constraints.",
      "Escalate missing or contradictory intake details before sending customer-facing messages.",
      "Escalate regulated claims, payment disputes, privacy requests, angry customers, emergencies, and high-value exceptions.",
      "When optional external accounts are missing, continue with the managed handoff rather than blocking delivery.",
    ],
    ambiguityKillers: [
      "The client bought an outcome, not software to configure.",
      "This is not a co-pilot that waits for a human to operate it; the delivery package should do the work and escalate exceptions.",
      "The strongest industry wedges are service-heavy functions where human labor spend is larger than software spend and the work is already outsourced, staffed, or painful to retain.",
      "Financial/admin, banking operations, healthcare/legal, fragmented verticals, customer support, multilingual support, and language-practice services should be treated as priority replacement maps.",
      "The easiest service replacements are already-outsourced outcome budgets in financial/admin, banking infrastructure, healthcare administration, legal application-layer work, HVAC and construction field services, trucking/logistics, and multilingual support.",
      "Boring schlep is a wedge, not a warning: payroll, tax, trucking compliance, insurance operations, KYC, debt recovery, and regulated admin are where painstaking drudgery becomes process power.",
      "Fragmented non-technical markets such as HVAC, construction, home services, trucking, and local field operations are attractive when weak software adoption lets agents become core workflow infrastructure.",
      "Legal AI should move beyond research copilots into application-layer service replacement with draft artifacts, fact checks, exception routing, and attorney-review boundaries.",
      "Multilingual support is easier for AI when patience and hundreds of languages replace hard-to-staff human queues for global customers, contractors, and DoorDasher-style workforces.",
      "High support attrition is not a side note; it is evidence that repetitive human service work may be ready for AI-native replacement.",
      "Business process automation means performing the service, not merely making an existing human workflow more productive.",
      "Self-regulating automation should monitor outputs, compare them with goals, and adjust the next process step when performance drifts.",
      "Do not sell automation by seats or dashboards when the value is tasks completed, work delivered, accepted outputs, and service capacity created.",
      "The operating model is Individual Contributors building/wrangling agents, Directly Responsible Individuals owning outcomes, and AI Founders leading through daily use of the system.",
      "Use tokens before headcount where tokens replace repeatable operations; humans belong at the edges as builders, operators, QA owners, approvers, and agent wranglers.",
      "AI software factory speed comes from humans defining specs and tests while agents generate code, scripts, workflows, reports, and QA artifacts.",
      "The software factory loop is spec, test, generate, fail, refine, and pass; do not celebrate manual coding volume as the unit of progress.",
      "Closed loops replace open loops: the system measures what happened, compares it with the goal, and changes the next action instead of relying on a human status chain.",
      "The organization must be queryable and legible to AI, which means every process, decision, workflow, exception, and customer outcome needs durable artifacts.",
      "Queryable means AI has a continuous operating-system view from email, Pylon-style support feedback, GitHub commits and issues, Notion or Google Docs plans, sales calls, daily standups, and delivery evidence.",
      "Legible by default means agents can inspect what actually shipped and whether it solved customer needs before recommending the next plan.",
      "Artifact-rich operation means AI meeting notes, decision logs, ticket updates, Slack transcripts, GitHub logs, customer outcomes, and departmental dashboards are operating memory.",
      "Private DMs and inbox-only decisions are context leaks; move durable operating context into shared package surfaces and transparent channels.",
      "Agents should have contextual parity with a human employee from dashboards, systems of record, recordings, Slack, GitHub, tickets, revenue, sales, engineering, hiring, and operations before being asked to plan, route, summarize, or decide.",
      "Autonomous sprint planning should use Linear-style tickets, Slack, GitHub, standup recordings, shipped work, and customer needs to propose the next plan instead of asking managers to reconstruct status by hand.",
      "Autonomous coordination should read tickets, Pylon/email feedback, Notion or Google Docs plans, GitHub commits and issues, sales calls, standup recordings, and delivery evidence before it routes work.",
      "Human middleware is a tax; remove status translation layers where the intelligence layer can route the same information directly.",
      "Humans belong at the edge as builders, operators, QA owners, approvers, and agent wranglers, not in the middle as information routers.",
      "Classic management hierarchy should give way to an intelligence layer that routes status and exceptions from artifacts to accountable owners.",
      "ICs are builder operators in every function; bring working prototypes, agent runs, dashboards, scripts, or customer-ready drafts instead of static pitch decks when the work can be shown.",
      "DRIs follow one person, one outcome: strategy, customer proof, and measured results need a named owner with nowhere to hide behind committee status.",
      "The DRI is not a classic middle manager; the role exists to guide strategy, outcomes, goals, constraints, evals, and escalation rules.",
      "One person, one outcome means no hierarchy hiding: if the result misses, the DRI owns the adjustment path.",
      "The intelligence layer should route information so DRIs are not used as human middleware.",
      "The DRI belongs at the edge near customers and operators, while agents coordinate repeatable work.",
      "Token maxing works only when the DRI can use agents to replace large admin, engineering, or coordination teams without losing outcome accountability.",
      "Information velocity is a DRI responsibility: prevent manual interpretation chains from slowing customer-visible changes.",
      "AI Founders lead by building and coaching with AI tools themselves; delegated AI strategy is an anti-pattern.",
      "Token usage is the scaling unit before headcount when agents can route information and perform repeatable work.",
      "The goal of removing human middleware is direct velocity: fewer middle-manager relays between artifact, agent, owner, and decision.",
      "A single capable operator with agents should replace work that used to require a larger cross-functional team, with humans judging edge cases.",
      "Engineering, HR, admin, support, and operations should stay lean when token spend can replace coordination headcount.",
      "Speed is the first moat: ship, learn, and close reliability gaps faster than labs or incumbents can move through their product process.",
      "One-day sprint cadence is the aspiration for safe changes: DRI spec, agent implementation, acceptance evidence, release.",
      "Incumbent craft overhead is a wedge; PM layers, PRDs, operations reviews, spec docs, approvals, and launch gates are slower than artifact-to-agent loops.",
      "AI-native from day one means prototypes over decks, specs and evals over committee syncs, tokens over coordination headcount, and agents inside repeatable workflows.",
      "Forward-deployed speed comes from sitting with customers, automating boring manual pain in the live workflow, and feeding specialized evals back into the next iteration.",
      "Use the AI Seven Powers map as a practical audit: speed, process power, counterpositioning, switching costs, network economy, cornered resource, scale economies, and branding.",
      "Speed is only the first power; the package needs the last-10-percent reliability work, customer-specific data, and operating evidence that make speed compound.",
      "Process power lives in 99% reliability, vertical evals, scenario thresholds, edge cases, and boring backend workflow rules.",
      "Counterpositioning means work-based pricing should make the operator stronger when automation reduces the customer's manual headcount.",
      "Switching costs come from onboarding depth, custom logic, integrations, approvals, acceptance history, and workflows minted into customer operations.",
      "The eval flywheel is the network economy: every pass, failure, override, and acceptance receipt should improve future package runs.",
      "Cornered resources are proprietary workflow data, tailored time-in-motion observations, specialized evals, domain edge cases, and optimized model routes.",
      "Scale economies and brand matter when reusable infrastructure gets cheaper per outcome and the package becomes the trusted default for the category.",
      "Schlep blindness is an advantage when boring bank, payroll, tax, trucking, insurance, or regulated-admin details scare off faster-looking competitors.",
      "System-of-record lock-in means customer history, decisions, approvals, outcomes, exceptions, eval traces, and reporting receipts stay in the package surfaces.",
      "Painstaking drudgery is found by observing tailored time-in-motion work, mapping request enrichment, and documenting the boring details operators rely on to bridge gaps.",
      "Hidden logic is the prize: informal checks, backend rules, exception paths, reconciliation habits, and operator judgment are the details that a superficial demo misses.",
      "High attrition, especially 50% to 80% in support or admin work, is a signal that the workflow is repetitive and painful enough to replace as a service.",
      "Boring spaces should be validated through observation, not abstraction: tax, payroll, trucking compliance, insurance operations, regulated admin, and healthcare back-office work are attractive only when the schlep exposes real budgeted pain.",
      "Invisible operator pain is a demand clue: phone orders, 1-800 numbers, spreadsheet queues, faxes, inbox handoffs, and specialist tribal knowledge may reveal workflows software builders rarely inspect.",
      "Truck-stop research is a method, not a metaphor: go where the work happens, talk to frontline operators, and find fuel-card-like wedges in daily operations.",
      "Forward-deployed validation means sitting inside the customer's workflow until request intake, enrichment, manual bridges, approvals, and judgment points are visible.",
      "Mission-critical workflows deserve priority when KYC, loan origination, legal review, accounting close, compliance, or customer operations failures can cost serious money.",
      "An 80% hackathon workflow is not production; the final 5% to 20% of consistency is where edge cases, evals, and process power are built.",
      "Existential pain should be visible in the workflow: revenue loss, firing risk, compliance exposure, missed promotion, or business failure if the manual process remains broken.",
      "The goal is to find narrow vertical treasure before broad labs care, then defend it with customer-specific evals, data, and edge-case reliability.",
      "High API spend is rational when it replaces HR, admin, engineering, support coordination, and management routing in a queryable organization.",
      "A healthy intelligence operating system should make shorter sprint cycles and meaningfully higher throughput plausible because agents can see goals, context, work shipped, and feedback.",
      "The long-term direction is spec-first, potentially zero-handwritten-code workflow generation where humans judge outcomes instead of syntax.",
      "A package has not cleared the probabilistic threshold unless threshold evidence explains scenario coverage, retries, failed cases, confidence signals, and acceptance receipts.",
      "Specs-only repositories are the north star for repeatable workflows: specs, scenarios, evals, and harnesses first; handwritten production code as the exception.",
      "Context engineering and prompt engineering are now senior engineering responsibilities, not side chores.",
      "The final 10% of reliability is where the moat lives: scenario validations, vertical evals, QA gates, and domain edge cases matter more than the demo.",
      "Painstaking vertical drudgery is expected in serious service replacement, especially around KYC, loan processing, legal, compliance, healthcare administration, and customer-specific exceptions.",
      "Big labs are not the default competitor for the final 5% of niche consistency; boring vertical drudgery and customer-specific integration depth are the shield.",
      "Mint the agent into the customer's operations by preserving custom thresholds, evals, reconciliation rules, acceptance receipts, and switching-cost evidence.",
      "Per-seat pricing is the wrong default because better automation should reduce manual seats, not reduce value capture.",
      "Per-seat pricing is the incumbent Achilles heel because revenue follows customer headcount; work-based pricing is the AI-native model because revenue follows outcomes completed.",
      "The package should benefit when automation gets better. If fewer customer employees means less revenue, the offer is still thinking like SaaS.",
      "Work-based pricing carries proof burden: longer pilots and acceptance evidence are the cost of reaching the larger services budget.",
      "Price capabilities humans cannot match, such as always-on multilingual patience, by service value and volume rather than by a seat equivalent.",
      "A package must pass the real-problem, tar-pit, founder-market-fit, acute-pain, moat-timing, and pricing-discipline checks before it becomes a repeatable offer.",
      "Acute means top-three priority, not useful someday. If the buyer will not pay, delay, complain, or change behavior, the package is probably nice-to-have.",
      "The Binary Test is charging money, not asking if someone likes the idea; a buyer either opens their wallet or exposes weak value.",
      "Use the Binary Test to learn which customer segment actually cares enough to pay, not merely which segment says the package sounds useful.",
      "Do not hide weak differentiation behind lower price; when the package is meaningfully better, a premium price can validate that buyers value the better outcome.",
      "The cleanest pricing signal is a customer who complains about a high price but still pays because the pain is expensive to leave unsolved.",
      "The best validation is complain but pay: price resistance plus payment beats enthusiastic non-payment.",
      "An instant yes can be a pricing warning in boring spaces; if customers do not flinch, the offer may be underpriced relative to the service pain.",
      "Superficially plausible is not enough; the buyer must actually care about the pain in daily life or daily operations.",
      "Use social coordination apps as the warning example: universal pain around weekend plans, event lists, friend invites, and group planning does not prove people will switch behavior.",
      "Fun discovery apps are not validated by being enjoyable to discuss; restaurant and music discovery still need acute pain, budget, and a reason incumbents failed.",
      "Abstract societal problems are too broad until they become a narrow workflow that someone urgently pays to fix.",
      "Consumer hardware, social networks, and ad tech should trigger a low-hit-rate review before any package is sold.",
      "Every new package needs a written hard-part hypothesis that names the structural barrier it handles differently from failed attempts.",
      "The service budget is the reference point: outsourced work, internal labor, agency operations, admin follow-up, production, reporting, and fulfillment.",
      "The delivery hub is the first place to open.",
      "Each output has its own guide, next action, and acceptance checklist.",
      `A missing optional integration is not a failed launch; it is handled through ${managedHandoffLabel} until approved access is added.`,
      "Success is measured by the intake success metric and the package reporting surface.",
    ],
  };
}

export function buildBundleCustomerGuide(input: {
  brandName: string;
  packageTitles: string[];
  totalArtifacts: number;
  successMetric: string;
  guidanceOptions?: PackageGuidanceOptions;
}): PackageCustomerGuide {
  const packageList = input.packageTitles.join(", ");
  const engineRoleName = input.guidanceOptions?.engineRoleName ?? "Lead OS system";

  return {
    title: `${input.brandName} bundle implementation guide`,
    executiveOverview: `${input.brandName} received ${input.packageTitles.length} complete solution hubs and ${input.totalArtifacts} guided outputs. The bundle should be operated as one connected service-replacement system measured by ${input.successMetric}, not as a set of customer-operated tools.`,
    startHere: [
      "Open the first workspace URL in the bundle.",
      "Review each package guide before assigning work to the client or delivery team.",
      "Use the same intake truth across all selected packages instead of asking the client to submit another form.",
      "Confirm every package has passed acceptance checks.",
    ],
    whatWasProvisioned: input.packageTitles.map((title) => `${title}: complete delivery hub with guided outputs and acceptance checks.`),
    operatingWorkflow: [
      `Operate these selected packages together: ${packageList}.`,
      "Use shared intake details for target market, offer, success metric, current process, constraints, and brand voice.",
      "Route capture, production, follow-up, monetization, and reporting through the package surfaces that match the client's immediate goal.",
      "Keep every decision, handoff, approval, exception, and outcome report in the package surfaces so the customer organization becomes queryable over time.",
      "Use reporting outputs to decide which package should be optimized or expanded first.",
    ],
    implementationRoadmap: [
      {
        phase: "Bundle orientation",
        timing: "Same day",
        actions: [
          "Open every package workspace.",
          "Identify the package that touches the customer's buyer first.",
          "Identify the package that proves value fastest.",
          "Assign owners to each package guide.",
        ],
      },
      {
        phase: "First outcome path",
        timing: "First week",
        actions: [
          "Run a customer scenario through the highest-priority package.",
          "Use adjacent packages only where they support that first outcome.",
          "Record proof in the reporting surface.",
        ],
      },
      {
        phase: "Expansion path",
        timing: "Weeks 2-4",
        actions: [
          "Review which package created the strongest value signal.",
          "Turn that proof into the renewal story.",
          "Add connected account access where it unlocks more value.",
        ],
      },
    ],
    rolesAndResponsibilities: [
      { role: "Client decision maker", responsibility: "Approves the combined outcome priority and success metric." },
      { role: "Package owner", responsibility: "Owns the guide, outputs, and acceptance checks for one selected package." },
      { role: "Delivery operator", responsibility: "Coordinates package handoffs without asking the client for repeat intake." },
      { role: engineRoleName, responsibility: "Launches every selected package from the one submitted form." },
    ],
    measurementPlan: [
      `Shared success metric: ${input.successMetric}.`,
      "Measure bundle value by work delivered, tasks completed, revenue recovered, qualified outcomes, and hours saved.",
      "Do not price the bundle by active users; price against the service spend and manual work removed.",
      "Make the bundle pricing trade-off explicit: per-seat SaaS monetizes headcount and gets punished when automation works, while work-based pricing monetizes completed services and grows with reliable throughput.",
      "Document the bundle per-seat cannibalization trap: if AI reduces customer employee count across selected workflows, a seat-priced vendor loses revenue exactly when the bundle becomes better.",
      "Use services-budget upside as the bundle benchmark: software tools may capture about 1% of spend, while AI-native service replacement can justify 4% to 10% when it performs the work.",
      "Track the reliability trade-off for work-based bundle pricing: pilots, acceptance receipts, and last-10-percent engineering are required before buyers trust the outcomes enough to pay on work delivered.",
      "Do not price superhuman bundle capacity like human seats; patience, 200-language fluency, 24/7 availability, and parallel handling should be monetized by outcomes, tasks, and volume.",
      "Map bundle industry wedges across financial/admin work, banking operations, healthcare/legal services, fragmented vertical markets, customer support, multilingual support, and language-practice services.",
      "Prioritize the easiest bundle replacement wedges: financial/admin services, banking infrastructure, healthcare administration, legal application-layer services, HVAC and construction field services, trucking/logistics, and multilingual support.",
      "Treat outsourced outcome budgets as the strongest bundle signal: agencies, BPOs, brokers, contractors, admin teams, and specialists show the buyer already pays for completed work.",
      "Map boring bundle schlep in payroll, tax, trucking compliance, insurance workflows, KYC, debt recovery, and regulated admin because painstaking drudgery compounds into process power.",
      "Use fragmented non-technical bundle markets like HVAC, construction, home services, trucking, and local field operations where weak software adoption lets agents become operating infrastructure.",
      "Use multilingual bundle support when patient agents fluent across hundreds of languages can serve global customers, international contractors, or DoorDasher-style workforces better than hard-to-staff human teams.",
      "Prioritize bundle workflows already outsourced or staffed as human services because those budgets are easier to replace than software-tool budgets.",
      "Track high-attrition support and admin labor as a buying wedge, especially where 50% to 80% churn makes AI-native service replacement attractive.",
      "Use the bundle as an intelligence operating system across selected workflows, with each package producing artifacts that make the organization more queryable.",
      "Frame the bundle as business process automation that performs selected services, not as co-pilots or productivity tools layered onto human workflows.",
      "Make bundle automation self-regulating by comparing outputs with stated goals and adjusting prompts, routing, tests, approvals, handoffs, or package priorities when performance drifts.",
      "Price bundle automation by tasks completed, work delivered, accepted outputs, and service capacity created rather than seats, logins, dashboards, or productivity claims.",
      "Replace open-loop bundle execution with closed-loop measurement, goal comparison, and process adjustment across package priorities, prompts, tests, routing, and handoffs.",
      "Make the bundle legible to AI by keeping decisions, meetings, tickets, approvals, exceptions, customer outcomes, and follow-up commitments in shared package surfaces and transparent channels.",
      "Make every bundle process, decision, workflow, exception, and outcome queryable so the intelligence layer improves stability and correctness from shared operating data.",
      "Give bundle AI a continuous operating-system view of the company rather than a one-off tool snapshot; package surfaces should point to the artifacts that keep the view current.",
      "Capture bundle communication logs from email, Pylon-style support tools, shared channels, and support queues as first-class operating memory.",
      "Capture bundle technical activity from GitHub commits, pull requests, issues, review notes, deployments, and shipped-work evidence.",
      "Capture bundle planning data from Notion, Google Docs, specs, decision memos, delivery hubs, and package workspaces.",
      "Capture bundle recorded interactions such as sales calls, customer calls, daily standups, transcripts, and follow-up commitments.",
      "Make the bundle legible by default so agents can analyze what actually shipped and whether it addressed customer needs before proposing the next plan.",
      "Run the bundle as an artifact-rich environment with AI notetakers, Slack transcripts, GitHub logs, ticket updates, customer outcomes, and dashboards for revenue, sales, engineering, hiring, and operations.",
      "Give bundle agents contextual parity with a human employee from revenue, sales, engineering, hiring, operations, customer feedback, ticket, Slack, GitHub, recordings, and package-performance dashboards.",
      "Use autonomous sprint planning across the bundle: agents should compare shipped work against customer needs and propose next-cycle plans without lossy manual status rollups.",
      "Base bundle autonomous coordination on queryable evidence: tickets, Pylon/email feedback, Notion or Google Docs plans, GitHub commits and issues, sales calls, standup recordings, and delivery evidence.",
      "Use Linear-style tickets, Slack, GitHub, standup recordings, shipped-work evidence, and customer needs to generate predictable bundle plans and target nearly 10x more useful work.",
      "Remove human middleware where the intelligence layer can route information directly across packages, operators, tickets, and customer-facing evidence.",
      "Move humans to the edge of bundle operations as builders, operators, QA owners, approvers, and agent wranglers instead of information routers.",
      "Replace classic bundle management hierarchy with an intelligence layer that routes package status, decisions, evidence, and exceptions directly to named owners.",
      "Define bundle ICs as builder operators across engineering, support, sales, and operations; bundle meetings should prefer working prototypes, live workflows, agent runs, dashboards, scripts, or customer-ready drafts over static decks.",
      "Define bundle DRIs as one person owning one measurable outcome, with strategy, customer proof, decisions, and improvement loops assigned to a named accountable owner.",
      "Measure bundle DRIs on strategy and customer outcomes, not status routing, headcount management, or middle-management coordination.",
      "Attach one named bundle DRI to one specific result with visible proof, decision rights, and acceptance evidence across the package surfaces.",
      "Check that missed bundle outcomes have a single DRI-owned adjustment path instead of responsibility diffused through committees or manager layers.",
      "Use the bundle intelligence layer to route artifacts, updates, exceptions, and evidence so the DRI guides goals, constraints, evals, escalation rules, and outcomes.",
      "Keep the bundle DRI at the edge of customer and operator reality, close enough to judge exceptions while agents coordinate repeatable work.",
      "Use bundle DRI leverage as a token-maxing measure: one accountable operator with agents should replace large engineering, admin, or coordination teams where the workflow is repeatable.",
      "Track whether bundle information velocity improves because signals move from artifacts to agents, decisions, and customer-visible changes without manual interpretation chains.",
      "Expect the bundle AI Founder archetype to build, coach, test, and use frontier AI tools personally; do not outsource AI strategy to a distant committee or tooling owner.",
      "Use the bundle IC, DRI, and AI Founder archetypes to maximize useful token usage before headcount while keeping humans focused on building, outcomes, judgment, and coaching.",
      "Track direct bundle velocity gain from removing human middleware: artifacts should flow to agents, accountable owners, and decisions without middle-manager status relays.",
      "Design the bundle for single-person agent leverage: one capable operator with AI agents should do work that previously required a larger cross-functional team.",
      "Keep bundle engineering, HR, admin, support, and operations departments lean by maximizing agent throughput and token spend before coordination headcount.",
      "Treat speed as the first bundle moat before data, network, or brand defensibility exists; the bundle should outlearn labs and incumbents by shipping AI-native service improvements faster.",
      "Measure whether queryable bundle data is compressing sprint cycles and helping the same expert team target nearly 10x more useful work.",
      "Use one-day bundle sprint cadence where safe: a DRI defines the spec, test, or eval, agents implement, and acceptance evidence decides release readiness.",
      "Document incumbent craft overhead the bundle exploits: PM layers, operations reviews, PRDs, spec docs, approvals, and launch gates that slow customer-visible change.",
      "Keep the bundle AI-native from day one with prototypes over decks, specs and evals over committee syncs, tokens over coordination headcount, and agents inside repeatable workflows.",
      "Use a forward-deployed bundle speed loop: sit with customers, spot boring manual pain, automate it inside live workflows, and feed usage and eval data back into the next iteration.",
      "Measure the bundle against an AI-native powers portfolio: speed first, then process power, counterpositioning, switching costs, eval network economy, cornered resources, scale economies, branding, schlep blindness, and system-of-record lock-in.",
      "Treat bundle speed as the foundation power: one-day sprint cycles, AI software factories, and forward-deployed customer learning should beat PRD-heavy craft cultures while the deeper bundle moats mature.",
      "Measure bundle process power in the final 5% to 10% of reliability: edge cases, QA gates, scenario validations, and domain rules should move mission-critical workflows toward 99% accuracy.",
      "Measure bundle counterpositioning by checking that work-delivered or task-completed pricing benefits when automation reduces customer headcount instead of punishing the operator like per-seat SaaS.",
      "Measure bundle switching costs by counting onboarding rules, integrations, approvals, exception paths, acceptance history, and customer-specific workflows minted into daily operations.",
      "Measure the bundle eval network economy by tracking pass/fail outcomes, overrides, exceptions, and customer acceptance receipts that improve prompts, context engineering, tests, and routing across selected packages.",
      "Measure bundle cornered resources by preserving proprietary workflow data, tailored time-in-motion observations, specialized evals, domain edge cases, and optimized model routes outsiders cannot see from the demo.",
      "Measure bundle scale economies where static crawls, model optimizations, evaluation harnesses, integrations, compliance checks, and deployment pipelines get cheaper or more reliable per outcome as usage grows.",
      "Measure bundle branding as trust under risk: the bundle should become the remembered reliable service outcome for the category, not just another model-powered dashboard.",
      "Measure bundle schlep blindness and system-of-record lock-in by documenting boring workflow details, bank or regulatory infrastructure work, customer history, decisions, approvals, outcomes, exceptions, eval traces, and reporting receipts.",
      "Discover bundle drudgery through time-in-motion observation across selected workflows rather than guessing from high-level market maps.",
      "Map bundle request paths in detail: email, forms, calls, tickets, spreadsheets, enrichment steps, call center bridges, manual data entry, and judgment points.",
      "Capture hidden bundle logic such as informal checks, reconciliation habits, exception paths, and operator know-how that only appear when the work is observed directly.",
      "Use 50% to 80% attrition in support or admin roles as a bundle signal that repetitive service work may be painful enough to replace.",
      "Search boring bundle workflow spaces such as payroll, tax accounting, trucking compliance, insurance operations, and regulated admin.",
      "Validate boring bundle spaces because unglamorous tax, payroll, trucking compliance, insurance, regulated admin, and healthcare back-office workflows can have higher hit rates than fun picked-over ideas.",
      "Do the bundle schlep before expanding: physically or operationally observe the work, interview frontline operators, and watch each selected workflow in context.",
      "Look for invisible bundle pain programmers rarely see: phone orders, 1-800-number workflows, spreadsheets, faxes, inbox queues, and specialist tribal knowledge that customers have tolerated for years.",
      "Find lossy bundle middleware: status rollups, fragmented handoffs, manager interpretation, duplicated updates, and manual coordination a closed loop can make queryable.",
      "Use truck-stop-style field research for bundles by going where the work happens and talking to frontline operators before naming the wedge.",
      "Use forward-deployed bundle validation to map tailored time-in-motion: request intake, enrichment, call-center bridges, manual entry, approvals, and judgment points before automation is declared real.",
      "Prioritize mission-critical bundle workflows where KYC, loan origination, legal review, accounting close, compliance, or customer-operation failures are expensive.",
      "Separate bundle hackathon demos from production reliability; the final 5% to 20% of consistency is where edge cases and evals become process power.",
      "Treat last-10-percent bundle discovery as validation: edge cases, specialized knowledge, exception paths, and 99% reliability requirements show whether the service mix can actually be replaced.",
      "Filter bundle drudgery for existential pain such as lost revenue, firing risk, compliance exposure, missed promotion, or business failure.",
      "Run the bundle Fire or Promotion test as a separate acuteness gate: the buyer should fear being fired, missing promotion, avoiding the work, or losing business momentum if selected workflows stay broken.",
      "Measure the bundle fire-side signal explicitly: missed numbers, credibility loss, firing risk, no desire to face the work, or business damage.",
      "Measure the bundle promotion-side signal explicitly: advancement, next-year growth, taking over more of the business, or being recognized as the person who fixed a top-three problem.",
      "Confirm the bundle solves a top-three problem now; a useful workflow that can wait is still nice-to-have.",
      "Use willingness to pay as bundle acuteness proof: the buyer should budget, complain but pay, or change behavior because the unsolved pain is more expensive.",
      "Bundle pricing is also the boring-space validation check: refusal to pay means weak pain, complaining but paying means strong pain, and an immediate yes often means the bundle is underpriced.",
      "Run the bundle Binary Test by charging real money and watching whether the buyer opens their wallet; compliments, waitlists, and polite interest do not validate value the way payment does.",
      "Treat bundle refusal to pay as a learning event: the selected workflows may not solve top-three problems, the buyer segment may be wrong, or the delivered value may not overcome the price tag yet.",
      "Use bundle payment behavior to identify the right customer segment: the best segment pays fastest, connects the combined outcome to budget, and tolerates reasonable implementation friction.",
      "Use bundle premium-price tests when the package mix claims superior setup, documentation, integrations, delivery, or outcome proof; better execution should be tested for willingness to pay more.",
      "Treat bundle complain-but-pay as the cleanest validation signal: the buyer feels the price and still pays because the unsolved problem is more expensive.",
      "Watch for bundle opportunities lying in plain sight where high-stakes daily work is obvious to operators but still unsolved because reliability, service replacement, or workflow change is hard.",
      "Mint specialized evals and datasets into customer operations so bundle speed compounds into process power rather than one-off feature churn.",
      "Track whether the bundle has found narrow vertical treasure before labs notice it, then harden edge cases while bigger competitors prioritize broad platform goals.",
      "Measure whether closed-loop coordination shortens bundle sprint cycles and increases useful work from the same expert team.",
      "Track where AI token spend replaced service labor, HR, admin, engineering, and coordination headcount and where human operators handled only approvals, QA, and edge cases.",
      "Measure bundle reliability with scenario validations, evals, human override rates, rejected outputs, and customer acceptance evidence rather than demo polish.",
      "Operate bundle engineering as a spec-and-test factory: humans define the harness and agents iterate until each selected package clears it.",
      "Use probabilistic review gates across the bundle so scenario evidence and acceptance receipts replace line-by-line technical review for repeatable generated work.",
      "Measure bundle process power by backend logic depth, integration surface area, customer-specific evals, acceptance receipts, and switching-cost creation.",
      "Measure bundle process automation moat by the hard last 10% needed to reach 99% accuracy in high-stakes banking, legal, accounting, compliance, healthcare, or regulated service workflows.",
      "Treat pilots as infrastructure-learning loops: preserve custom rules, integrations, reporting, approvals, and acceptance history until the bundle becomes core operating infrastructure.",
      "Use the bundle to compound thousandx-engineer leverage: one expert surrounded by agents should move more workflows than a traditional team.",
      "Design the bundle around token usage before headcount, with agents handling repeatable operations and humans handling strategy, QA, approvals, and complex exceptions.",
      "Treat bundle token maxing as the queryable-organization scaling rule when API spend replaces HR, admin, engineering, support coordination, and management routing.",
      "Use the bundle's eval flywheel to improve context engineering, prompts, tests, routing, and operating rules after every run.",
      "Validate the bundle against acute pain, founder-market fit, tar-pit risk, and willingness to pay before expanding it across niches.",
      "Bundle expansion needs one of the four value cases: make more money, reduce costs, move faster, or avoid risk.",
      "If the bundle is not tied to a top-three priority or a no-real-alternative wedge, treat it as unvalidated even when the demo looks compelling.",
      "Do not bundle AI capabilities into a solution unless the combined workflow maps to real daily pain rather than a made-up problem that sounds logical.",
      "Document prior failed attempts and the bundle's hard-part hypothesis before treating a superficially plausible workflow as a sellable package.",
      "Flag bundle social coordination tar pits explicitly: weekend-plan pain, group chats, event lists, and friend invites are universal, but the structural hard part is changing social behavior.",
      "Flag bundle fun discovery tar pits explicitly: restaurant, music, and hobby discovery are picked-over spaces where personal curiosity rarely proves urgent willingness to pay.",
      "Break abstract bundle goals into tractable wedges: climate, poverty, and other huge problems need a specific workflow, buyer, budget, and painful transaction before packaging.",
      "Apply extra skepticism to low-hit-rate bundle spaces such as consumer hardware, social networks, and ad tech; require stronger distribution, monetization, and hard-part evidence than usual.",
      "Use the bundle tar-pit avoidance checklist: search prior attempts, interview failed founders or operators, name the hard part, run Fire or Promotion, and compare against boring service workflows.",
      "Track package-level outcomes separately and roll them up into one bundle story.",
      "Prioritize optimization where the fastest money, time, or risk value appears.",
    ],
    supportAndEscalation: [
      "Escalate contradictions between selected package outcomes before changing customer-facing copy.",
      "Keep optional account access as managed handoff until approved access is added.",
      "Use package-specific failure states when one package is blocked while others remain live.",
    ],
    ambiguityKillers: [
      "One intake form is enough for the selected package mix.",
      "Each package can stand alone, but the bundle guide explains how to operate them together.",
      "The client should not receive raw artifacts without the package guide and output guides.",
      "The bundle sells service outcomes and operational throughput, not software seats.",
      "Automation success should create more outcome capacity, not per-seat cannibalization.",
      "Per-seat bundle pricing is the incumbent Achilles heel because revenue follows customer headcount; work-based bundle pricing is AI-native because revenue follows completed outcomes.",
      "The bundle should benefit when automation gets better. If fewer customer employees means less revenue, the offer is still thinking like SaaS.",
      "Work-based bundle pricing carries proof burden: longer pilots and acceptance evidence are the cost of reaching the larger services budget.",
      "Price bundle capabilities humans cannot match, such as always-on multilingual patience, by service value and volume rather than by a seat equivalent.",
      "The bundle should target service-heavy industries where labor spend dwarfs software spend, including financial/admin services, banking operations, healthcare/legal, logistics/trucking, HVAC/home services, real estate, debt financing, customer support, and language services.",
      "Already-outsourced work, fragmented non-tech markets, and high-attrition support/admin roles are the strongest bundle entry points.",
      "The easiest bundle replacements are outcome budgets already spent on agencies, BPOs, brokers, contractors, admin teams, and specialists rather than internal software seats.",
      "Boring bundle schlep such as payroll, tax, trucking compliance, insurance operations, KYC, debt recovery, and regulated admin should be welcomed because the drudgery is where process power compounds.",
      "Fragmented non-technical bundle markets such as HVAC, construction, home services, trucking, and local field operations are attractive when agents can be minted into core workflows.",
      "Bundle legal AI should be application-layer service replacement with draft artifacts, fact checks, exception routing, and attorney-review boundaries instead of only research copilots.",
      "Bundle multilingual support should use patient agents fluent across hundreds of languages for global customers, international contractors, and DoorDasher-style workforces.",
      "Humans should wrangle agent fleets and complex exceptions, not perform the repetitive service work the bundle exists to replace.",
      "Bundle business process automation should perform the service paths, create proof, and escalate exceptions instead of acting like a productivity layer.",
      "Bundle value should come from tasks completed, work delivered, accepted outputs, and service capacity, not from logins or dashboards.",
      "Bundle operations should be closed loops, not one-way decisions: measure outcomes, compare with the goal, and update the next package action.",
      "A pilot is not just a trial; it is where custom operating rules, integrations, approvals, reporting, and acceptance history become the customer's core infrastructure.",
      "The bundle organization must be legible to AI: meetings, tickets, approvals, exceptions, customer results, and commitments need artifacts the intelligence layer can query.",
      "The bundle should run as a queryable organization where every process, decision, workflow, exception, and customer outcome is legible to AI.",
      "Queryable bundle operation means AI has a continuous operating-system view from email, Pylon-style support feedback, GitHub commits and issues, Notion or Google Docs plans, sales calls, daily standups, and delivery evidence.",
      "Legible by default means bundle agents can inspect what actually shipped and whether it solved customer needs before recommending the next plan.",
      "Artifact-rich bundle operation means AI notetakers, Slack transcripts, GitHub logs, ticket updates, customer outcomes, and departmental dashboards become operating memory.",
      "Autonomous sprint planning should read package evidence, Linear-style tickets, Slack, GitHub, standup recordings, and customer needs before proposing the next operating plan.",
      "Bundle autonomous coordination should read tickets, Pylon/email feedback, Notion or Google Docs plans, GitHub commits and issues, sales calls, standup recordings, and delivery evidence before it routes work.",
      "Remove human middleware when it only translates status; keep humans for strategy, taste, approvals, and complex exceptions.",
      "Accept high API bills when token spend replaces HR, admin, engineering, and coordination headcount while humans stay at the edge as builders, QA owners, approvers, and agent wranglers.",
      "Classic bundle management hierarchy should give way to an intelligence layer that routes status and exceptions from artifacts to accountable owners.",
      "Bundle ICs are builder operators in every function; bring working prototypes, agent runs, dashboards, scripts, or customer-ready drafts instead of static pitch decks when the work can be shown.",
      "Bundle DRIs follow one person, one outcome: strategy, customer proof, and measured results need a named owner with nowhere to hide behind committee status.",
      "A bundle DRI is not a classic middle manager; the role guides strategy, outcomes, goals, constraints, evals, and escalation rules.",
      "Bundle one person, one outcome means no hierarchy hiding: if the result misses, the DRI owns the adjustment path.",
      "The bundle intelligence layer should route information so DRIs are not used as human middleware.",
      "The bundle DRI belongs at the edge near customers and operators, while agents coordinate repeatable work.",
      "Bundle token maxing works only when the DRI can use agents to replace large admin, engineering, or coordination teams without losing outcome accountability.",
      "Bundle information velocity is a DRI responsibility: prevent manual interpretation chains from slowing customer-visible changes.",
      "Bundle AI Founders lead by building and coaching with AI tools themselves; delegated AI strategy is an anti-pattern.",
      "Bundle token usage is the scaling unit before headcount when agents can route information and perform repeatable work.",
      "The goal of removing bundle human middleware is direct velocity: fewer middle-manager relays between artifact, agent, owner, and decision.",
      "A single capable bundle operator with agents should replace work that used to require a larger cross-functional team, with humans judging edge cases.",
      "Bundle engineering, HR, admin, support, and operations should stay lean when token spend can replace coordination headcount.",
      "Bundle speed is the first moat: ship, learn, and close reliability gaps faster than labs or incumbents can move through their product process.",
      "One-day bundle sprint cadence is the aspiration for safe changes: DRI spec, agent implementation, acceptance evidence, release.",
      "Incumbent craft overhead is a bundle wedge; PM layers, PRDs, operations reviews, spec docs, approvals, and launch gates are slower than artifact-to-agent loops.",
      "AI-native bundle operation from day one means prototypes over decks, specs and evals over committee syncs, tokens over coordination headcount, and agents inside repeatable workflows.",
      "Forward-deployed bundle speed comes from sitting with customers, automating boring manual pain in live workflows, and feeding specialized evals back into the next iteration.",
      "Use the AI Seven Powers map as the bundle audit: speed, process power, counterpositioning, switching costs, network economy, cornered resource, scale economies, and branding.",
      "Bundle speed is only the first power; the bundle also needs last-10-percent reliability work, customer-specific data, and operating evidence that make speed compound.",
      "Bundle process power lives in 99% reliability, vertical evals, scenario thresholds, edge cases, and boring backend workflow rules.",
      "Bundle counterpositioning means work-based pricing should make the operator stronger when automation reduces the customer's manual headcount.",
      "Bundle switching costs come from onboarding depth, custom logic, integrations, approvals, acceptance history, and workflows minted into customer operations.",
      "The bundle eval flywheel is the network economy: every pass, failure, override, and acceptance receipt should improve future package runs.",
      "Bundle cornered resources are proprietary workflow data, tailored time-in-motion observations, specialized evals, domain edge cases, and optimized model routes.",
      "Bundle scale economies and brand matter when reusable infrastructure gets cheaper per outcome and the bundle becomes the trusted default for the category.",
      "Bundle schlep blindness is an advantage when boring bank, payroll, tax, trucking, insurance, or regulated-admin details scare off faster-looking competitors.",
      "Bundle system-of-record lock-in means customer history, decisions, approvals, outcomes, exceptions, eval traces, and reporting receipts stay in the bundle surfaces.",
      "Painstaking bundle drudgery is found by observing tailored time-in-motion work, mapping request enrichment, and documenting the boring details operators use to bridge gaps.",
      "Hidden bundle logic is the prize: informal checks, backend rules, exception paths, reconciliation habits, and operator judgment are the details a superficial demo misses.",
      "High attrition in bundle support or admin work is evidence that the workflow may be repetitive and painful enough to replace as a service.",
      "Boring bundle spaces should be validated through observation, not abstraction: tax, payroll, trucking compliance, insurance operations, regulated admin, and healthcare back-office work are attractive only when the schlep exposes real budgeted pain.",
      "Invisible bundle operator pain is a demand clue: phone orders, 1-800 numbers, spreadsheet queues, faxes, inbox handoffs, and specialist tribal knowledge may reveal workflows software builders rarely inspect.",
      "Truck-stop bundle research means going where the work happens, talking to frontline operators, and finding wedges hidden in daily operations.",
      "Forward-deployed bundle validation means sitting inside customer workflows until request intake, enrichment, manual bridges, approvals, and judgment points are visible.",
      "Mission-critical bundle workflows deserve priority when failures in KYC, loan origination, legal review, accounting close, compliance, or customer operations can cost serious money.",
      "An 80% bundle demo is not production; the final consistency gap is where edge cases, evals, and process power are built.",
      "Existential pain should be visible before bundle expansion: revenue loss, firing risk, compliance exposure, missed promotion, or business failure if the workflow remains broken.",
      "Bundle fire means the buyer can imagine being fired, missing promotion, losing credibility, avoiding work, or watching the business suffer if the pain remains.",
      "Bundle promotion means the buyer can imagine advancement, next-year growth, taking over more of the business, or becoming known for fixing the top-priority workflow.",
      "Do not let bundle top-three priority become vague language; name what would be delayed, lost, or risked if the bundle is not bought now.",
      "Bundle willingness to pay is the binary acuteness check: complaints about price are acceptable when the buyer still pays.",
      "The bundle Binary Test is charging money, not asking if someone likes the idea; a buyer either opens their wallet or exposes weak value.",
      "Use the bundle Binary Test to learn which customer segment actually cares enough to pay, not merely which segment says the package mix sounds useful.",
      "Do not hide weak bundle differentiation behind lower price; when the bundle is meaningfully better, a premium price can validate that buyers value the better outcome.",
      "The best bundle validation is complain but pay: price resistance plus payment beats enthusiastic non-payment.",
      "The best acute bundle opportunities often look obvious in hindsight because they were lying in plain sight inside daily work.",
      "The bundle should find narrow vertical treasure before broad labs care, then defend it with customer-specific evals, data, and edge-case reliability.",
      "High API spend is rational when it replaces HR, admin, engineering, support coordination, and management routing in a queryable bundle.",
      "Bundle moat comes from the last 10%: vertical evals, scenario thresholds, QA gates, and customer-specific edge cases turned into reliable operating paths.",
      "Validation is the reviewer for generated bundle work: agents iterate until every scenario, constraint, and threshold clears, then humans judge the outcome.",
      "A bundle is defensible when the workflows are minted into customer operations with custom logic, integrations, reporting contracts, and hard-to-recreate acceptance history.",
      "Incumbents struggle here because this requires resetting engineering culture around specs, tests, context engineering, prompt engineering, evals, and intelligence loops.",
      "Do not use the bundle to hide a weak idea; each selected package still needs real pain and a buyer willing to pay.",
      "A bundle is acute only when the buyer would put budget behind it now; a polite compliment is not validation.",
      "An instant yes can be a bundle pricing warning; if customers do not flinch, the offer may be underpriced relative to the service pain.",
      "A technology-first bundle is still a solution in search of a problem if customers are not genuinely bothered by the workflow.",
      "A fun, universal coordination problem is not automatically a good bundle; prove why this workflow avoids the social-app tar pit before scaling it.",
      "Fun discovery bundle ideas need more than taste; restaurant, music, and hobby discovery still need acute pain, budget, and a reason incumbents failed.",
      "Abstract societal bundle goals are too broad until they become a narrow workflow that someone urgently pays to fix.",
      "Consumer hardware, social networks, and ad tech should trigger a low-hit-rate bundle review before any package mix is sold.",
      "The first renewal conversation should point to outcomes and acceptance evidence.",
    ],
  };
}
