export type PublicPlanId = "whitelabel-starter" | "whitelabel-growth" | "whitelabel-enterprise";

export interface PublicPlan {
  id: PublicPlanId;
  shortId: "starter" | "growth" | "professional";
  name: string;
  price: string;
  priceValue: number;
  description: string;
  limits: string;
  features: string[];
  recommended: boolean;
}

export const publicPlans: PublicPlan[] = [
  {
    id: "whitelabel-starter",
    shortId: "starter",
    name: "Starter",
    price: "$99/mo",
    priceValue: 9900,
    description: "For one operator validating a lead capture workspace.",
    limits: "100 leads/mo, 1,000 emails, 2 funnels, 3 integrations",
    features: [
      "Hosted lead capture workspace",
      "Basic lead scoring",
      "Email nurture workflow",
      "Embeddable capture script",
      "Operator dashboard access",
    ],
    recommended: false,
  },
  {
    id: "whitelabel-growth",
    shortId: "growth",
    name: "Growth",
    price: "$249/mo",
    priceValue: 24900,
    description: "For teams running several funnels or client workspaces.",
    limits: "500 leads/mo, 5,000 emails, 5 funnels, 10 integrations",
    features: [
      "Everything in Starter",
      "A/B testing surfaces",
      "Attribution views",
      "WhatsApp-ready channel toggle",
      "Three operator seats",
    ],
    recommended: true,
  },
  {
    id: "whitelabel-enterprise",
    shortId: "professional",
    name: "Professional",
    price: "$499/mo",
    priceValue: 49900,
    description: "For operators preparing a production multi-workspace rollout.",
    limits: "2,000 leads/mo, 25,000 emails, unlimited funnels, 10 operators",
    features: [
      "Everything in Growth",
      "Marketplace access surfaces",
      "Priority support lane",
      "Unlimited funnel definitions",
      "Production launch checklist",
    ],
    recommended: false,
  },
];

export const deliveredNow = [
  "A public website that explains the outcome, audience, pricing, and launch path.",
  "A universal intake that collects the client details needed to launch one package or any package bundle.",
  "A generated client delivery hub with capture, operator, reporting, billing, embed, and acceptance-check surfaces.",
  "Customer-ready package outputs that document what was created, where it lives, and what outcome it is meant to improve.",
  "A service-replacement strategy that targets outsourced work, internal labor, or agency budgets instead of per-seat software spend.",
  "Service-heavy market framing for insurance brokerage, accounting, tax audit, compliance, and healthcare administration where services spend can support larger wallet share than software spend.",
  "Financial and administrative service-wedge mapping for accounting, tax audit, payroll, insurance brokerage, compliance, and banking operations.",
  "Banking-operations use-case mapping for KYC, loan origination, debt recovery, and fraud monitoring where mission-critical reliability matters more than demo speed.",
  "Healthcare and legal service mapping where specialized knowledge and last-10-percent accuracy determine whether AI can replace manual service work.",
  "Specialized vertical mapping for logistics, trucking, fuel cards, HVAC, home services, real estate, and debt financing in fragmented non-tech markets.",
  "Customer-support and language-market mapping for multilingual support, international contractor support, and conversation-practice services that AI can provide patiently across languages.",
  "Easiest-replacement industry mapping for financial/admin services, banking infrastructure, healthcare administration, legal application-layer services, HVAC and construction field services, trucking/logistics, and multilingual support.",
  "Outsourced outcome-budget guidance that treats agencies, BPOs, brokers, contractors, admin teams, and specialist vendors as buying signals because the customer already pays for completed work.",
  "Boring-schlep guidance for payroll, tax, trucking compliance, insurance workflows, KYC, debt recovery, and regulated admin where painstaking drudgery creates process power.",
  "Fragmented non-technical market guidance for HVAC, construction, home services, trucking, and local field operations where weak software adoption leaves room to mint agents into core workflows.",
  "Legal application-layer guidance that moves beyond research copilots toward specialized work, draft artifacts, fact checks, exception routing, and attorney-review boundaries.",
  "Multilingual support guidance that uses patient agents fluent across hundreds of languages for global customers, international contractors, and DoorDasher-style workforces.",
  "Outsourced-service readiness guidance that prefers workflows already bought as human services because the replacement budget already exists outside software.",
  "High-attrition labor guidance that targets support and admin functions with 50% to 80% attrition as strong AI-native service-replacement wedges.",
  "Outcome-pricing guidance that frames value around work delivered, tasks completed, accepted outputs, qualified outcomes, recovered revenue, and hours saved.",
  "Pricing trade-off guidance that contrasts per-seat SaaS, where revenue follows customer headcount, with work-based AI-native pricing, where revenue follows completed service outcomes.",
  "Per-seat cannibalization guidance that names the incumbent Achilles heel: better automation reduces customer seats and can reduce vendor revenue under the old model.",
  "Software-budget versus services-budget guidance that treats roughly 1% software wallet share as too small when AI-native service replacement can justify 4% to 10% of the spend it replaces.",
  "Work-based pricing risk guidance that acknowledges longer pilots, acceptance evidence, and last-10-percent reliability work as the price of charging for outcomes.",
  "Superhuman-capability pricing guidance that monetizes always-on patience, 200-language fluency, and parallel handling by service value and volume rather than by seat equivalents.",
  "Pricing survival guidance that requires every package to benefit when AI improves; if automation success shrinks revenue, the offer is still trapped in SaaS thinking.",
  "Business-process automation guidance that frames packages as systems that perform the service itself rather than co-pilots or productivity tools.",
  "Service-performing automation guidance that requires the system to monitor work, take next actions, create proof, and escalate only the exceptions humans should judge.",
  "Self-regulating automation guidance that compares outputs with stated goals and adjusts prompts, routing, tests, approvals, handoffs, or package priorities when performance drifts.",
  "Task-priced automation guidance that ties value to tasks completed, work delivered, accepted outputs, and service capacity rather than seats, logins, dashboards, or productivity claims.",
  "AI-native operating model guidance that treats the package as an intelligence operating system, not a co-pilot, with Individual Contributors, Directly Responsible Individuals, and AI Founders as the delivery archetypes.",
  "Management-hierarchy replacement guidance that routes status and decisions through an intelligence layer instead of relying on human middleware.",
  "IC builder-operator guidance that expects engineering, support, sales, and operations teammates to bring working prototypes instead of static pitch decks.",
  "DRI outcome-ownership guidance that assigns one person to one outcome with visible customer proof and no committee hiding.",
  "DRI strategy guidance that keeps the accountable owner focused on strategy and customer outcomes rather than status routing or headcount management.",
  "DRI result-contract guidance that attaches one named owner to one specific result with proof, decision rights, and no hierarchy hiding.",
  "DRI intelligence-layer guidance that lets agents route artifacts, updates, exceptions, and evidence while the DRI sets goals, constraints, evals, and escalation rules.",
  "DRI edge-role guidance that puts the accountable owner close to customers and operators while AI systems coordinate repeatable work.",
  "DRI token-maxing guidance that uses one accountable operator with agents to replace large engineering, admin, or coordination teams.",
  "DRI information-velocity guidance that keeps signals moving from artifacts to agents, decisions, and customer-visible changes without manual interpretation chains.",
  "AI Founder leadership guidance that keeps founders and senior DRIs using frontier AI tools themselves, building and coaching by example instead of delegating AI strategy.",
  "Token-usage archetype guidance that uses ICs, DRIs, and AI Founders to maximize useful token spend before adding headcount.",
  "Human-middleware velocity guidance that removes middle-manager status relays so artifacts flow directly to agents, owners, and decisions.",
  "Single-person agent leverage guidance that designs package delivery so one capable operator with AI agents can do work previously handled by a larger cross-functional team.",
  "Lean-department guidance that keeps engineering, HR, admin, support, and operations teams smaller by maxing tokens before coordination headcount.",
  "Speed-moat guidance that treats fast AI-native shipping as the first defensibility layer before data, network, or brand moats exist.",
  "Lab-competition guidance that names why narrow customer workflow speed can beat broad labs with more capital and compute.",
  "One-day sprint guidance where a DRI defines the spec, agents implement, and acceptance evidence decides daily release readiness.",
  "Incumbent craft-overhead guidance that uses PM layers, operations reviews, PRDs, spec docs, approvals, and launch gates as the startup's speed gap.",
  "AI-native-from-day-one guidance that favors prototypes over decks, specs and evals over committee syncs, tokens over coordination headcount, and agents inside repeatable workflows.",
  "Forward-deployed speed-loop guidance that turns customer observation, boring manual pain, live workflow automation, and eval feedback into faster iteration.",
  "Moat-powers framework guidance that evaluates every package through speed, process power, counterpositioning, switching costs, eval network economy, cornered resources, scale economies, branding, schlep blindness, and system-of-record lock-in.",
  "AI Seven Powers guidance that treats speed as the foundation and then hardens defensibility through process power, counterpositioning, switching costs, network economy, cornered resources, scale economies, and brand.",
  "Primary-speed-moat guidance that uses one-day sprint cycles, AI software factories, forward-deployed learning, and artifact-to-agent loops to outpace PRD-heavy incumbents and broad labs.",
  "Last-10-percent process-power guidance that turns 99% reliability in KYC, loan origination, legal review, accounting, healthcare administration, compliance, and customer operations into the moat.",
  "Counterpositioning guidance that sells work delivered and tasks completed, so better automation increases value instead of reducing per-seat revenue.",
  "Deep-switching-cost guidance that makes onboarding, custom rules, integrations, fraud-monitoring paths, debt recovery logic, approvals, and acceptance history part of the delivered operating infrastructure.",
  "Eval-network-economy guidance that feeds pass/fail outcomes, overrides, exceptions, customer acceptance receipts, prompts, and context engineering back into every future run.",
  "Cornered-resource guidance that captures proprietary workflow data, tailored time-in-motion observations, specialized evals, domain edge cases, and optimized model routes outsiders cannot infer from the demo.",
  "Scale-economies guidance for reusable infrastructure such as static crawls, model optimizations, evaluation harnesses, integrations, compliance checks, and deployment pipelines.",
  "Branding-trust guidance that makes the package the remembered reliable service outcome even when underlying model capabilities converge.",
  "Schlep-blindness guidance that turns boring payroll, tax accounting, trucking compliance, insurance operations, bank infrastructure, and regulated-admin details into defensibility.",
  "System-of-record lock-in guidance that preserves customer history, decisions, approvals, outcomes, exceptions, eval traces, and reporting receipts in the delivery surfaces.",
  "Outcome Graph moat guidance that captures buyer persona, niche, pain point, offer, workflow steps, accepted outputs, failed outputs, human overrides, pricing tested, renewals, churn reasons, hours saved, revenue recovered, and tasks completed on every run.",
  "Borrowed-tool representation guidance that translates agency resale, CRM-grade trust, integration readiness, GTM data execution, brand governance, production agent operations, and ontology depth into Lead OS service outcomes.",
  "Agency resale guidance with branded client portals, resale packaging, onboarding checklists, rebilling proof, and sell-this-tomorrow package collateral.",
  "System-of-record trust guidance with customer timelines, permissions, audit trails, imports, exports, acceptance receipts, and operating memory.",
  "Connector-readiness guidance that shows what works now, which CRM, calendar, billing, email, SMS, data, or publishing connectors improve it, and which managed handoff covers missing access.",
  "Agent-operations guidance for run logs, approvals, retries, exception queues, human overrides, uptime, reliability scoring, and production service evidence.",
  "Outcome event-schema guidance that turns delivery hub records, operator decisions, pricing tests, exception paths, acceptance receipts, and outcome reports into reusable operating memory.",
  "Vertical eval flywheel guidance that converts failed outputs, accepted outputs, human overrides, and exceptions into scenario validations, prompt updates, routing rules, and QA checks.",
  "Certified Outcome guidance that treats launch proof, acceptance receipts, operating guides, escalation rules, pricing logic, and customer outcome reports as the standard for a defensible package.",
  "Outcome billing moat guidance that ties invoices to accepted outputs, qualified leads, booked calls, recovered revenue, hours saved, tasks completed, or other proven service outcomes.",
  "Package marketplace loop guidance that clones working patterns, improves them with Outcome Graph data, specializes them by vertical, and distributes certified versions faster than bespoke services can.",
  "Painstaking-drudgery discovery guidance that pushes operators past superficially plausible automation and into the unsexy last-10-percent work that makes service replacement reliable.",
  "Forward-deployed time-in-motion guidance that requires sitting with customers, watching tailored workflows minute by minute, and recording how requests, exceptions, and approvals really move.",
  "Nitty-gritty workflow-map guidance that traces how requests arrive by email, forms, calls, tickets, or spreadsheets; how they get enriched; and where manual data entry, call centers, or judgment bridge gaps.",
  "Hidden-logic discovery guidance that captures backend rules, reconciliation habits, informal checks, exception paths, and operator know-how invisible from demos or landing pages.",
  "Attrition-signal guidance that treats 50% to 80% annual turnover in support or admin roles as evidence of torturous work ready for AI-native service replacement.",
  "Boring-workflow schlep guidance for payroll, tax accounting, trucking compliance, insurance operations, regulated admin, and other grinding execution spaces.",
  "Boring-space validation guidance that favors tax, payroll, trucking compliance, insurance operations, regulated admin, and other unglamorous markets because real pain, existing budgets, and lower founder competition can create higher hit rates than fun ideas.",
  "Physical-observation schlep guidance that sends operators to the source of the work for frontline interviews, workflow shadowing, and truck-stop-style field discovery before packaging a workflow.",
  "Invisible-pain discovery guidance for phone-order, 1-800-number, spreadsheet, fax, inbox, and tribal-knowledge workflows that specialists tolerate because software builders rarely observe them directly.",
  "Forward-deployed validation guidance that maps tailored time-in-motion, request intake, enrichment, call-center bridges, manual data entry, approvals, and judgment points before automation is declared real.",
  "Last-10-percent validation guidance that treats edge cases, specialized knowledge, exception paths, and 99% reliability requirements as proof that the workflow can become a trusted service instead of only a demo.",
  "Lossy-middleware discovery guidance that identifies status rollups, fragmented handoffs, manager interpretation, duplicated updates, and manual coordination as closed-loop automation targets.",
  "Truck-stop field-research guidance that sends operators to where the work physically or operationally happens to find fuel-card-style wedges hidden in frontline details.",
  "Mission-critical workflow-filter guidance for KYC, loan origination, legal review, accounting close, compliance checks, and customer operations where a failure can cost millions.",
  "Hackathon-vs-production guidance that separates an 80% demo from the final 5% to 20% of consistency needed for 99% reliability.",
  "Existential-pain workflow guidance that prioritizes drudgery tied to lost revenue, firing risk, compliance exposure, missed promotions, or business failure.",
  "Specialized-eval minting guidance that embeds customer-specific evals and datasets into operations so speed compounds into process power.",
  "Treasure-before-labs guidance that pushes operators to capture valuable narrow verticals and harden edge cases before broad platform competitors notice.",
  "Queryable-organization guidance that makes every process, decision, workflow, exception, and outcome legible to AI so closed loops improve stability and correctness.",
  "Queryable operating-system guidance that gives AI a continuous, up-to-date view of operations rather than a one-off tool snapshot.",
  "Artifact-source guidance that captures communication logs from email and Pylon-style support tools, technical activity from GitHub commits and issues, planning data from Notion or Google Docs, and recordings from sales calls and daily standups.",
  "Legible-by-default guidance that lets agents inspect what actually shipped, compare it with customer needs, and use the evidence before recommending the next plan.",
  "Queryable autonomous-coordination guidance that bases sprint planning on tickets, Pylon/email feedback, Notion or Google Docs plans, GitHub commits and issues, sales calls, standup recordings, and delivery evidence.",
  "Queryable token-maxing guidance that accepts high API spend when it replaces HR, admin, engineering, support coordination, and management routing.",
  "Artifact-rich environment guidance for AI notetakers, decision logs, ticket updates, Slack transcripts, GitHub logs, customer outcomes, and revenue, sales, engineering, hiring, and operations dashboards.",
  "Transparent-channel guidance that minimizes private DMs and email-only decisions by moving important work into shared package surfaces where embedded agents can observe, route, summarize, and learn.",
  "Contextual-parity guidance that gives the intelligence layer employee-grade context before it plans, routes, summarizes, or decides.",
  "Token-maxing guidance that accepts high API spend where it replaces repetitive service labor and moves humans into agent wrangling, approval, QA, and complex exception handling.",
  "Last-10-percent reliability guidance that treats the gap between a demo and 99% production accuracy as the product work, not cleanup.",
  "AI software factory and TDD-loop guidance where humans define specs, tests, scenario validations, and acceptance thresholds while agents iterate until the work passes.",
  "Spec-and-test workflow guidance that makes durable specs, test harnesses, scenario coverage, and judge criteria the main engineering artifacts while agents own implementation syntax.",
  "Probabilistic review-gate guidance that replaces line-by-line code review with scenario performance, confidence evidence, failing-case retries, human overrides, and acceptance receipts.",
  "Validation-as-reviewer guidance that removes human middleware by requiring agents to autonomously refine implementation until every defined scenario and constraint passes.",
  "Zero-handwritten-code posture for new workflow code: push repeatable delivery toward generated implementation backed by specs, evals, harnesses, and outcome review.",
  "Specs-only repository goals that point repeatable workflow repos toward specs, scenario validations, evals, and test harnesses rather than handwritten production code.",
  "Thousandx-engineer leverage that surrounds one expert with agents for implementation drudgery, allowing a small team to produce work that previously required a full engineering team.",
  "Incumbent-reset guidance that names the culture shift from manual coding volume to context engineering, prompt engineering, evals, and intelligence loops.",
  "Eval-flywheel guidance that feeds pass/fail outcomes, rejected outputs, human overrides, edge cases, and customer acceptance evidence back into context engineering, prompts, QA gates, and operating rules.",
  "Closed-loop operating guidance that replaces open-loop decision execution with measurement, goal comparison, and process adjustment until the workflow self-corrects.",
  "Legible-organization guidance that keeps work in transparent channels, package surfaces, shared records, and delivery receipts rather than private DMs or inbox fragments.",
  "Artifact-generation guidance for meeting notes, decision logs, tickets, approval receipts, exception notes, QA traces, customer outcomes, and follow-up commitments.",
  "Comprehensive-context dashboard guidance that feeds models revenue, sales, engineering, hiring, customer feedback, tickets, Slack, GitHub, and package-performance context.",
  "Autonomous sprint-planning guidance where agents inspect shipped work, customer needs, tickets, Slack decisions, GitHub changes, and delivery evidence to propose predictable next-cycle plans.",
  "Sprint-planning intelligence-loop guidance that uses Linear-style tickets, Slack, GitHub, standup recordings, shipped-work evidence, and customer needs to cut planning noise and target nearly 10x more useful work.",
  "Intelligence-layer coordination guidance that replaces middle-management status routing with direct signal flow to owners, agents, package surfaces, and decision records.",
  "Human-middleware removal guidance that cuts status rollups, translation layers, and middle-management handoffs where the intelligence layer can route information directly.",
  "Humans-at-the-edge guidance that places people as builders, operators, QA owners, approvers, and agent wranglers instead of information routers.",
  "Closed-loop velocity guidance that targets shorter sprint cycles and substantially more useful work when agents can see goals, context, shipped work, and feedback.",
  "Process-power moat framing that turns vertical drudgery in KYC, loan-processing, legal, compliance, healthcare administration, and customer-specific edge cases into mission-critical infrastructure.",
  "Wrapper-clone rebuttal that explains why the defensible product is accumulated workflow logic, evals, approvals, exceptions, and operating evidence rather than the demo surface.",
  "99-percent accuracy moat guidance that separates an 80% weekend prototype from mission-critical workflows like loan origination, KYC, legal review, accounting, and compliance.",
  "Deep backend logic guidance that borrows from Stripe/Gusto-style defensibility: policy rules, state transitions, retries, audit trails, permissions, reconciliations, handoffs, and exception paths.",
  "Integration surface-area guidance that compounds client systems, data formats, approval paths, financial-institution-style quirks, imports, exports, and reporting contracts.",
  "Customer-minted workflow guidance that captures custom logic, evals, thresholds, reconciliation rules, and acceptance receipts as switching-cost assets.",
  "Process-automation moat guidance for the painstaking last 10% needed to reach 99% accuracy in banking, legal, accounting, compliance, healthcare, and other high-stakes service environments.",
  "Pilot-to-core-infrastructure guidance that turns customer-specific rules, integrations, reporting, approvals, and acceptance history into operating infrastructure the customer depends on.",
  "Token-maxing cost-shift guidance that treats high API bills as rational when token spend replaces inflated HR, admin, engineering, and coordination headcount.",
  "Token-usage organization guidance that moves repeatable operations to agents and humans to the edges as builders, operators, QA owners, approvers, and agent wranglers.",
  "Startup idea guardrails that reject solution-in-search-of-problem launches, made-up problems, superficially plausible AI applications, tar pit risks, weak founder-market fit, non-acute pain, moat over-analysis, and timid pricing.",
  "Tar-pit category warnings for social coordination apps, restaurant discovery, music discovery, abstract societal problems, consumer hardware, social networks, and ad tech before a package becomes repeatable.",
  "Social coordination tar-pit guidance that treats weekend-plan apps, event lists, friend invites, and group-planning tools as the canonical warning that universal pain does not prove switching behavior.",
  "Fun discovery app warnings that separate restaurant, music, and hobby discovery curiosity from urgent buyer pain and monetizable demand.",
  "Abstract-problem guidance that forces climate, poverty, and other huge goals into tractable workflow wedges with a named buyer, budget, and specific pain point.",
  "Low-hit-rate idea-space guidance that requires extra proof for consumer hardware, social networks, and ad tech because the broad categories have historically lower startup hit rates.",
  "Tar-pit avoidance guidance that forces prior-attempt searches, failed-founder interviews, structural hard-part hypotheses, Fire-or-Promotion checks, and boring-service comparisons before launch.",
  "Acute-pain validation that checks top-three buyer priority, fire-or-promotion stakes, no-real-alternative wedges, and whether customers complain about a high price but still pay.",
  "Fire-or-Promotion acuteness guidance that separates fire risk, promotion upside, top-three priority, willingness to pay, and opportunities lying in plain sight before a package becomes repeatable.",
  "Fire-side validation that looks for buyers who fear being fired, missing a promotion, avoiding the work, losing credibility, or seeing the business suffer if the workflow stays broken.",
  "Promotion-side validation that confirms solving the workflow could help the buyer advance, unlock next-year growth, take over more of the business, or become known for fixing a top-priority problem.",
  "Pricing binary validation that treats refusal to pay as weak pain, complaints plus payment as strong pain, and an immediate yes as a signal the package may be underpriced.",
  "Binary Test definition guidance that requires charging real money to see whether the buyer will open their wallet instead of relying on compliments, waitlists, or polite interest.",
  "Open-wallet value guidance that treats refusal to pay as evidence the package is not yet valuable enough, not urgent enough, or aimed at the wrong segment.",
  "Customer-segment discovery guidance that uses who pays fastest, who connects the outcome to budget, and who tolerates implementation friction to identify the best buyer segment.",
  "Premium-price learning guidance that tests value rather than only undercutting, including the Stripe-style lesson that superior setup, documentation, APIs, or delivery can justify charging more than incumbents.",
  "Complain-but-pay guidance that treats a buyer complaining about price but paying anyway as stronger validation than enthusiasm with no payment.",
  "High-attrition validation that treats 50% to 80% annual churn in support, admin, field, or compliance roles as evidence that repetitive work is painful enough for AI-native service replacement.",
  "Value-category prompts that force every package to prove it helps the buyer make more money, reduce costs, move faster, or avoid risk.",
  "Technology-first trap warnings that force operators to start from daily user pain and manual service workflows instead of starting with interesting AI capabilities and hunting for a use case.",
  "Tar-pit research prompts that use social coordination apps as the warning example, require prior-attempt research, and force a written hard-part hypothesis before packaging a superficially plausible workflow.",
  "Closed-loop outcome receipts that keep decisions, approvals, handoffs, exceptions, and results available for future optimization.",
  "Operator views for readiness, reporting, managed handoffs, and next expansion opportunities.",
];

export const notLiveUntilConfigured = [
  "Client-owned CRM or customer-list access activates direct record sync; until then, Lead OS provides import-ready handoffs.",
  "Client-owned billing access activates live checkout, invoices, subscriptions, claims, or commissions; until then, Lead OS provides payment-ready instructions.",
  "Approved email, SMS, WhatsApp, calendar, phone, or ad-account access activates live external actions; until then, Lead OS creates the scripts, sequences, routing, and approval-ready assets.",
  "Regulated claims, likeness use, financial promises, legal language, and medical content remain behind human approval checkpoints.",
];

export const userJourney = [
  {
    title: "Describe the workspace",
    body: "Enter your email, niche, and business model so the system can create the right lead workspace.",
  },
  {
    title: "Choose the operating plan",
    body: "Pick the plan limits that match the workspace you want to test or launch.",
  },
  {
    title: "Brand the experience",
    body: "Add the public brand name, accent color, website, and support email shown to leads and operators.",
  },
  {
    title: "Select channels",
    body: "Choose which integrations you intend to use. Channels stay inactive until credentials are connected.",
  },
  {
    title: "Use the result",
    body: "Copy the embed script, open the dashboard, and connect production services before sending real traffic.",
  },
];

export function getPublicPlan(id: string | null | undefined): PublicPlan | undefined {
  if (!id) return undefined;
  return publicPlans.find((plan) => plan.id === id || plan.shortId === id);
}
