export interface ClientPreset {
  id: string;
  brandName: string;
  secondaryBrandName: string;
  legalName: string;
  brandPrimary: string;
  brandAccent: string;
  siteUrl: string;
  supportEmail: string;
  adminEmail: string;
  tenantTag: string;
  portalUrl: string;
  marketingHeadline: string;
  marketingDescription: string;
  openGraphDescription: string;
  enabledServices: string[];
  featuredCoreServices: string[];
  featuredBlueOceanServices: string[];
  featuredIndustries: string[];
}

export const clientPresets: Record<string, ClientPreset> = {
  neatcircle: {
    id: "neatcircle",
    brandName: "NeatCircle",
    secondaryBrandName: "Your Deputy",
    legalName: "NeatCircle LLC",
    brandPrimary: "Neat",
    brandAccent: "Circle",
    siteUrl: "https://neatcircle.com",
    supportEmail: "services@neatcircle.com",
    adminEmail: "ike@neatcircle.com",
    tenantTag: "neatcircle",
    portalUrl: "https://portal.yourdeputy.com",
    marketingHeadline: "Business Automation & Process Optimization",
    marketingDescription:
      "Systematic process optimization and operational efficiency solutions for middle-market companies. 209+ premium tools included. Zero software licensing fees.",
    openGraphDescription:
      "209+ premium business tools included in every engagement. Zero software licensing fees. 97% client satisfaction.",
    enabledServices: [
      "client-portal",
      "process-automation",
      "systems-integration",
      "training-platform",
      "business-intelligence",
      "digital-transformation",
      "compliance-training",
      "managed-services",
      "re-syndication",
      "immigration-law",
      "construction",
      "franchise",
      "staffing",
      "church-management",
      "creator-management",
      "compliance-productized",
    ],
    featuredCoreServices: [
      "client-portal",
      "process-automation",
      "systems-integration",
      "training-platform",
      "business-intelligence",
      "digital-transformation",
      "compliance-training",
      "managed-services",
    ],
    featuredBlueOceanServices: [
      "re-syndication",
      "immigration-law",
      "construction",
      "franchise",
      "staffing",
      "church-management",
      "creator-management",
      "compliance-productized",
    ],
    featuredIndustries: [
      "client-portal",
      "process-automation",
      "business-intelligence",
      "managed-services",
      "re-syndication",
      "immigration-law",
    ],
  },
  "professional-services": {
    id: "professional-services",
    brandName: "Professional Services OS",
    secondaryBrandName: "Operator Desk",
    legalName: "Professional Services OS",
    brandPrimary: "Professional",
    brandAccent: "OS",
    siteUrl: "https://professional-services.example.com",
    supportEmail: "hello@professional-services.example.com",
    adminEmail: "ops@professional-services.example.com",
    tenantTag: "professional-services",
    portalUrl: "https://portal.professional-services.example.com",
    marketingHeadline: "Adaptive Lead Capture for High-Ticket Service Firms",
    marketingDescription:
      "Assessments, webinars, AI chat, and pipeline automation for agencies, consultancies, and service operators.",
    openGraphDescription:
      "Intelligent funnels and client acquisition systems for service-led businesses.",
    enabledServices: [
      "client-portal",
      "process-automation",
      "systems-integration",
      "business-intelligence",
      "digital-transformation",
      "managed-services",
      "construction",
      "franchise",
      "staffing",
      "creator-management",
    ],
    featuredCoreServices: [
      "client-portal",
      "process-automation",
      "systems-integration",
      "business-intelligence",
    ],
    featuredBlueOceanServices: [
      "construction",
      "franchise",
      "staffing",
      "creator-management",
    ],
    featuredIndustries: [
      "client-portal",
      "construction",
      "franchise",
      "staffing",
      "creator-management",
      "business-intelligence",
    ],
  },
  "education-compliance": {
    id: "education-compliance",
    brandName: "Training Growth OS",
    secondaryBrandName: "Enablement Desk",
    legalName: "Training Growth OS",
    brandPrimary: "Training",
    brandAccent: "Growth",
    siteUrl: "https://training-growth.example.com",
    supportEmail: "hello@training-growth.example.com",
    adminEmail: "ops@training-growth.example.com",
    tenantTag: "training-growth",
    portalUrl: "https://portal.training-growth.example.com",
    marketingHeadline: "Compliance, LMS, and Enablement Funnels That Convert",
    marketingDescription:
      "Turn knowledge delivery into a product with assessments, webinars, certificates, and automated intake.",
    openGraphDescription:
      "Launch training, compliance, and membership funnels with intelligent routing.",
    enabledServices: [
      "training-platform",
      "compliance-training",
      "compliance-productized",
      "business-intelligence",
      "managed-services",
      "church-management",
    ],
    featuredCoreServices: [
      "training-platform",
      "compliance-training",
      "business-intelligence",
      "managed-services",
    ],
    featuredBlueOceanServices: [
      "compliance-productized",
      "church-management",
    ],
    featuredIndustries: [
      "training-platform",
      "compliance-training",
      "compliance-productized",
      "church-management",
      "business-intelligence",
      "managed-services",
    ],
  },
  "dtc-conversion": {
    id: "dtc-conversion",
    brandName: "DTC Conversion OS",
    secondaryBrandName: "Revenue Desk",
    legalName: "DTC Conversion OS",
    brandPrimary: "DTC",
    brandAccent: "OS",
    siteUrl: "https://dtc-conversion.example.com",
    supportEmail: "hello@dtc-conversion.example.com",
    adminEmail: "ops@dtc-conversion.example.com",
    tenantTag: "dtc-conversion",
    portalUrl: "https://portal.dtc-conversion.example.com",
    marketingHeadline: "Adaptive Acquisition for Offers With Faster Buying Cycles",
    marketingDescription:
      "Giveaways, coupon paths, evergreen proof, and recovery flows for conversion-focused operators.",
    openGraphDescription:
      "Convert more traffic with intelligent entry paths, recovery offers, and automated nurture.",
    enabledServices: [
      "process-automation",
      "systems-integration",
      "business-intelligence",
      "managed-services",
      "creator-management",
    ],
    featuredCoreServices: [
      "process-automation",
      "systems-integration",
      "business-intelligence",
      "managed-services",
    ],
    featuredBlueOceanServices: [
      "creator-management",
    ],
    featuredIndustries: [
      "process-automation",
      "systems-integration",
      "business-intelligence",
      "managed-services",
      "creator-management",
    ],
  },
  // ─── BLUEPRINT PERSONA PRESETS ──────────────────────────────
  "persona-agency": {
    id: "persona-agency",
    brandName: "Agency Growth OS",
    secondaryBrandName: "Client Desk",
    legalName: "Agency Growth OS",
    brandPrimary: "Agency",
    brandAccent: "OS",
    siteUrl: "https://agency-growth.example.com",
    supportEmail: "hello@agency-growth.example.com",
    adminEmail: "ops@agency-growth.example.com",
    tenantTag: "agency-growth",
    portalUrl: "https://portal.agency-growth.example.com",
    marketingHeadline: "Stop Managing 8 Tools. Run All Your Clients From One Dashboard.",
    marketingDescription: "Replace your SaaS sprawl with a unified lead gen, scoring, and nurture platform. Built for agencies managing 5-50 clients across multiple niches.",
    openGraphDescription: "The all-in-one lead operating system for digital marketing agencies. 200+ integrations, white-label ready.",
    enabledServices: ["client-portal", "process-automation", "managed-services", "business-intelligence", "systems-integration"],
    featuredCoreServices: ["client-portal", "process-automation", "managed-services", "business-intelligence"],
    featuredBlueOceanServices: [],
    featuredIndustries: ["client-portal", "process-automation", "managed-services"],
  },
  "persona-saas": {
    id: "persona-saas",
    brandName: "SaaS Launch OS",
    secondaryBrandName: "Product Desk",
    legalName: "SaaS Launch OS",
    brandPrimary: "SaaS",
    brandAccent: "OS",
    siteUrl: "https://saas-launch.example.com",
    supportEmail: "hello@saas-launch.example.com",
    adminEmail: "ops@saas-launch.example.com",
    tenantTag: "saas-launch",
    portalUrl: "https://portal.saas-launch.example.com",
    marketingHeadline: "Launch Your Own Lead Generation SaaS — Zero Code, Full Brand Control",
    marketingDescription: "White-label lead scoring, nurture, and marketplace platform. Stripe billing built in. Deploy your branded SaaS in hours, not months.",
    openGraphDescription: "Build and launch a white-label lead generation SaaS with zero code. Instant deploy with Stripe billing.",
    enabledServices: ["digital-transformation", "systems-integration", "business-intelligence", "process-automation"],
    featuredCoreServices: ["digital-transformation", "systems-integration", "business-intelligence"],
    featuredBlueOceanServices: [],
    featuredIndustries: ["digital-transformation", "systems-integration", "business-intelligence"],
  },
  "persona-leadgen": {
    id: "persona-leadgen",
    brandName: "Lead Marketplace OS",
    secondaryBrandName: "Revenue Desk",
    legalName: "Lead Marketplace OS",
    brandPrimary: "Lead",
    brandAccent: "Marketplace",
    siteUrl: "https://lead-marketplace.example.com",
    supportEmail: "hello@lead-marketplace.example.com",
    adminEmail: "ops@lead-marketplace.example.com",
    tenantTag: "lead-marketplace",
    portalUrl: "https://portal.lead-marketplace.example.com",
    marketingHeadline: "Buy and Sell Pre-Qualified Leads With Real-Time Scoring",
    marketingDescription: "AI-scored lead marketplace with temperature-based pricing. Cold $25, warm $50, hot $100, burning $200. Outcome tracking and quality guarantees built in.",
    openGraphDescription: "The lead marketplace with AI scoring, temperature pricing, and outcome tracking.",
    enabledServices: ["process-automation", "business-intelligence", "systems-integration", "managed-services"],
    featuredCoreServices: ["process-automation", "business-intelligence", "systems-integration"],
    featuredBlueOceanServices: [],
    featuredIndustries: ["process-automation", "business-intelligence"],
  },
  "persona-consultant": {
    id: "persona-consultant",
    brandName: "Consultant Growth OS",
    secondaryBrandName: "Authority Desk",
    legalName: "Consultant Growth OS",
    brandPrimary: "Consultant",
    brandAccent: "OS",
    siteUrl: "https://consultant-growth.example.com",
    supportEmail: "hello@consultant-growth.example.com",
    adminEmail: "ops@consultant-growth.example.com",
    tenantTag: "consultant-growth",
    portalUrl: "https://portal.consultant-growth.example.com",
    marketingHeadline: "We Implement the Lead Systems Other Consultants Just Recommend",
    marketingDescription: "End-to-end implementation + retainer. CRM, automation, portals, and ongoing management for consultants who deliver, not just advise.",
    openGraphDescription: "Implementation-first consulting platform. CRM, automation, and managed services for technology consultants.",
    enabledServices: ["client-portal", "process-automation", "systems-integration", "training-platform", "managed-services", "business-intelligence"],
    featuredCoreServices: ["client-portal", "process-automation", "systems-integration", "managed-services"],
    featuredBlueOceanServices: [],
    featuredIndustries: ["client-portal", "process-automation", "systems-integration"],
  },
  "persona-franchise": {
    id: "persona-franchise",
    brandName: "Franchise Command OS",
    secondaryBrandName: "Territory Desk",
    legalName: "Franchise Command OS",
    brandPrimary: "Franchise",
    brandAccent: "Command",
    siteUrl: "https://franchise-command.example.com",
    supportEmail: "hello@franchise-command.example.com",
    adminEmail: "ops@franchise-command.example.com",
    tenantTag: "franchise-command",
    portalUrl: "https://portal.franchise-command.example.com",
    marketingHeadline: "One Platform. Every Location. Total Brand Control.",
    marketingDescription: "Multi-tenant franchise management with centralized lead routing, brand compliance, performance benchmarking, and territory management. 50+ franchise systems served.",
    openGraphDescription: "The franchise operations platform for multi-location brands. Lead routing, compliance, and benchmarking.",
    enabledServices: ["franchise", "compliance-productized", "managed-services", "training-platform", "business-intelligence"],
    featuredCoreServices: ["managed-services", "training-platform", "business-intelligence"],
    featuredBlueOceanServices: ["franchise", "compliance-productized"],
    featuredIndustries: ["franchise", "compliance-productized", "managed-services"],
  },
  // ─── INDUSTRY NICHE PRESETS ───────────────────────────────
  "niche-legal": {
    id: "niche-legal",
    brandName: "Legal Practice OS",
    secondaryBrandName: "Intake Desk",
    legalName: "Legal Practice OS",
    brandPrimary: "Legal",
    brandAccent: "OS",
    siteUrl: "https://legal-practice.example.com",
    supportEmail: "hello@legal-practice.example.com",
    adminEmail: "ops@legal-practice.example.com",
    tenantTag: "legal-practice",
    portalUrl: "https://portal.legal-practice.example.com",
    marketingHeadline: "Automate Intake. Convert More Consultations. Grow Your Firm.",
    marketingDescription: "Intake automation, compliance tracking, and client communication for law firms. Bar-compliant workflows with 3x consultation conversion.",
    openGraphDescription: "Legal intake automation and practice management. Used by 150+ law firms.",
    enabledServices: ["client-portal", "process-automation", "compliance-training", "managed-services", "immigration-law"],
    featuredCoreServices: ["client-portal", "process-automation", "compliance-training", "managed-services"],
    featuredBlueOceanServices: ["immigration-law"],
    featuredIndustries: ["client-portal", "process-automation", "immigration-law"],
  },
  "niche-construction": {
    id: "niche-construction",
    brandName: "Contractor Growth OS",
    secondaryBrandName: "Project Desk",
    legalName: "Contractor Growth OS",
    brandPrimary: "Contractor",
    brandAccent: "OS",
    siteUrl: "https://contractor-growth.example.com",
    supportEmail: "hello@contractor-growth.example.com",
    adminEmail: "ops@contractor-growth.example.com",
    tenantTag: "contractor-growth",
    portalUrl: "https://portal.contractor-growth.example.com",
    marketingHeadline: "Win More Bids. Finish More Projects. Zero Paperwork.",
    marketingDescription: "Bid follow-up, crew scheduling, change order tracking, and safety compliance for contractors. 35% more bids won on average.",
    openGraphDescription: "Construction project management and bid automation for contractors and builders.",
    enabledServices: ["process-automation", "systems-integration", "managed-services", "construction"],
    featuredCoreServices: ["process-automation", "systems-integration", "managed-services"],
    featuredBlueOceanServices: ["construction"],
    featuredIndustries: ["construction", "process-automation", "managed-services"],
  },
  "niche-real-estate": {
    id: "niche-real-estate",
    brandName: "Real Estate Lead OS",
    secondaryBrandName: "Agent Desk",
    legalName: "Real Estate Lead OS",
    brandPrimary: "Real Estate",
    brandAccent: "Lead OS",
    siteUrl: "https://re-lead.example.com",
    supportEmail: "hello@re-lead.example.com",
    adminEmail: "ops@re-lead.example.com",
    tenantTag: "re-lead",
    portalUrl: "https://portal.re-lead.example.com",
    marketingHeadline: "Respond in Under 5 Minutes. Close 4x More Deals.",
    marketingDescription: "Automated lead follow-up, listing marketing, and open house capture for real estate agents and teams. Used by 250+ agents.",
    openGraphDescription: "Real estate lead generation and CRM automation. Speed-to-lead that closes more deals.",
    enabledServices: ["client-portal", "process-automation", "business-intelligence", "managed-services", "re-syndication"],
    featuredCoreServices: ["client-portal", "process-automation", "business-intelligence"],
    featuredBlueOceanServices: ["re-syndication"],
    featuredIndustries: ["re-syndication", "client-portal", "process-automation"],
  },
  "niche-health": {
    id: "niche-health",
    brandName: "Practice Growth OS",
    secondaryBrandName: "Patient Desk",
    legalName: "Practice Growth OS",
    brandPrimary: "Practice",
    brandAccent: "Growth",
    siteUrl: "https://practice-growth.example.com",
    supportEmail: "hello@practice-growth.example.com",
    adminEmail: "ops@practice-growth.example.com",
    tenantTag: "practice-growth",
    portalUrl: "https://portal.practice-growth.example.com",
    marketingHeadline: "Fill Your Schedule. Reduce No-Shows. Grow Your Practice.",
    marketingDescription: "Patient scheduling, automated reminders, reactivation campaigns, and review management for healthcare practices. 40% no-show reduction.",
    openGraphDescription: "Healthcare practice automation. Scheduling, reminders, and patient reactivation.",
    enabledServices: ["client-portal", "process-automation", "compliance-training", "managed-services"],
    featuredCoreServices: ["client-portal", "process-automation", "compliance-training", "managed-services"],
    featuredBlueOceanServices: [],
    featuredIndustries: ["client-portal", "process-automation", "compliance-training"],
  },
  "niche-tech": {
    id: "niche-tech",
    brandName: "SaaS Growth OS",
    secondaryBrandName: "Product Desk",
    legalName: "SaaS Growth OS",
    brandPrimary: "SaaS",
    brandAccent: "Growth",
    siteUrl: "https://saas-growth.example.com",
    supportEmail: "hello@saas-growth.example.com",
    adminEmail: "ops@saas-growth.example.com",
    tenantTag: "saas-growth",
    portalUrl: "https://portal.saas-growth.example.com",
    marketingHeadline: "Convert More Trials. Reduce Churn. Scale Your SaaS.",
    marketingDescription: "Product-led onboarding, health scoring, churn prediction, and trial conversion automation for SaaS companies.",
    openGraphDescription: "SaaS growth engine. Trial conversion, health scoring, and churn prevention.",
    enabledServices: ["digital-transformation", "systems-integration", "business-intelligence", "process-automation"],
    featuredCoreServices: ["digital-transformation", "systems-integration", "business-intelligence", "process-automation"],
    featuredBlueOceanServices: [],
    featuredIndustries: ["digital-transformation", "systems-integration", "business-intelligence"],
  },
  "niche-education": {
    id: "niche-education",
    brandName: "Enrollment Growth OS",
    secondaryBrandName: "Admissions Desk",
    legalName: "Enrollment Growth OS",
    brandPrimary: "Enrollment",
    brandAccent: "Growth",
    siteUrl: "https://enrollment-growth.example.com",
    supportEmail: "hello@enrollment-growth.example.com",
    adminEmail: "ops@enrollment-growth.example.com",
    tenantTag: "enrollment-growth",
    portalUrl: "https://portal.enrollment-growth.example.com",
    marketingHeadline: "Enroll More Students. Improve Completion. Engage Alumni.",
    marketingDescription: "Admissions nurture, student onboarding, completion tracking, and alumni engagement for educational institutions and training programs.",
    openGraphDescription: "Education enrollment automation. Admissions, retention, and alumni engagement.",
    enabledServices: ["training-platform", "compliance-training", "client-portal", "managed-services"],
    featuredCoreServices: ["training-platform", "compliance-training", "client-portal", "managed-services"],
    featuredBlueOceanServices: [],
    featuredIndustries: ["training-platform", "compliance-training", "client-portal"],
  },
  "niche-finance": {
    id: "niche-finance",
    brandName: "Advisory Practice OS",
    secondaryBrandName: "Compliance Desk",
    legalName: "Advisory Practice OS",
    brandPrimary: "Advisory",
    brandAccent: "OS",
    siteUrl: "https://advisory-practice.example.com",
    supportEmail: "hello@advisory-practice.example.com",
    adminEmail: "ops@advisory-practice.example.com",
    tenantTag: "advisory-practice",
    portalUrl: "https://portal.advisory-practice.example.com",
    marketingHeadline: "Onboard Clients Faster. Stay Compliant. Grow AUM.",
    marketingDescription: "Automated KYC, compliance tracking, client review scheduling, and prospect nurture for financial advisors and accounting firms.",
    openGraphDescription: "Financial practice automation. Onboarding, compliance, and client engagement.",
    enabledServices: ["client-portal", "compliance-training", "process-automation", "business-intelligence", "managed-services"],
    featuredCoreServices: ["client-portal", "compliance-training", "process-automation", "business-intelligence"],
    featuredBlueOceanServices: [],
    featuredIndustries: ["client-portal", "compliance-training", "process-automation"],
  },
  "niche-franchise": {
    id: "niche-franchise",
    brandName: "Franchise Operations OS",
    secondaryBrandName: "Territory Desk",
    legalName: "Franchise Operations OS",
    brandPrimary: "Franchise",
    brandAccent: "Operations",
    siteUrl: "https://franchise-ops.example.com",
    supportEmail: "hello@franchise-ops.example.com",
    adminEmail: "ops@franchise-ops.example.com",
    tenantTag: "franchise-ops",
    portalUrl: "https://portal.franchise-ops.example.com",
    marketingHeadline: "Centralize Lead Routing. Enforce Brand Compliance. Scale Faster.",
    marketingDescription: "Multi-location lead management, franchisee portals, performance benchmarking, and brand compliance for franchise systems.",
    openGraphDescription: "Franchise management platform. Lead routing, compliance, and benchmarking.",
    enabledServices: ["franchise", "compliance-productized", "training-platform", "managed-services", "business-intelligence"],
    featuredCoreServices: ["training-platform", "managed-services", "business-intelligence"],
    featuredBlueOceanServices: ["franchise", "compliance-productized"],
    featuredIndustries: ["franchise", "compliance-productized", "training-platform"],
  },
  "niche-staffing": {
    id: "niche-staffing",
    brandName: "Staffing Pipeline OS",
    secondaryBrandName: "Placement Desk",
    legalName: "Staffing Pipeline OS",
    brandPrimary: "Staffing",
    brandAccent: "Pipeline",
    siteUrl: "https://staffing-pipeline.example.com",
    supportEmail: "hello@staffing-pipeline.example.com",
    adminEmail: "ops@staffing-pipeline.example.com",
    tenantTag: "staffing-pipeline",
    portalUrl: "https://portal.staffing-pipeline.example.com",
    marketingHeadline: "Fill Roles Faster. Delight Clients. Track Every Placement.",
    marketingDescription: "Candidate pipeline, client portals, placement tracking, and revenue analytics for staffing agencies. 50% faster time-to-submittal.",
    openGraphDescription: "Staffing agency automation. Candidate sourcing, placement tracking, and client management.",
    enabledServices: ["client-portal", "process-automation", "business-intelligence", "managed-services", "staffing"],
    featuredCoreServices: ["client-portal", "process-automation", "business-intelligence"],
    featuredBlueOceanServices: ["staffing"],
    featuredIndustries: ["staffing", "client-portal", "process-automation"],
  },
  "niche-faith": {
    id: "niche-faith",
    brandName: "Ministry Platform OS",
    secondaryBrandName: "Congregation Desk",
    legalName: "Ministry Platform OS",
    brandPrimary: "Ministry",
    brandAccent: "Platform",
    siteUrl: "https://ministry-platform.example.com",
    supportEmail: "hello@ministry-platform.example.com",
    adminEmail: "ops@ministry-platform.example.com",
    tenantTag: "ministry-platform",
    portalUrl: "https://portal.ministry-platform.example.com",
    marketingHeadline: "Focus on Ministry, Not Management. Technology That Serves.",
    marketingDescription: "Member portals, online giving, volunteer scheduling, event management, and communication for churches and ministries.",
    openGraphDescription: "Church management platform. Online giving, volunteer scheduling, and congregation engagement.",
    enabledServices: ["client-portal", "training-platform", "managed-services", "church-management"],
    featuredCoreServices: ["client-portal", "training-platform", "managed-services"],
    featuredBlueOceanServices: ["church-management"],
    featuredIndustries: ["church-management", "client-portal", "training-platform"],
  },
  "niche-creative": {
    id: "niche-creative",
    brandName: "Creative Agency OS",
    secondaryBrandName: "Studio Desk",
    legalName: "Creative Agency OS",
    brandPrimary: "Creative",
    brandAccent: "OS",
    siteUrl: "https://creative-agency.example.com",
    supportEmail: "hello@creative-agency.example.com",
    adminEmail: "ops@creative-agency.example.com",
    tenantTag: "creative-agency",
    portalUrl: "https://portal.creative-agency.example.com",
    marketingHeadline: "Streamline Intake. Speed Up Approvals. Grow Your Studio.",
    marketingDescription: "Project intake automation, client approval workflows, portfolio-to-lead conversion, and revenue tracking for creative agencies and studios.",
    openGraphDescription: "Creative agency workflow automation. Intake, approvals, and project management.",
    enabledServices: ["client-portal", "process-automation", "business-intelligence", "managed-services", "creator-management"],
    featuredCoreServices: ["client-portal", "process-automation", "business-intelligence"],
    featuredBlueOceanServices: ["creator-management"],
    featuredIndustries: ["creator-management", "client-portal", "process-automation"],
  },
  "niche-service": {
    id: "niche-service",
    brandName: "Service Business OS",
    secondaryBrandName: "Growth Desk",
    legalName: "Service Business OS",
    brandPrimary: "Service",
    brandAccent: "OS",
    siteUrl: "https://service-business.example.com",
    supportEmail: "hello@service-business.example.com",
    adminEmail: "ops@service-business.example.com",
    tenantTag: "service-business",
    portalUrl: "https://portal.service-business.example.com",
    marketingHeadline: "Capture More Leads. Book More Jobs. Grow Without Hiring.",
    marketingDescription: "Lead capture, automated follow-up, review generation, and booking automation for plumbing, HVAC, electrical, and other service businesses.",
    openGraphDescription: "Service business automation. Lead capture, booking, and customer retention.",
    enabledServices: ["client-portal", "process-automation", "systems-integration", "managed-services", "construction"],
    featuredCoreServices: ["client-portal", "process-automation", "systems-integration", "managed-services"],
    featuredBlueOceanServices: ["construction"],
    featuredIndustries: ["construction", "client-portal", "process-automation"],
  },
};

export const defaultClientPresetId = "neatcircle";
