// ────────────────────────────────────────────────────────────────────────────
// Glossary Data — erie.pro
// Industry-specific glossary terms for all 12 niches.
// Each term includes a definition useful for Erie, PA homeowners.
// ────────────────────────────────────────────────────────────────────────────

export interface GlossaryTerm {
  term: string;
  definition: string;
}

export const GLOSSARY_DATA: Record<string, GlossaryTerm[]> = {
  plumbing: [
    { term: "Backflow Preventer", definition: "A device installed on your water system that prevents contaminated water from flowing backward into the clean water supply. Required by Erie building code on irrigation systems and commercial properties." },
    { term: "P-Trap", definition: "The U-shaped pipe beneath sinks and drains that holds water to block sewer gases from entering your home. If you smell rotten eggs near a drain, the P-trap may have dried out." },
    { term: "PRV (Pressure Reducing Valve)", definition: "A valve that reduces incoming water pressure to a safe level (typically 40-60 PSI). Erie municipal water pressure can exceed 80 PSI, making PRVs essential for protecting pipes and fixtures." },
    { term: "Sump Pump", definition: "A pump installed in the lowest point of a basement that removes accumulated water and channels it away from the foundation. Critical for Erie homes due to heavy rainfall and snowmelt." },
    { term: "Tankless Water Heater", definition: "A water heater that heats water on demand rather than storing it in a tank. While energy efficient, Erie's cold incoming water temperature (35-40°F in winter) requires proper sizing." },
    { term: "PEX Piping", definition: "Flexible cross-linked polyethylene tubing increasingly used in Erie homes as a replacement for copper. PEX resists freezing better than rigid pipe, making it ideal for our climate." },
    { term: "Main Shutoff Valve", definition: "The primary valve that controls all water entering your home. Every Erie homeowner should know its location — during a burst pipe emergency, shutting this off immediately limits damage." },
    { term: "Sewer Scope", definition: "A camera inspection of your sewer line from the house to the street. Recommended before buying an older Erie home, as many have original clay or cast-iron sewer lines." },
    { term: "Backflow", definition: "The unwanted reversal of water flow in your plumbing system, which can contaminate drinking water with wastewater. Annual backflow testing is required in Erie for certain installations." },
    { term: "Flapper Valve", definition: "The rubber seal inside your toilet tank that lifts when you flush and reseals to allow the tank to refill. A worn flapper is the most common cause of a running toilet." },
    { term: "Auger (Drain Snake)", definition: "A flexible metal cable fed into a drain to break through clogs. Professional-grade augers can clear blockages that chemical drain cleaners cannot, especially in Erie's older cast-iron pipes." },
    { term: "Water Hammer", definition: "A banging noise in pipes caused by the sudden stoppage of water flow. Common in Erie homes with high water pressure and can damage pipes over time if not addressed." },
    { term: "Shutoff Valve", definition: "Individual valves located near each fixture (toilet, sink, washing machine) that allow you to cut water to that fixture without shutting off the entire house." },
    { term: "Ejector Pump", definition: "A pump that handles wastewater from below-grade fixtures (basement bathrooms, laundry). Unlike sump pumps that handle clean water, ejector pumps are designed for sewage." },
    { term: "Expansion Tank", definition: "A small tank connected to your water heater that absorbs excess pressure caused by thermal expansion. Required by code in Erie for closed water systems." },
    { term: "Galvanized Pipe", definition: "Steel pipe coated with zinc, common in Erie homes built before 1960. These pipes corrode internally over time, restricting water flow and potentially leaching lead. Replacement with copper or PEX is recommended." },
  ],

  hvac: [
    { term: "AFUE (Annual Fuel Utilization Efficiency)", definition: "A measurement of furnace efficiency as a percentage. A 96% AFUE furnace converts 96 cents of every dollar spent on gas into heat. Given Erie's long heating season, high-AFUE models save significantly." },
    { term: "SEER (Seasonal Energy Efficiency Ratio)", definition: "The cooling efficiency rating for air conditioners and heat pumps. Higher SEER means lower operating costs. For Erie's moderate cooling season, a 14-16 SEER unit offers the best value." },
    { term: "Heat Pump", definition: "A system that both heats and cools by transferring heat rather than generating it. Modern cold-climate heat pumps work in Erie winters, though many homes pair them with a gas furnace backup." },
    { term: "Manual J Load Calculation", definition: "The industry-standard method for determining the correct HVAC system size for your home. Factors in insulation, windows, square footage, and Erie's climate zone." },
    { term: "Ductwork", definition: "The network of metal or flexible tubes that distributes heated or cooled air throughout your home. Leaky ducts can waste 20-30% of your heating energy — significant during Erie winters." },
    { term: "Thermostat", definition: "The device that controls your HVAC system. Smart thermostats can save Erie homeowners $100-$200 per year by learning schedules and adjusting for occupancy." },
    { term: "Air Handler", definition: "The indoor component of a split HVAC system that circulates air through your ducts. Contains the blower motor and evaporator coil." },
    { term: "Condenser", definition: "The outdoor unit of your air conditioning or heat pump system. Should be kept clear of snow, ice, and debris — particularly important during Erie's lake effect storms." },
    { term: "Evaporator Coil", definition: "The indoor coil that absorbs heat from your home's air during cooling. A frozen evaporator coil is a common AC problem, often caused by low refrigerant or poor airflow." },
    { term: "Zoning System", definition: "A setup that divides your home into independently controlled temperature zones. Useful in multi-story Erie homes where upper floors are warmer in summer and cooler in winter." },
    { term: "Dual-Fuel System", definition: "A heating setup that combines a heat pump with a gas furnace. The heat pump handles mild weather efficiently, switching to gas during Erie's coldest days for maximum comfort and savings." },
    { term: "BTU (British Thermal Unit)", definition: "The standard measurement of heating and cooling capacity. Erie homes typically need 40-50 BTUs per square foot for heating, depending on insulation quality." },
    { term: "MERV Rating", definition: "A filter efficiency rating from 1 to 20. For most Erie homes, MERV 8-12 filters offer good air quality without restricting airflow. Higher ratings require compatible HVAC systems." },
    { term: "Refrigerant", definition: "The chemical compound in your AC or heat pump that absorbs and releases heat to cool or warm your home. Low refrigerant usually indicates a leak that needs professional repair." },
    { term: "Humidifier", definition: "A device that adds moisture to heated air. Erie's winter air can drop to 15-20% humidity indoors, causing dry skin, static electricity, and damage to wood floors and furniture." },
    { term: "Carbon Monoxide Detector", definition: "A safety device that detects CO gas from malfunctioning furnaces, water heaters, or gas appliances. PA law requires CO detectors in every Erie home with fuel-burning appliances." },
  ],

  electrical: [
    { term: "Panel Upgrade", definition: "Replacing your home's electrical panel (breaker box) with a higher-capacity unit. Many older Erie homes still have 100-amp panels; modern needs often require 200 amps, especially for EV chargers or heat pumps." },
    { term: "GFCI (Ground Fault Circuit Interrupter)", definition: "A safety outlet that cuts power when it detects electrical current flowing through water or a person. Required by code in Erie kitchens, bathrooms, garages, and outdoor outlets." },
    { term: "AFCI (Arc Fault Circuit Interrupter)", definition: "A breaker that detects dangerous electrical arcs — a leading cause of house fires. Required by current code in Erie bedrooms and living areas." },
    { term: "Knob and Tube Wiring", definition: "An outdated wiring method found in Erie homes built before 1940. While not immediately dangerous, it lacks grounding and cannot handle modern electrical loads. Many insurers require replacement." },
    { term: "Grounding", definition: "A safety system that provides a path for electrical current to safely dissipate into the earth. Ungrounded outlets (two-prong) are common in older Erie homes and should be upgraded." },
    { term: "Circuit Breaker", definition: "A safety device in your electrical panel that trips (shuts off) when a circuit is overloaded. Frequent tripping indicates an overloaded circuit or a wiring problem." },
    { term: "Dedicated Circuit", definition: "A circuit that serves only one appliance or area. Required for high-draw appliances like dryers, ovens, and HVAC systems. Adding circuits is common during Erie home renovations." },
    { term: "Load Center", definition: "Another name for your electrical panel or breaker box — the central distribution point for all electricity in your home." },
    { term: "Whole-House Generator", definition: "A permanently installed generator that automatically powers your home during outages. Popular in Erie due to winter storms and lake-effect power disruptions." },
    { term: "Surge Protector (Whole-House)", definition: "A device installed at your electrical panel that protects all electronics and appliances from power surges. Erie's lightning storms and grid fluctuations make this a smart investment." },
    { term: "EV Charger Installation", definition: "Adding a Level 2 (240V) charging station for electric vehicles. Requires a dedicated 40-50 amp circuit and may necessitate a panel upgrade in older Erie homes." },
    { term: "Recessed Lighting", definition: "Light fixtures installed into the ceiling for a clean, modern look. Proper insulation contact (IC) rated fixtures are essential in Erie to maintain ceiling insulation integrity." },
    { term: "Wire Gauge", definition: "The thickness of electrical wire, measured in AWG (American Wire Gauge). Lower numbers mean thicker wire. Using the wrong gauge for a circuit is a fire hazard." },
    { term: "Amperage", definition: "The measure of electrical current flow. Your home's total amperage capacity determines how many circuits and appliances it can safely support simultaneously." },
    { term: "Transfer Switch", definition: "A device that safely switches your home's power source between the grid and a generator, preventing dangerous backfeed to utility lines." },
  ],

  roofing: [
    { term: "Asphalt Shingles", definition: "The most common roofing material in Erie, offering good weather protection at a moderate price. Architectural (dimensional) shingles last 25-30 years and resist Erie's wind and snow better than 3-tab." },
    { term: "Ice Dam", definition: "A ridge of ice that forms at the roof edge, preventing melting snow from draining. Extremely common in Erie due to lake effect snow. Can cause water to back up under shingles and into your home." },
    { term: "Ice and Water Shield", definition: "A self-adhesive waterproof membrane installed under shingles at the eaves, valleys, and around penetrations. Essential in Erie — code requires it on the first 3 feet from the eave." },
    { term: "Flashing", definition: "Metal strips installed at roof joints, valleys, chimneys, and vent pipes to prevent water intrusion. Flashing failure is one of the most common causes of roof leaks in Erie." },
    { term: "Soffit", definition: "The underside of the roof overhang. Vented soffits allow air into the attic, which is critical for preventing ice dams in Erie's winter climate." },
    { term: "Ridge Vent", definition: "A continuous vent along the roof peak that allows hot, moist air to escape the attic. Works with soffit vents to maintain proper attic ventilation and prevent ice dams." },
    { term: "Roof Pitch", definition: "The angle or steepness of a roof, expressed as a ratio (e.g., 6:12 means 6 inches of rise per 12 inches of run). Steeper pitches shed Erie's heavy snow more effectively." },
    { term: "Tear-Off", definition: "Complete removal of existing roofing material before installing new shingles. Erie code allows a maximum of two layers; a tear-off is required before adding a third." },
    { term: "Underlayment", definition: "A water-resistant barrier installed over roof decking and under shingles. Synthetic underlayment is increasingly preferred in Erie for its superior moisture protection." },
    { term: "Fascia", definition: "The vertical board running along the roof edge where gutters attach. Damaged fascia in Erie often results from ice buildup and can lead to gutter failure." },
    { term: "Drip Edge", definition: "A metal strip installed at roof edges that directs water away from the fascia and into the gutters. Required by current building code in Erie." },
    { term: "Attic Ventilation", definition: "The system of intake (soffit) and exhaust (ridge) vents that circulates air through the attic. Proper ventilation prevents ice dams in winter and reduces cooling costs in summer." },
    { term: "Valley", definition: "The V-shaped channel where two roof slopes meet. Valleys handle concentrated water flow and are prone to leaks if not properly flashed and shingled." },
    { term: "Wind Uplift", definition: "The force of wind lifting shingles from the roof surface. Erie's lakefront location and exposure to strong storms require shingles rated for high wind speeds." },
    { term: "Gutter Guards", definition: "Covers or screens installed over gutters to prevent debris accumulation. Particularly useful in Erie neighborhoods with heavy tree coverage." },
    { term: "Roof Decking", definition: "The plywood or OSB boards nailed to the rafters that form the base for your roofing material. Water-damaged decking must be replaced during a reroof." },
  ],

  landscaping: [
    { term: "Hardscape", definition: "The non-living elements of a landscape: patios, walkways, retaining walls, and driveways. In Erie, hardscaping must account for freeze-thaw cycles that can crack improperly installed surfaces." },
    { term: "Grading", definition: "The slope of the ground around your home. Proper grading directs water away from the foundation — critical in Erie where spring snowmelt and heavy rain cause basement flooding." },
    { term: "Aeration", definition: "The process of poking small holes in your lawn to allow air, water, and nutrients to reach grass roots. Best done in early fall in Erie for cool-season grass varieties." },
    { term: "Overseeding", definition: "Spreading grass seed over an existing lawn to fill thin spots and improve density. In Erie, the best window is September when soil temperatures are ideal for germination." },
    { term: "Perennial", definition: "A plant that returns year after year. Erie-hardy perennials (Zone 6a) include coneflowers, hostas, daylilies, and black-eyed Susans that survive our cold winters." },
    { term: "Retaining Wall", definition: "A structure built to hold back soil on a slope. In Erie, retaining walls must be engineered to handle frost heave and the pressure of saturated soil during spring thaw." },
    { term: "Mulch", definition: "Organic material (wood chips, bark) spread around plants to retain moisture, suppress weeds, and regulate soil temperature. Apply 2-3 inches in Erie gardens after the last spring frost." },
    { term: "French Drain", definition: "A gravel-filled trench with a perforated pipe that redirects groundwater away from problem areas. A common solution for Erie homes with persistent yard flooding." },
    { term: "Native Plants", definition: "Plants that naturally occur in the Lake Erie region. Native species like switchgrass, Joe-Pye weed, and serviceberry require less maintenance and support local wildlife." },
    { term: "Dethatching", definition: "Removing the layer of dead grass and organic debris (thatch) that accumulates between the soil and grass blades. Thick thatch prevents water and nutrients from reaching roots." },
    { term: "Cool-Season Grass", definition: "Grass varieties that thrive in Erie's climate, including Kentucky bluegrass, perennial ryegrass, and fescue. They grow most actively in spring and fall." },
    { term: "Frost Heave", definition: "The upward movement of soil and structures caused by freezing moisture expanding underground. Can damage patios, walkways, and retaining walls in Erie if base preparation is inadequate." },
    { term: "Irrigation System", definition: "An automated sprinkler system for your lawn and garden. In Erie, systems must be winterized (blown out) before the first freeze to prevent pipe damage." },
    { term: "Landscape Bed", definition: "A defined garden area separated from the lawn, typically edged and mulched. Bed design should consider Erie's sun exposure, drainage, and winter hardiness." },
    { term: "Topdressing", definition: "Applying a thin layer of compost or soil over your lawn to improve soil quality and levelness. Combined with aeration, it revitalizes compacted Erie lawns." },
  ],

  dental: [
    { term: "Crown", definition: "A tooth-shaped cap placed over a damaged tooth to restore its shape, size, and strength. Crowns typically last 10-15 years and can be made from porcelain, ceramic, or metal." },
    { term: "Root Canal", definition: "A procedure to remove infected pulp from inside a tooth, clean the canal, and seal it. Modern root canals are relatively painless and save teeth that would otherwise need extraction." },
    { term: "Veneer", definition: "A thin porcelain shell bonded to the front of a tooth to improve its appearance. Veneers address discoloration, chips, gaps, and minor misalignment." },
    { term: "Dental Implant", definition: "A titanium post surgically placed in the jawbone that serves as a permanent foundation for a replacement tooth. The gold standard for replacing missing teeth." },
    { term: "Periodontal Disease", definition: "Infection of the gums and bone supporting the teeth, commonly called gum disease. Early-stage gingivitis is reversible; advanced periodontitis can lead to tooth loss." },
    { term: "Fluoride Treatment", definition: "A preventive application of concentrated fluoride to strengthen tooth enamel and resist decay. Erie's municipal water is fluoridated, but professional treatments provide additional protection." },
    { term: "Orthodontics", definition: "The dental specialty focused on correcting misaligned teeth and jaws. Options include traditional braces, clear aligners (Invisalign), and lingual braces." },
    { term: "Dental Bridge", definition: "A fixed prosthetic that replaces one or more missing teeth by anchoring to adjacent natural teeth. An alternative to implants that typically costs less." },
    { term: "TMJ/TMD", definition: "Temporomandibular joint disorder — pain and dysfunction in the jaw joint and surrounding muscles. Symptoms include jaw clicking, headaches, and difficulty chewing." },
    { term: "Prophylaxis", definition: "A professional dental cleaning performed by a hygienist. Recommended every 6 months to remove plaque, tartar, and stains that brushing and flossing miss." },
    { term: "Dental Sealant", definition: "A thin protective coating applied to the chewing surfaces of back teeth to prevent cavities. Especially recommended for children and teens." },
    { term: "Extraction", definition: "The removal of a tooth. Simple extractions involve visible teeth; surgical extractions are required for impacted or broken teeth, including wisdom teeth." },
    { term: "Whitening", definition: "Professional teeth bleaching that removes stains and lightens tooth color. In-office treatments produce faster results than take-home trays or over-the-counter products." },
    { term: "Bite Adjustment (Occlusal)", definition: "Reshaping the biting surfaces of teeth to correct an uneven bite. An uneven bite can cause jaw pain, headaches, and premature wear on certain teeth." },
    { term: "Night Guard", definition: "A custom-fitted oral appliance worn during sleep to prevent teeth grinding (bruxism). Protects teeth, crowns, and fillings from grinding damage." },
    { term: "Composite Filling", definition: "A tooth-colored resin material used to fill cavities. Composites blend with natural tooth color, unlike silver amalgam fillings." },
  ],

  legal: [
    { term: "Retainer", definition: "An upfront fee paid to secure an attorney's services. Retainers are common for ongoing matters like family law cases and are drawn down as the attorney bills hours." },
    { term: "Contingency Fee", definition: "A payment arrangement where the attorney's fee is a percentage (typically 33-40%) of the settlement or judgment. Common in personal injury cases — you pay nothing if you lose." },
    { term: "Deposition", definition: "Sworn out-of-court testimony given by a witness or party, recorded by a court reporter. Depositions are a standard part of the discovery process in civil litigation." },
    { term: "Discovery", definition: "The pre-trial process where both sides exchange information, documents, and evidence. Includes depositions, interrogatories, and requests for documents." },
    { term: "Statute of Limitations", definition: "The legal deadline for filing a lawsuit. In Pennsylvania, personal injury claims must be filed within 2 years, and breach of contract within 4 years." },
    { term: "Power of Attorney", definition: "A legal document authorizing someone to act on your behalf in legal or financial matters. Pennsylvania recognizes both general and durable powers of attorney." },
    { term: "Mediation", definition: "A voluntary dispute resolution process where a neutral mediator helps parties reach agreement. Often faster and less expensive than going to trial in Erie County courts." },
    { term: "Estate Planning", definition: "The process of arranging for the management and distribution of your assets after death or incapacitation. Includes wills, trusts, powers of attorney, and healthcare directives." },
    { term: "Probate", definition: "The legal process of validating a will and distributing a deceased person's assets. In Pennsylvania, probate is handled by the Register of Wills in Erie County." },
    { term: "Living Trust", definition: "A legal entity that holds assets during your lifetime and transfers them to beneficiaries upon death, bypassing probate. Revocable trusts offer flexibility while alive." },
    { term: "Personal Injury", definition: "A legal claim for physical or psychological harm caused by another party's negligence. Common cases in Erie include car accidents, slip-and-fall injuries, and workplace incidents." },
    { term: "Child Custody", definition: "The legal arrangement determining where a child lives and who makes decisions about their care. Pennsylvania courts prioritize the child's best interest in all custody decisions." },
    { term: "DUI/DWI", definition: "Driving under the influence charges in Pennsylvania. PA has tiered penalties based on blood alcohol level: general impairment (0.08-0.099%), high rate (0.10-0.159%), and highest rate (0.16%+)." },
    { term: "Tort", definition: "A civil wrong that causes harm to another person, giving the injured party the right to sue for damages. Personal injury claims are the most common type of tort case." },
    { term: "Plea Bargain", definition: "A negotiated agreement between a defendant and prosecutor where the defendant pleads guilty to a lesser charge in exchange for a reduced sentence." },
    { term: "Arbitration", definition: "A private dispute resolution process where an arbitrator makes a binding decision. Faster than court proceedings but with limited appeal options." },
  ],

  cleaning: [
    { term: "Deep Clean", definition: "A thorough, intensive cleaning that goes beyond regular maintenance. Includes scrubbing grout, cleaning inside appliances, washing baseboards, and addressing areas normally skipped in routine cleaning." },
    { term: "Move-In/Move-Out Clean", definition: "A comprehensive cleaning performed when tenants change in a rental property. Covers every surface to return the unit to like-new condition and typically meets lease requirements." },
    { term: "Green Cleaning", definition: "Cleaning using environmentally friendly, non-toxic products. Important for homes with children, pets, or family members with chemical sensitivities." },
    { term: "Recurring Service", definition: "A scheduled cleaning at regular intervals — weekly, biweekly, or monthly. Recurring service typically costs less per visit than one-time cleanings." },
    { term: "Post-Construction Clean", definition: "Specialized cleaning after renovation or construction work. Removes drywall dust, paint splatters, adhesive residue, and construction debris." },
    { term: "Sanitizing vs. Disinfecting", definition: "Sanitizing reduces bacteria to a safe level; disinfecting kills nearly all bacteria and viruses. Disinfecting is recommended for bathrooms, kitchens, and during illness." },
    { term: "HEPA Filter", definition: "High-Efficiency Particulate Air filter that captures 99.97% of particles. HEPA-equipped vacuums are essential for allergy sufferers and thorough dust removal." },
    { term: "Bonded and Insured", definition: "A bonded cleaning company has purchased a surety bond to protect clients against theft or damage. Insurance covers accidental property damage during cleaning." },
    { term: "Spot Treatment", definition: "Targeted cleaning of specific stains or areas, particularly on carpets and upholstery. Different stains require different treatment methods for effective removal." },
    { term: "High-Touch Surfaces", definition: "Frequently touched areas like door handles, light switches, countertops, and faucets. Regularly disinfecting these surfaces reduces germ transmission." },
    { term: "Steam Cleaning", definition: "Using pressurized steam to clean and sanitize surfaces without chemicals. Effective for tile, grout, hardwood, and upholstery. Kills bacteria, dust mites, and allergens." },
    { term: "Window Cleaning (Interior/Exterior)", definition: "Professional cleaning of all window glass, sills, and tracks. Erie's lake proximity and seasonal pollen make regular window cleaning important for maintaining curb appeal." },
    { term: "Carpet Extraction", definition: "Hot water extraction (often called steam cleaning) that deep-cleans carpets by injecting hot water and cleaning solution, then extracting dirty water. Recommended annually for Erie homes." },
    { term: "Decluttering Service", definition: "Organizing and removing excess items to create a cleaner, more functional living space. Often performed before a deep clean or listing a home for sale." },
    { term: "Janitorial Service", definition: "Regular commercial cleaning including trash removal, restroom sanitizing, floor care, and surface wiping. Tailored to office buildings, retail spaces, and medical facilities." },
  ],

  "auto-repair": [
    { term: "Diagnostic Scan", definition: "Using an OBD-II scanner to read your vehicle's computer codes and identify problems. Modern vehicles have dozens of sensors, and a diagnostic scan pinpoints issues quickly." },
    { term: "Alignment", definition: "Adjusting the angles of your wheels to the manufacturer's specifications. Erie's potholes and rough winter roads frequently knock wheels out of alignment." },
    { term: "Brake Pads vs. Rotors", definition: "Brake pads are the friction material that presses against the rotor (disc) to slow your car. Pads wear faster and need replacement every 30,000-70,000 miles; rotors last longer but may need resurfacing or replacement." },
    { term: "Transmission Flush", definition: "A complete replacement of your transmission fluid, removing old fluid and contaminants. Recommended every 30,000-60,000 miles depending on driving conditions." },
    { term: "Catalytic Converter", definition: "An emissions control device that converts harmful exhaust gases into less harmful ones. Pennsylvania requires a functioning catalytic converter to pass the annual safety inspection." },
    { term: "Pennsylvania State Inspection", definition: "An annual vehicle safety inspection required by PA law. Covers brakes, tires, lights, steering, suspension, and exhaust. Erie County also requires an emissions inspection." },
    { term: "Timing Belt/Chain", definition: "A belt or chain that synchronizes the engine's camshaft and crankshaft. A broken timing belt can cause catastrophic engine damage. Replacement intervals vary by manufacturer." },
    { term: "Suspension", definition: "The system of springs, shocks, struts, and linkages connecting your vehicle to its wheels. Erie's road conditions accelerate suspension wear." },
    { term: "Coolant Flush", definition: "Draining old antifreeze/coolant and replacing it with fresh fluid. Critical in Erie — proper coolant protects your engine from freezing in winter and overheating in summer." },
    { term: "CV Joint/Boot", definition: "Constant velocity joints allow your drive axles to flex while transmitting power. The rubber boots that protect them crack over time; a torn boot leads to joint failure if not caught early." },
    { term: "Serpentine Belt", definition: "A single belt that drives multiple engine accessories (alternator, power steering, AC compressor). Belts degrade faster in Erie's temperature extremes and should be inspected regularly." },
    { term: "Wheel Bearing", definition: "Bearings that allow your wheels to spin freely on the axle. A humming or grinding noise that changes with speed often indicates a worn wheel bearing." },
    { term: "OBD-II", definition: "On-Board Diagnostics, the standardized vehicle computer system present in all cars since 1996. Mechanics connect to the OBD-II port to read trouble codes and diagnose issues." },
    { term: "Undercoating", definition: "A protective coating applied to the vehicle's undercarriage to prevent rust. Highly recommended in Erie due to heavy road salt use during winter months." },
    { term: "All-Season vs. Winter Tires", definition: "All-season tires handle moderate winter conditions; dedicated winter tires provide significantly better traction in snow and ice. Many Erie drivers switch to winter tires November through April." },
  ],

  "pest-control": [
    { term: "IPM (Integrated Pest Management)", definition: "A strategy combining prevention, monitoring, and targeted treatment to control pests with minimal chemical use. The preferred approach for environmentally conscious pest control." },
    { term: "Termite Inspection", definition: "A thorough examination of your home for signs of termite activity and damage. Recommended during real estate transactions and every 1-3 years for Erie homeowners." },
    { term: "Bait Station", definition: "A device placed around your home's perimeter containing slow-acting bait that pests carry back to their colony. Used for termites, ants, and rodents." },
    { term: "Perimeter Treatment", definition: "Applying pesticide around the exterior foundation of your home to create a barrier against crawling insects. Typically reapplied quarterly in Erie." },
    { term: "Rodent Exclusion", definition: "Sealing gaps, cracks, and entry points in your home's exterior to prevent mice and rats from entering. Mice can squeeze through openings as small as a dime." },
    { term: "Bed Bug Treatment", definition: "Specialized extermination of bed bugs using heat treatment, chemical application, or a combination. Heat treatment (raising room temperature to 120-140°F) is the most effective single-visit option." },
    { term: "Carpenter Ant", definition: "Large black ants that excavate wood to build nests (unlike termites, they don't eat wood). Common in Erie homes with moisture problems, especially around windows and in basements." },
    { term: "Subterranean Termite", definition: "Termites that live in soil and build mud tubes to reach wood in your home. The primary termite species found in the Erie region, causing billions in damage nationally each year." },
    { term: "Fumigation", definition: "A whole-structure treatment that fills the building with gaseous pesticide. Reserved for severe infestations (like drywood termites) and requires vacating the home for 24-72 hours." },
    { term: "German Cockroach", definition: "A small, fast-reproducing roach species commonly found in kitchens and bathrooms. The most common indoor cockroach in Erie and one of the hardest to eliminate." },
    { term: "Wildlife Removal", definition: "Humane trapping and relocation of animals like raccoons, squirrels, and bats from your home. In Pennsylvania, certain species are protected and require licensed removal." },
    { term: "Preventive Maintenance Plan", definition: "A scheduled pest control service (monthly, bimonthly, or quarterly) designed to prevent infestations before they start. Most cost-effective for long-term pest management." },
    { term: "Attic Insulation Removal", definition: "Removing contaminated insulation from attics after rodent or wildlife infestation. Droppings, urine, and nesting materials can create health hazards." },
    { term: "Stink Bug", definition: "Brown marmorated stink bugs that invade Erie homes in fall seeking warmth. Not harmful but extremely nuiseous when crushed. Prevention through sealing entry points is the best strategy." },
    { term: "Mosquito Treatment", definition: "Yard treatment targeting mosquito breeding areas and resting spots. Particularly important near Erie's waterways and in neighborhoods near Presque Isle Bay." },
  ],

  painting: [
    { term: "Primer", definition: "A preparatory coating applied before paint to improve adhesion, cover stains, and ensure uniform color. Erie homes with older lead paint, water stains, or new drywall all need primer." },
    { term: "Sheen (Finish)", definition: "The level of gloss in paint: flat, eggshell, satin, semi-gloss, and high-gloss. Higher sheen resists moisture better (ideal for Erie bathrooms and kitchens) but shows imperfections more." },
    { term: "VOC (Volatile Organic Compound)", definition: "Chemicals released as paint dries, contributing to indoor air pollution. Low-VOC and zero-VOC paints are safer for occupied homes, especially during Erie's closed-window winter months." },
    { term: "Lead Paint", definition: "Paint containing lead, found in homes built before 1978. Erie has many older homes with lead paint. Disturbing lead paint requires EPA-certified renovators following lead-safe work practices." },
    { term: "Caulking", definition: "Applying flexible sealant to gaps around windows, doors, trim, and siding joints. Essential prep work before exterior painting in Erie to prevent moisture infiltration." },
    { term: "Power Washing", definition: "High-pressure water cleaning of exterior surfaces before painting. Removes dirt, mildew, and loose paint to ensure proper adhesion of the new coat." },
    { term: "Skim Coat", definition: "A thin layer of joint compound applied over an entire wall surface to create a smooth, uniform finish. Necessary for Erie homes with damaged plaster or heavily patched drywall." },
    { term: "Cut-In", definition: "Painting precise lines with a brush along edges, corners, and trim before rolling the larger surfaces. Quality cut-in work separates professional painters from amateurs." },
    { term: "Two-Coat System", definition: "Applying one coat of primer and one coat of paint, or two coats of paint. Most professional Erie painters recommend two coats of finish paint for durability and uniform coverage." },
    { term: "Exterior Paint Season", definition: "The window of weather suitable for exterior painting. In Erie, this runs roughly May through October, when temperatures stay above 50°F and humidity is manageable." },
    { term: "Wallpaper Removal", definition: "Stripping existing wallpaper before painting. Older Erie homes often have multiple layers of wallpaper that must be removed, and walls may need skim coating afterward." },
    { term: "Color Consultation", definition: "Professional guidance on paint color selection. Many Erie painting contractors offer this service, helping you choose colors that complement your home's architecture and natural lighting." },
    { term: "Elastomeric Paint", definition: "A thick, flexible coating that bridges hairline cracks and repels water. An excellent option for Erie's masonry and stucco exteriors exposed to freeze-thaw cycles." },
    { term: "Mil Thickness", definition: "The measurement of paint film thickness (1 mil = 1/1000th of an inch). Professional painters ensure proper mil thickness for longevity — especially important for Erie's harsh weather exposure." },
    { term: "Cabinet Refinishing", definition: "Painting or staining kitchen cabinets to refresh their appearance without full replacement. A cost-effective kitchen update that typically costs 70-80% less than new cabinets." },
  ],

  "real-estate": [
    { term: "CMA (Comparative Market Analysis)", definition: "A report comparing your property to recently sold similar homes to determine fair market value. Erie agents use comparable sales data from the Greater Erie Board of Realtors MLS." },
    { term: "Closing Costs", definition: "Fees and expenses paid at the real estate closing beyond the purchase price. In Pennsylvania, buyers typically pay 2-5% of the purchase price in closing costs; sellers pay 6-10% including agent commissions." },
    { term: "Home Inspection", definition: "A thorough examination of a property's condition before purchase. In Erie, inspections commonly reveal issues related to older construction, basement moisture, and roof condition." },
    { term: "Appraisal", definition: "An independent assessment of a property's market value, required by mortgage lenders. If the appraisal comes in below the offer price, the buyer may need to renegotiate or cover the difference." },
    { term: "Escrow", definition: "A neutral third party that holds funds and documents during the transaction. In PA, escrow also refers to the account your lender uses to pay property taxes and homeowner's insurance." },
    { term: "Title Insurance", definition: "Insurance protecting against claims on property ownership. Pennsylvania buyers typically purchase both lender's and owner's title insurance at closing." },
    { term: "Pre-Approval", definition: "A lender's conditional commitment to loan you a specific amount based on your financial information. Stronger than pre-qualification and essential in competitive Erie market conditions." },
    { term: "Buyer's Agent vs. Listing Agent", definition: "A buyer's agent represents the purchaser's interests; a listing agent represents the seller. In Pennsylvania, agents must disclose who they represent at the start of the relationship." },
    { term: "MLS (Multiple Listing Service)", definition: "The database where real estate agents share property listings. The Greater Erie Board of Realtors operates the local MLS used by Erie-area agents." },
    { term: "Contingency", definition: "A condition that must be met for a real estate contract to proceed. Common contingencies include home inspection, financing, and appraisal contingencies." },
    { term: "Deed", definition: "The legal document transferring property ownership. In Pennsylvania, deeds are recorded with the Erie County Recorder of Deeds to establish public record of ownership." },
    { term: "HOA (Homeowners Association)", definition: "An organization in some developments that sets rules and collects fees for maintenance of shared spaces. Common in newer Erie-area subdivisions and condominium complexes." },
    { term: "Transfer Tax", definition: "A tax paid when property changes hands. Pennsylvania charges a 2% transfer tax (1% from buyer, 1% from seller) on real estate transactions, with some local additions." },
    { term: "Disclosure Statement", definition: "A document where the seller discloses known defects and issues with the property. Pennsylvania law requires sellers to complete a detailed property disclosure form." },
    { term: "Short Sale", definition: "A sale where the property sells for less than the outstanding mortgage balance, requiring lender approval. Less common in strong markets but may apply to distressed Erie properties." },
    { term: "Earnest Money", definition: "A deposit made by the buyer to demonstrate serious intent, typically 1-3% of the purchase price. Held in escrow and applied to the purchase at closing." },
  ],
};

export function getGlossaryTerms(slug: string): GlossaryTerm[] {
  return GLOSSARY_DATA[slug] ?? [];
}
