// ────────────────────────────────────────────────────────────────────────────
// Glossary Data — erie.pro
// Industry-specific glossary terms for all 12 niches.
// Each term includes a definition useful for Erie, PA homeowners.
// ────────────────────────────────────────────────────────────────────────────

export interface GlossaryTerm {
  term: string;
  definition: string;
}

export const GLOSSARY_DATA: Record<string, GlossaryTerm[]> = {
  plumbing: [
    { term: "Backflow Preventer", definition: "A device installed on your water system that prevents contaminated water from flowing backward into the clean water supply. Required by Erie building code on irrigation systems and commercial properties." },
    { term: "P-Trap", definition: "The U-shaped pipe beneath sinks and drains that holds water to block sewer gases from entering your home. If you smell rotten eggs near a drain, the P-trap may have dried out." },
    { term: "PRV (Pressure Reducing Valve)", definition: "A valve that reduces incoming water pressure to a safe level (typically 40-60 PSI). Erie municipal water pressure can exceed 80 PSI, making PRVs essential for protecting pipes and fixtures." },
    { term: "Sump Pump", definition: "A pump installed in the lowest point of a basement that removes accumulated water and channels it away from the foundation. Critical for Erie homes due to heavy rainfall and snowmelt." },
    { term: "Tankless Water Heater", definition: "A water heater that heats water on demand rather than storing it in a tank. While energy efficient, Erie's cold incoming water temperature (35-40°F in winter) requires proper sizing." },
    { term: "PEX Piping", definition: "Flexible cross-linked polyethylene tubing increasingly used in Erie homes as a replacement for copper. PEX resists freezing better than rigid pipe, making it ideal for our climate." },
    { term: "Main Shutoff Valve", definition: "The primary valve that controls all water entering your home. Every Erie homeowner should know its location — during a burst pipe emergency, shutting this off immediately limits damage." },
    { term: "Sewer Scope", definition: "A camera inspection of your sewer line from the house to the street. Recommended before buying an older Erie home, as many have original clay or cast-iron sewer lines." },
    { term: "Backflow", definition: "The unwanted reversal of water flow in your plumbing system, which can contaminate drinking water with wastewater. Annual backflow testing is required in Erie for certain installations." },
    { term: "Flapper Valve", definition: "The rubber seal inside your toilet tank that lifts when you flush and reseals to allow the tank to refill. A worn flapper is the most common cause of a running toilet." },
    { term: "Auger (Drain Snake)", definition: "A flexible metal cable fed into a drain to break through clogs. Professional-grade augers can clear blockages that chemical drain cleaners cannot, especially in Erie's older cast-iron pipes." },
    { term: "Water Hammer", definition: "A banging noise in pipes caused by the sudden stoppage of water flow. Common in Erie homes with high water pressure and can damage pipes over time if not addressed." },
    { term: "Shutoff Valve", definition: "Individual valves located near each fixture (toilet, sink, washing machine) that allow you to cut water to that fixture without shutting off the entire house." },
    { term: "Ejector Pump", definition: "A pump that handles wastewater from below-grade fixtures (basement bathrooms, laundry). Unlike sump pumps that handle clean water, ejector pumps are designed for sewage." },
    { term: "Expansion Tank", definition: "A small tank connected to your water heater that absorbs excess pressure caused by thermal expansion. Required by code in Erie for closed water systems." },
    { term: "Galvanized Pipe", definition: "Steel pipe coated with zinc, common in Erie homes built before 1960. These pipes corrode internally over time, restricting water flow and potentially leaching lead. Replacement with copper or PEX is recommended." },
  ],

  hvac: [
    { term: "AFUE (Annual Fuel Utilization Efficiency)", definition: "A measurement of furnace efficiency as a percentage. A 96% AFUE furnace converts 96 cents of every dollar spent on gas into heat. Given Erie's long heating season, high-AFUE models save significantly." },
    { term: "SEER (Seasonal Energy Efficiency Ratio)", definition: "The cooling efficiency rating for air conditioners and heat pumps. Higher SEER means lower operating costs. For Erie's moderate cooling season, a 14-16 SEER unit offers the best value." },
    { term: "Heat Pump", definition: "A system that both heats and cools by transferring heat rather than generating it. Modern cold-climate heat pumps work in Erie winters, though many homes pair them with a gas furnace backup." },
    { term: "Manual J Load Calculation", definition: "The industry-standard method for determining the correct HVAC system size for your home. Factors in insulation, windows, square footage, and Erie's climate zone." },
    { term: "Ductwork", definition: "The network of metal or flexible tubes that distributes heated or cooled air throughout your home. Leaky ducts can waste 20-30% of your heating energy — significant during Erie winters." },
    { term: "Thermostat", definition: "The device that controls your HVAC system. Smart thermostats can save Erie homeowners $100-$200 per year by learning schedules and adjusting for occupancy." },
    { term: "Air Handler", definition: "The indoor component of a split HVAC system that circulates air through your ducts. Contains the blower motor and evaporator coil." },
    { term: "Condenser", definition: "The outdoor unit of your air conditioning or heat pump system. Should be kept clear of snow, ice, and debris — particularly important during Erie's lake effect storms." },
    { term: "Evaporator Coil", definition: "The indoor coil that absorbs heat from your home's air during cooling. A frozen evaporator coil is a common AC problem, often caused by low refrigerant or poor airflow." },
    { term: "Zoning System", definition: "A setup that divides your home into independently controlled temperature zones. Useful in multi-story Erie homes where upper floors are warmer in summer and cooler in winter." },
    { term: "Dual-Fuel System", definition: "A heating setup that combines a heat pump with a gas furnace. The heat pump handles mild weather efficiently, switching to gas during Erie's coldest days for maximum comfort and savings." },
    { term: "BTU (British Thermal Unit)", definition: "The standard measurement of heating and cooling capacity. Erie homes typically need 40-50 BTUs per square foot for heating, depending on insulation quality." },
    { term: "MERV Rating", definition: "A filter efficiency rating from 1 to 20. For most Erie homes, MERV 8-12 filters offer good air quality without restricting airflow. Higher ratings require compatible HVAC systems." },
    { term: "Refrigerant", definition: "The chemical compound in your AC or heat pump that absorbs and releases heat to cool or warm your home. Low refrigerant usually indicates a leak that needs professional repair." },
    { term: "Humidifier", definition: "A device that adds moisture to heated air. Erie's winter air can drop to 15-20% humidity indoors, causing dry skin, static electricity, and damage to wood floors and furniture." },
    { term: "Carbon Monoxide Detector", definition: "A safety device that detects CO gas from malfunctioning furnaces, water heaters, or gas appliances. PA law requires CO detectors in every Erie home with fuel-burning appliances." },
  ],

  electrical: [
    { term: "Panel Upgrade", definition: "Replacing your home's electrical panel (breaker box) with a higher-capacity unit. Many older Erie homes still have 100-amp panels; modern needs often require 200 amps, especially for EV chargers or heat pumps." },
    { term: "GFCI (Ground Fault Circuit Interrupter)", definition: "A safety outlet that cuts power when it detects electrical current flowing through water or a person. Required by code in Erie kitchens, bathrooms, garages, and outdoor outlets." },
    { term: "AFCI (Arc Fault Circuit Interrupter)", definition: "A breaker that detects dangerous electrical arcs — a leading cause of house fires. Required by current code in Erie bedrooms and living areas." },
    { term: "Knob and Tube Wiring", definition: "An outdated wiring method found in Erie homes built before 1940. While not immediately dangerous, it lacks grounding and cannot handle modern electrical loads. Many insurers require replacement." },
    { term: "Grounding", definition: "A safety system that provides a path for electrical current to safely dissipate into the earth. Ungrounded outlets (two-prong) are common in older Erie homes and should be upgraded." },
    { term: "Circuit Breaker", definition: "A safety device in your electrical panel that trips (shuts off) when a circuit is overloaded. Frequent tripping indicates an overloaded circuit or a wiring problem." },
    { term: "Dedicated Circuit", definition: "A circuit that serves only one appliance or area. Required for high-draw appliances like dryers, ovens, and HVAC systems. Adding circuits is common during Erie home renovations." },
    { term: "Load Center", definition: "Another name for your electrical panel or breaker box — the central distribution point for all electricity in your home." },
    { term: "Whole-House Generator", definition: "A permanently installed generator that automatically powers your home during outages. Popular in Erie due to winter storms and lake-effect power disruptions." },
    { term: "Surge Protector (Whole-House)", definition: "A device installed at your electrical panel that protects all electronics and appliances from power surges. Erie's lightning storms and grid fluctuations make this a smart investment." },
    { term: "EV Charger Installation", definition: "Adding a Level 2 (240V) charging station for electric vehicles. Requires a dedicated 40-50 amp circuit and may necessitate a panel upgrade in older Erie homes." },
    { term: "Recessed Lighting", definition: "Light fixtures installed into the ceiling for a clean, modern look. Proper insulation contact (IC) rated fixtures are essential in Erie to maintain ceiling insulation integrity." },
    { term: "Wire Gauge", definition: "The thickness of electrical wire, measured in AWG (American Wire Gauge). Lower numbers mean thicker wire. Using the wrong gauge for a circuit is a fire hazard." },
    { term: "Amperage", definition: "The measure of electrical current flow. Your home's total amperage capacity determines how many circuits and appliances it can safely support simultaneously." },
    { term: "Transfer Switch", definition: "A device that safely switches your home's power source between the grid and a generator, preventing dangerous backfeed to utility lines." },
  ],

  roofing: [
    { term: "Asphalt Shingles", definition: "The most common roofing material in Erie, offering good weather protection at a moderate price. Architectural (dimensional) shingles last 25-30 years and resist Erie's wind and snow better than 3-tab." },
    { term: "Ice Dam", definition: "A ridge of ice that forms at the roof edge, preventing melting snow from draining. Extremely common in Erie due to lake effect snow. Can cause water to back up under shingles and into your home." },
    { term: "Ice and Water Shield", definition: "A self-adhesive waterproof membrane installed under shingles at the eaves, valleys, and around penetrations. Essential in Erie — code requires it on the first 3 feet from the eave." },
    { term: "Flashing", definition: "Metal strips installed at roof joints, valleys, chimneys, and vent pipes to prevent water intrusion. Flashing failure is one of the most common causes of roof leaks in Erie." },
    { term: "Soffit", definition: "The underside of the roof overhang. Vented soffits allow air into the attic, which is critical for preventing ice dams in Erie's winter climate." },
    { term: "Ridge Vent", definition: "A continuous vent along the roof peak that allows hot, moist air to escape the attic. Works with soffit vents to maintain proper attic ventilation and prevent ice dams." },
    { term: "Roof Pitch", definition: "The angle or steepness of a roof, expressed as a ratio (e.g., 6:12 means 6 inches of rise per 12 inches of run). Steeper pitches shed Erie's heavy snow more effectively." },
    { term: "Tear-Off", definition: "Complete removal of existing roofing material before installing new shingles. Erie code allows a maximum of two layers; a tear-off is required before adding a third." },
    { term: "Underlayment", definition: "A water-resistant barrier installed over roof decking and under shingles. Synthetic underlayment is increasingly preferred in Erie for its superior moisture protection." },
    { term: "Fascia", definition: "The vertical board running along the roof edge where gutters attach. Damaged fascia in Erie often results from ice buildup and can lead to gutter failure." },
    { term: "Drip Edge", definition: "A metal strip installed at roof edges that directs water away from the fascia and into the gutters. Required by current building code in Erie." },
    { term: "Attic Ventilation", definition: "The system of intake (soffit) and exhaust (ridge) vents that circulates air through the attic. Proper ventilation prevents ice dams in winter and reduces cooling costs in summer." },
    { term: "Valley", definition: "The V-shaped channel where two roof slopes meet. Valleys handle concentrated water flow and are prone to leaks if not properly flashed and shingled." },
    { term: "Wind Uplift", definition: "The force of wind lifting shingles from the roof surface. Erie's lakefront location and exposure to strong storms require shingles rated for high wind speeds." },
    { term: "Gutter Guards", definition: "Covers or screens installed over gutters to prevent debris accumulation. Particularly useful in Erie neighborhoods with heavy tree coverage." },
    { term: "Roof Decking", definition: "The plywood or OSB boards nailed to the rafters that form the base for your roofing material. Water-damaged decking must be replaced during a reroof." },
  ],

  landscaping: [
    { term: "Hardscape", definition: "The non-living elements of a landscape: patios, walkways, retaining walls, and driveways. In Erie, hardscaping must account for freeze-thaw cycles that can crack improperly installed surfaces." },
    { term: "Grading", definition: "The slope of the ground around your home. Proper grading directs water away from the foundation — critical in Erie where spring snowmelt and heavy rain cause basement flooding." },
    { term: "Aeration", definition: "The process of poking small holes in your lawn to allow air, water, and nutrients to reach grass roots. Best done in early fall in Erie for cool-season grass varieties." },
    { term: "Overseeding", definition: "Spreading grass seed over an existing lawn to fill thin spots and improve density. In Erie, the best window is September when soil temperatures are ideal for germination." },
    { term: "Perennial", definition: "A plant that returns year after year. Erie-hardy perennials (Zone 6a) include coneflowers, hostas, daylilies, and black-eyed Susans that survive our cold winters." },
    { term: "Retaining Wall", definition: "A structure built to hold back soil on a slope. In Erie, retaining walls must be engineered to handle frost heave and the pressure of saturated soil during spring thaw." },
    { term: "Mulch", definition: "Organic material (wood chips, bark) spread around plants to retain moisture, suppress weeds, and regulate soil temperature. Apply 2-3 inches in Erie gardens after the last spring frost." },
    { term: "French Drain", definition: "A gravel-filled trench with a perforated pipe that redirects groundwater away from problem areas. A common solution for Erie homes with persistent yard flooding." },
    { term: "Native Plants", definition: "Plants that naturally occur in the Lake Erie region. Native species like switchgrass, Joe-Pye weed, and serviceberry require less maintenance and support local wildlife." },
    { term: "Dethatching", definition: "Removing the layer of dead grass and organic debris (thatch) that accumulates between the soil and grass blades. Thick thatch prevents water and nutrients from reaching roots." },
    { term: "Cool-Season Grass", definition: "Grass varieties that thrive in Erie's climate, including Kentucky bluegrass, perennial ryegrass, and fescue. They grow most actively in spring and fall." },
    { term: "Frost Heave", definition: "The upward movement of soil and structures caused by freezing moisture expanding underground. Can damage patios, walkways, and retaining walls in Erie if base preparation is inadequate." },
    { term: "Irrigation System", definition: "An automated sprinkler system for your lawn and garden. In Erie, systems must be winterized (blown out) before the first freeze to prevent pipe damage." },
    { term: "Landscape Bed", definition: "A defined garden area separated from the lawn, typically edged and mulched. Bed design should consider Erie's sun exposure, drainage, and winter hardiness." },
    { term: "Topdressing", definition: "Applying a thin layer of compost or soil over your lawn to improve soil quality and levelness. Combined with aeration, it revitalizes compacted Erie lawns." },
  ],

  dental: [
    { term: "Crown", definition: "A tooth-shaped cap placed over a damaged tooth to restore its shape, size, and strength. Crowns typically last 10-15 years and can be made from porcelain, ceramic, or metal." },
    { term: "Root Canal", definition: "A procedure to remove infected pulp from inside a tooth, clean the canal, and seal it. Modern root canals are relatively painless and save teeth that would otherwise need extraction." },
    { term: "Veneer", definition: "A thin porcelain shell bonded to the front of a tooth to improve its appearance. Veneers address discoloration, chips, gaps, and minor misalignment." },
    { term: "Dental Implant", definition: "A titanium post surgically placed in the jawbone that serves as a permanent foundation for a replacement tooth. The gold standard for replacing missing teeth." },
    { term: "Periodontal Disease", definition: "Infection of the gums and bone supporting the teeth, commonly called gum disease. Early-stage gingivitis is reversible; advanced periodontitis can lead to tooth loss." },
    { term: "Fluoride Treatment", definition: "A preventive application of concentrated fluoride to strengthen tooth enamel and resist decay. Erie's municipal water is fluoridated, but professional treatments provide additional protection." },
    { term: "Orthodontics", definition: "The dental specialty focused on correcting misaligned teeth and jaws. Options include traditional braces, clear aligners (Invisalign), and lingual braces." },
    { term: "Dental Bridge", definition: "A fixed prosthetic that replaces one or more missing teeth by anchoring to adjacent natural teeth. An alternative to implants that typically costs less." },
    { term: "TMJ/TMD", definition: "Temporomandibular joint disorder — pain and dysfunction in the jaw joint and surrounding muscles. Symptoms include jaw clicking, headaches, and difficulty chewing." },
    { term: "Prophylaxis", definition: "A professional dental cleaning performed by a hygienist. Recommended every 6 months to remove plaque, tartar, and stains that brushing and flossing miss." },
    { term: "Dental Sealant", definition: "A thin protective coating applied to the chewing surfaces of back teeth to prevent cavities. Especially recommended for children and teens." },
    { term: "Extraction", definition: "The removal of a tooth. Simple extractions involve visible teeth; surgical extractions are required for impacted or broken teeth, including wisdom teeth." },
    { term: "Whitening", definition: "Professional teeth bleaching that removes stains and lightens tooth color. In-office treatments produce faster results than take-home trays or over-the-counter products." },
    { term: "Bite Adjustment (Occlusal)", definition: "Reshaping the biting surfaces of teeth to correct an uneven bite. An uneven bite can cause jaw pain, headaches, and premature wear on certain teeth." },
    { term: "Night Guard", definition: "A custom-fitted oral appliance worn during sleep to prevent teeth grinding (bruxism). Protects teeth, crowns, and fillings from grinding damage." },
    { term: "Composite Filling", definition: "A tooth-colored resin material used to fill cavities. Composites blend with natural tooth color, unlike silver amalgam fillings." },
  ],

  legal: [
    { term: "Retainer", definition: "An upfront fee paid to secure an attorney's services. Retainers are common for ongoing matters like family law cases and are drawn down as the attorney bills hours." },
    { term: "Contingency Fee", definition: "A payment arrangement where the attorney's fee is a percentage (typically 33-40%) of the settlement or judgment. Common in personal injury cases — you pay nothing if you lose." },
    { term: "Deposition", definition: "Sworn out-of-court testimony given by a witness or party, recorded by a court reporter. Depositions are a standard part of the discovery process in civil litigation." },
    { term: "Discovery", definition: "The pre-trial process where both sides exchange information, documents, and evidence. Includes depositions, interrogatories, and requests for documents." },
    { term: "Statute of Limitations", definition: "The legal deadline for filing a lawsuit. In Pennsylvania, personal injury claims must be filed within 2 years, and breach of contract within 4 years." },
    { term: "Power of Attorney", definition: "A legal document authorizing someone to act on your behalf in legal or financial matters. Pennsylvania recognizes both general and durable powers of attorney." },
    { term: "Mediation", definition: "A voluntary dispute resolution process where a neutral mediator helps parties reach agreement. Often faster and less expensive than going to trial in Erie County courts." },
    { term: "Estate Planning", definition: "The process of arranging for the management and distribution of your assets after death or incapacitation. Includes wills, trusts, powers of attorney, and healthcare directives." },
    { term: "Probate", definition: "The legal process of validating a will and distributing a deceased person's assets. In Pennsylvania, probate is handled by the Register of Wills in Erie County." },
    { term: "Living Trust", definition: "A legal entity that holds assets during your lifetime and transfers them to beneficiaries upon death, bypassing probate. Revocable trusts offer flexibility while alive." },
    { term: "Personal Injury", definition: "A legal claim for physical or psychological harm caused by another party's negligence. Common cases in Erie include car accidents, slip-and-fall injuries, and workplace incidents." },
    { term: "Child Custody", definition: "The legal arrangement determining where a child lives and who makes decisions about their care. Pennsylvania courts prioritize the child's best interest in all custody decisions." },
    { term: "DUI/DWI", definition: "Driving under the influence charges in Pennsylvania. PA has tiered penalties based on blood alcohol level: general impairment (0.08-0.099%), high rate (0.10-0.159%), and highest rate (0.16%+)." },
    { term: "Tort", definition: "A civil wrong that causes harm to another person, giving the injured party the right to sue for damages. Personal injury claims are the most common type of tort case." },
    { term: "Plea Bargain", definition: "A negotiated agreement between a defendant and prosecutor where the defendant pleads guilty to a lesser charge in exchange for a reduced sentence." },
    { term: "Arbitration", definition: "A private dispute resolution process where an arbitrator makes a binding decision. Faster than court proceedings but with limited appeal options." },
  ],

  cleaning: [
    { term: "Deep Clean", definition: "A thorough, intensive cleaning that goes beyond regular maintenance. Includes scrubbing grout, cleaning inside appliances, washing baseboards, and addressing areas normally skipped in routine cleaning." },
    { term: "Move-In/Move-Out Clean", definition: "A comprehensive cleaning performed when tenants change in a rental property. Covers every surface to return the unit to like-new condition and typically meets lease requirements." },
    { term: "Green Cleaning", definition: "Cleaning using environmentally friendly, non-toxic products. Important for homes with children, pets, or family members with chemical sensitivities." },
    { term: "Recurring Service", definition: "A scheduled cleaning at regular intervals — weekly, biweekly, or monthly. Recurring service typically costs less per visit than one-time cleanings." },
    { term: "Post-Construction Clean", definition: "Specialized cleaning after renovation or construction work. Removes drywall dust, paint splatters, adhesive residue, and construction debris." },
    { term: "Sanitizing vs. Disinfecting", definition: "Sanitizing reduces bacteria to a safe level; disinfecting kills nearly all bacteria and viruses. Disinfecting is recommended for bathrooms, kitchens, and during illness." },
    { term: "HEPA Filter", definition: "High-Efficiency Particulate Air filter that captures 99.97% of particles. HEPA-equipped vacuums are essential for allergy sufferers and thorough dust removal." },
    { term: "Bonded and Insured", definition: "A bonded cleaning company has purchased a surety bond to protect clients against theft or damage. Insurance covers accidental property damage during cleaning." },
    { term: "Spot Treatment", definition: "Targeted cleaning of specific stains or areas, particularly on carpets and upholstery. Different stains require different treatment methods for effective removal." },
    { term: "High-Touch Surfaces", definition: "Frequently touched areas like door handles, light switches, countertops, and faucets. Regularly disinfecting these surfaces reduces germ transmission." },
    { term: "Steam Cleaning", definition: "Using pressurized steam to clean and sanitize surfaces without chemicals. Effective for tile, grout, hardwood, and upholstery. Kills bacteria, dust mites, and allergens." },
    { term: "Window Cleaning (Interior/Exterior)", definition: "Professional cleaning of all window glass, sills, and tracks. Erie's lake proximity and seasonal pollen make regular window cleaning important for maintaining curb appeal." },
    { term: "Carpet Extraction", definition: "Hot water extraction (often called steam cleaning) that deep-cleans carpets by injecting hot water and cleaning solution, then extracting dirty water. Recommended annually for Erie homes." },
    { term: "Decluttering Service", definition: "Organizing and removing excess items to create a cleaner, more functional living space. Often performed before a deep clean or listing a home for sale." },
    { term: "Janitorial Service", definition: "Regular commercial cleaning including trash removal, restroom sanitizing, floor care, and surface wiping. Tailored to office buildings, retail spaces, and medical facilities." },
  ],

  "auto-repair": [
    { term: "Diagnostic Scan", definition: "Using an OBD-II scanner to read your vehicle's computer codes and identify problems. Modern vehicles have dozens of sensors, and a diagnostic scan pinpoints issues quickly." },
    { term: "Alignment", definition: "Adjusting the angles of your wheels to the manufacturer's specifications. Erie's potholes and rough winter roads frequently knock wheels out of alignment." },
    { term: "Brake Pads vs. Rotors", definition: "Brake pads are the friction material that presses against the rotor (disc) to slow your car. Pads wear faster and need replacement every 30,000-70,000 miles; rotors last longer but may need resurfacing or replacement." },
    { term: "Transmission Flush", definition: "A complete replacement of your transmission fluid, removing old fluid and contaminants. Recommended every 30,000-60,000 miles depending on driving conditions." },
    { term: "Catalytic Converter", definition: "An emissions control device that converts harmful exhaust gases into less harmful ones. Pennsylvania requires a functioning catalytic converter to pass the annual safety inspection." },
    { term: "Pennsylvania State Inspection", definition: "An annual vehicle safety inspection required by PA law. Covers brakes, tires, lights, steering, suspension, and exhaust. Erie County also requires an emissions inspection." },
    { term: "Timing Belt/Chain", definition: "A belt or chain that synchronizes the engine's camshaft and crankshaft. A broken timing belt can cause catastrophic engine damage. Replacement intervals vary by manufacturer." },
    { term: "Suspension", definition: "The system of springs, shocks, struts, and linkages connecting your vehicle to its wheels. Erie's road conditions accelerate suspension wear." },
    { term: "Coolant Flush", definition: "Draining old antifreeze/coolant and replacing it with fresh fluid. Critical in Erie — proper coolant protects your engine from freezing in winter and overheating in summer." },
    { term: "CV Joint/Boot", definition: "Constant velocity joints allow your drive axles to flex while transmitting power. The rubber boots that protect them crack over time; a torn boot leads to joint failure if not caught early." },
    { term: "Serpentine Belt", definition: "A single belt that drives multiple engine accessories (alternator, power steering, AC compressor). Belts degrade faster in Erie's temperature extremes and should be inspected regularly." },
    { term: "Wheel Bearing", definition: "Bearings that allow your wheels to spin freely on the axle. A humming or grinding noise that changes with speed often indicates a worn wheel bearing." },
    { term: "OBD-II", definition: "On-Board Diagnostics, the standardized vehicle computer system present in all cars since 1996. Mechanics connect to the OBD-II port to read trouble codes and diagnose issues." },
    { term: "Undercoating", definition: "A protective coating applied to the vehicle's undercarriage to prevent rust. Highly recommended in Erie due to heavy road salt use during winter months." },
    { term: "All-Season vs. Winter Tires", definition: "All-season tires handle moderate winter conditions; dedicated winter tires provide significantly better traction in snow and ice. Many Erie drivers switch to winter tires November through April." },
  ],

  "pest-control": [
    { term: "IPM (Integrated Pest Management)", definition: "A strategy combining prevention, monitoring, and targeted treatment to control pests with minimal chemical use. The preferred approach for environmentally conscious pest control." },
    { term: "Termite Inspection", definition: "A thorough examination of your home for signs of termite activity and damage. Recommended during real estate transactions and every 1-3 years for Erie homeowners." },
    { term: "Bait Station", definition: "A device placed around your home's perimeter containing slow-acting bait that pests carry back to their colony. Used for termites, ants, and rodents." },
    { term: "Perimeter Treatment", definition: "Applying pesticide around the exterior foundation of your home to create a barrier against crawling insects. Typically reapplied quarterly in Erie." },
    { term: "Rodent Exclusion", definition: "Sealing gaps, cracks, and entry points in your home's exterior to prevent mice and rats from entering. Mice can squeeze through openings as small as a dime." },
    { term: "Bed Bug Treatment", definition: "Specialized extermination of bed bugs using heat treatment, chemical application, or a combination. Heat treatment (raising room temperature to 120-140°F) is the most effective single-visit option." },
    { term: "Carpenter Ant", definition: "Large black ants that excavate wood to build nests (unlike termites, they don't eat wood). Common in Erie homes with moisture problems, especially around windows and in basements." },
    { term: "Subterranean Termite", definition: "Termites that live in soil and build mud tubes to reach wood in your home. The primary termite species found in the Erie region, causing billions in damage nationally each year." },
    { term: "Fumigation", definition: "A whole-structure treatment that fills the building with gaseous pesticide. Reserved for severe infestations (like drywood termites) and requires vacating the home for 24-72 hours." },
    { term: "German Cockroach", definition: "A small, fast-reproducing roach species commonly found in kitchens and bathrooms. The most common indoor cockroach in Erie and one of the hardest to eliminate." },
    { term: "Wildlife Removal", definition: "Humane trapping and relocation of animals like raccoons, squirrels, and bats from your home. In Pennsylvania, certain species are protected and require licensed removal." },
    { term: "Preventive Maintenance Plan", definition: "A scheduled pest control service (monthly, bimonthly, or quarterly) designed to prevent infestations before they start. Most cost-effective for long-term pest management." },
    { term: "Attic Insulation Removal", definition: "Removing contaminated insulation from attics after rodent or wildlife infestation. Droppings, urine, and nesting materials can create health hazards." },
    { term: "Stink Bug", definition: "Brown marmorated stink bugs that invade Erie homes in fall seeking warmth. Not harmful but extremely nuiseous when crushed. Prevention through sealing entry points is the best strategy." },
    { term: "Mosquito Treatment", definition: "Yard treatment targeting mosquito breeding areas and resting spots. Particularly important near Erie's waterways and in neighborhoods near Presque Isle Bay." },
  ],

  painting: [
    { term: "Primer", definition: "A preparatory coating applied before paint to improve adhesion, cover stains, and ensure uniform color. Erie homes with older lead paint, water stains, or new drywall all need primer." },
    { term: "Sheen (Finish)", definition: "The level of gloss in paint: flat, eggshell, satin, semi-gloss, and high-gloss. Higher sheen resists moisture better (ideal for Erie bathrooms and kitchens) but shows imperfections more." },
    { term: "VOC (Volatile Organic Compound)", definition: "Chemicals released as paint dries, contributing to indoor air pollution. Low-VOC and zero-VOC paints are safer for occupied homes, especially during Erie's closed-window winter months." },
    { term: "Lead Paint", definition: "Paint containing lead, found in homes built before 1978. Erie has many older homes with lead paint. Disturbing lead paint requires EPA-certified renovators following lead-safe work practices." },
    { term: "Caulking", definition: "Applying flexible sealant to gaps around windows, doors, trim, and siding joints. Essential prep work before exterior painting in Erie to prevent moisture infiltration." },
    { term: "Power Washing", definition: "High-pressure water cleaning of exterior surfaces before painting. Removes dirt, mildew, and loose paint to ensure proper adhesion of the new coat." },
    { term: "Skim Coat", definition: "A thin layer of joint compound applied over an entire wall surface to create a smooth, uniform finish. Necessary for Erie homes with damaged plaster or heavily patched drywall." },
    { term: "Cut-In", definition: "Painting precise lines with a brush along edges, corners, and trim before rolling the larger surfaces. Quality cut-in work separates professional painters from amateurs." },
    { term: "Two-Coat System", definition: "Applying one coat of primer and one coat of paint, or two coats of paint. Most professional Erie painters recommend two coats of finish paint for durability and uniform coverage." },
    { term: "Exterior Paint Season", definition: "The window of weather suitable for exterior painting. In Erie, this runs roughly May through October, when temperatures stay above 50°F and humidity is manageable." },
    { term: "Wallpaper Removal", definition: "Stripping existing wallpaper before painting. Older Erie homes often have multiple layers of wallpaper that must be removed, and walls may need skim coating afterward." },
    { term: "Color Consultation", definition: "Professional guidance on paint color selection. Many Erie painting contractors offer this service, helping you choose colors that complement your home's architecture and natural lighting." },
    { term: "Elastomeric Paint", definition: "A thick, flexible coating that bridges hairline cracks and repels water. An excellent option for Erie's masonry and stucco exteriors exposed to freeze-thaw cycles." },
    { term: "Mil Thickness", definition: "The measurement of paint film thickness (1 mil = 1/1000th of an inch). Professional painters ensure proper mil thickness for longevity — especially important for Erie's harsh weather exposure." },
    { term: "Cabinet Refinishing", definition: "Painting or staining kitchen cabinets to refresh their appearance without full replacement. A cost-effective kitchen update that typically costs 70-80% less than new cabinets." },
  ],

  "real-estate": [
    { term: "CMA (Comparative Market Analysis)", definition: "A report comparing your property to recently sold similar homes to determine fair market value. Erie agents use comparable sales data from the Greater Erie Board of Realtors MLS." },
    { term: "Closing Costs", definition: "Fees and expenses paid at the real estate closing beyond the purchase price. In Pennsylvania, buyers typically pay 2-5% of the purchase price in closing costs; sellers pay 6-10% including agent commissions." },
    { term: "Home Inspection", definition: "A thorough examination of a property's condition before purchase. In Erie, inspections commonly reveal issues related to older construction, basement moisture, and roof condition." },
    { term: "Appraisal", definition: "An independent assessment of a property's market value, required by mortgage lenders. If the appraisal comes in below the offer price, the buyer may need to renegotiate or cover the difference." },
    { term: "Escrow", definition: "A neutral third party that holds funds and documents during the transaction. In PA, escrow also refers to the account your lender uses to pay property taxes and homeowner's insurance." },
    { term: "Title Insurance", definition: "Insurance protecting against claims on property ownership. Pennsylvania buyers typically purchase both lender's and owner's title insurance at closing." },
    { term: "Pre-Approval", definition: "A lender's conditional commitment to loan you a specific amount based on your financial information. Stronger than pre-qualification and essential in competitive Erie market conditions." },
    { term: "Buyer's Agent vs. Listing Agent", definition: "A buyer's agent represents the purchaser's interests; a listing agent represents the seller. In Pennsylvania, agents must disclose who they represent at the start of the relationship." },
    { term: "MLS (Multiple Listing Service)", definition: "The database where real estate agents share property listings. The Greater Erie Board of Realtors operates the local MLS used by Erie-area agents." },
    { term: "Contingency", definition: "A condition that must be met for a real estate contract to proceed. Common contingencies include home inspection, financing, and appraisal contingencies." },
    { term: "Deed", definition: "The legal document transferring property ownership. In Pennsylvania, deeds are recorded with the Erie County Recorder of Deeds to establish public record of ownership." },
    { term: "HOA (Homeowners Association)", definition: "An organization in some developments that sets rules and collects fees for maintenance of shared spaces. Common in newer Erie-area subdivisions and condominium complexes." },
    { term: "Transfer Tax", definition: "A tax paid when property changes hands. Pennsylvania charges a 2% transfer tax (1% from buyer, 1% from seller) on real estate transactions, with some local additions." },
    { term: "Disclosure Statement", definition: "A document where the seller discloses known defects and issues with the property. Pennsylvania law requires sellers to complete a detailed property disclosure form." },
    { term: "Short Sale", definition: "A sale where the property sells for less than the outstanding mortgage balance, requiring lender approval. Less common in strong markets but may apply to distressed Erie properties." },
    { term: "Earnest Money", definition: "A deposit made by the buyer to demonstrate serious intent, typically 1-3% of the purchase price. Held in escrow and applied to the purchase at closing." },
  ],

  "garage-door": [
    { term: "Torsion Spring", definition: "A tightly wound spring mounted above the garage door opening that provides the lifting force. Torsion springs are under extreme tension and should only be replaced by professionals." },
    { term: "Extension Spring", definition: "Springs mounted on either side of the door track that stretch to provide lifting force. Less expensive than torsion springs but have a shorter lifespan and can be dangerous if not safely contained." },
    { term: "Garage Door Opener", definition: "The motorized unit that opens and closes the garage door. Common types include chain drive, belt drive (quieter), and screw drive. Smart openers add Wi-Fi connectivity and app control." },
    { term: "R-Value", definition: "A measurement of a garage door's insulation effectiveness. Higher R-values mean better insulation. For Erie's climate, an R-12 or higher door significantly reduces heat loss from attached garages." },
    { term: "Safety Sensors (Photo Eyes)", definition: "Infrared sensors mounted near the floor on each side of the garage door opening. They prevent the door from closing if anything breaks the beam, protecting children, pets, and objects." },
    { term: "Weatherstripping", definition: "Flexible seals installed along the bottom and sides of the garage door to block drafts, moisture, and pests. Erie's extreme cold makes quality weatherstripping essential for energy efficiency." },
    { term: "Track", definition: "The metal rails on either side of the garage door that guide the door as it opens and closes. Bent or misaligned tracks cause binding, uneven movement, and premature wear." },
    { term: "Roller", definition: "Small wheels that ride inside the track, allowing the door to move smoothly. Nylon rollers are quieter than steel and do not require lubrication." },
    { term: "Cable", definition: "Steel cables that connect the springs to the bottom brackets of the door. Frayed or broken cables cause the door to hang unevenly or drop suddenly." },
    { term: "Bottom Bracket", definition: "The hardware at the bottom corners of the garage door where the cables attach. These are under high tension and should only be adjusted by a professional." },
    { term: "Strut", definition: "A horizontal reinforcement bar mounted across the back of a garage door panel. Struts prevent the door from bowing or bending, especially on wide double doors common in Erie homes." },
    { term: "Sectional Door", definition: "The most common garage door type, made of horizontal panels (sections) connected by hinges. Sections can be replaced individually if damaged by Erie's hail or impacts." },
    { term: "Auto-Reverse", definition: "A safety feature that causes the garage door to reverse direction if it contacts an obstruction while closing. Federal law has required this feature on all openers since 1993." },
    { term: "Cycle Rating", definition: "The number of open/close cycles a garage door spring is rated to perform. Standard springs are rated for 10,000 cycles; high-cycle springs last 25,000 to 50,000 cycles." },
    { term: "Horsepower (Opener)", definition: "The power rating of a garage door opener motor. Standard single-car doors need 1/2 HP; heavy insulated double doors common in Erie may require 3/4 HP or higher." },
    { term: "Keypad Entry", definition: "A wireless keypad mounted outside the garage that allows entry via a PIN code. Useful for Erie families who need garage access without a remote or smartphone." },
  ],

  fencing: [
    { term: "Post", definition: "The vertical structural members set into the ground that support the fence. In Erie, posts must be set below the 32-inch frost line to prevent heaving during freeze-thaw cycles." },
    { term: "Rail", definition: "Horizontal members that connect posts and support pickets or panels. Most fences use two or three rails depending on height." },
    { term: "Picket", definition: "The individual vertical boards or slats that make up the visible face of a fence. Spacing between pickets determines the level of privacy." },
    { term: "Privacy Fence", definition: "A fence with no gaps between pickets, typically 6 feet tall. Popular in Erie residential neighborhoods for blocking wind, noise, and visibility from neighbors." },
    { term: "Frost Line", definition: "The depth to which the ground freezes in winter. In Erie County, the frost line is approximately 32 inches. Fence posts must be set below this depth to avoid frost heave." },
    { term: "Frost Heave", definition: "The upward movement of fence posts caused by freezing and expanding soil. A common problem in Erie that damages fences with insufficiently deep post holes." },
    { term: "Vinyl Fencing", definition: "Fence panels made from PVC plastic that resist rot, insects, and moisture. Vinyl requires no painting or staining and holds up well in Erie's wet climate, though extreme cold can make it brittle." },
    { term: "Pressure-Treated Wood", definition: "Lumber infused with chemical preservatives to resist rot, decay, and insects. The most affordable wood fence option for Erie homeowners, but requires regular staining or sealing." },
    { term: "Cedar", definition: "A naturally rot-resistant wood popular for fencing. Cedar weathers to an attractive gray if left untreated, or can be stained to maintain its original color. More expensive but longer-lasting than pressure-treated pine in Erie's wet climate." },
    { term: "Setback", definition: "The minimum distance a fence must be from a property line, sidewalk, or street. Erie and its surrounding townships have specific setback requirements that vary by zone." },
    { term: "Gate Hardware", definition: "Hinges, latches, and closers used on fence gates. Self-closing hinges and gravity latches are required on pool fences in Erie County for safety compliance." },
    { term: "Snow Fence", definition: "A lightweight fence installed to control snow drifting. Common along Erie County roads and rural properties to prevent lake effect snow from blocking driveways and walkways." },
    { term: "Chain Link", definition: "A fence made from woven steel wire in a diamond pattern. The most economical fencing option, commonly used for pet containment, sports fields, and commercial properties in Erie." },
    { term: "Ornamental Iron", definition: "Decorative metal fencing (typically aluminum or steel) that mimics traditional wrought iron. Aluminum versions are maintenance-free and do not rust in Erie's wet conditions." },
    { term: "Fence Cap", definition: "A decorative or protective cover placed on top of fence posts. Caps prevent water from entering the post end grain, extending the life of wood posts in Erie's rainy climate." },
    { term: "Shadow Box Fence", definition: "A semi-private fence design with pickets on alternating sides of the rails. Provides privacy from direct angles while allowing airflow — useful in Erie's humid summers." },
  ],

  flooring: [
    { term: "LVP (Luxury Vinyl Plank)", definition: "Waterproof vinyl flooring that mimics the look of hardwood. The top choice for Erie basements and moisture-prone areas because it handles temperature swings and water without damage." },
    { term: "Engineered Hardwood", definition: "Hardwood flooring made of a thin hardwood veneer over a plywood or HDF core. More dimensionally stable than solid hardwood, making it better suited to Erie's humidity fluctuations." },
    { term: "Solid Hardwood", definition: "Flooring milled from a single piece of wood. Beautiful and long-lasting but sensitive to moisture and humidity changes. Not recommended for Erie basements or below-grade installations." },
    { term: "Subfloor", definition: "The structural layer beneath your finished flooring, typically plywood or concrete. In older Erie homes, subfloors may need leveling, repair, or moisture barriers before new flooring is installed." },
    { term: "Underlayment", definition: "A thin layer of material installed between the subfloor and the finished floor. Provides cushioning, sound dampening, and moisture protection — essential in Erie homes over concrete slabs." },
    { term: "Moisture Barrier", definition: "A plastic or rubber membrane installed to prevent moisture from reaching the flooring. Critical for Erie basements and concrete slabs where moisture can wick up from the ground." },
    { term: "Floating Floor", definition: "A flooring installation method where planks click together and rest on the subfloor without being glued or nailed down. LVP, laminate, and some engineered hardwood are installed this way." },
    { term: "Glue-Down Installation", definition: "A flooring method where planks are adhered directly to the subfloor with adhesive. Provides the most stable installation and is common for LVP and engineered hardwood in Erie homes." },
    { term: "Acclimation", definition: "The process of letting flooring material adjust to a room's temperature and humidity before installation. In Erie, hardwood should acclimate for 3 to 7 days to prevent post-installation warping." },
    { term: "Refinishing", definition: "Sanding down the existing finish on hardwood floors and applying new stain and sealant. Erie's winter salt and grit make refinishing necessary every 7 to 10 years for high-traffic areas." },
    { term: "Wear Layer", definition: "The protective top surface of LVP or engineered hardwood that resists scratches and wear. Thicker wear layers (20+ mil for LVP) last longer in high-traffic Erie homes." },
    { term: "Grout", definition: "The cement-based filler between tiles. In Erie bathrooms and kitchens, grout should be sealed to prevent moisture absorption, staining, and mold growth." },
    { term: "Transition Strip", definition: "A trim piece that bridges the gap between two different flooring types or heights. Ensures a smooth, safe transition between rooms with different flooring materials." },
    { term: "SPC (Stone Polymer Composite)", definition: "A type of rigid core vinyl flooring that is extremely durable and waterproof. SPC handles temperature changes well, making it ideal for Erie homes with unheated areas." },
    { term: "Radiant Floor Heating", definition: "A heating system installed beneath the floor that warms rooms from the ground up. Compatible with tile and some LVP. An increasingly popular comfort upgrade for Erie's cold winters." },
    { term: "Quarter Round", definition: "Small trim molding installed where the floor meets the wall. Covers the expansion gap required for floating floors and provides a finished appearance." },
  ],

  "windows-doors": [
    { term: "U-Factor", definition: "A measurement of how well a window insulates. Lower U-factors mean better insulation. For Erie's climate, look for windows with a U-factor of 0.25 or lower." },
    { term: "Low-E Coating", definition: "A microscopically thin metallic coating on window glass that reflects heat. Low-E windows keep heat inside during Erie's winters and reduce solar heat gain in summer." },
    { term: "Double-Pane (Dual-Pane)", definition: "Windows with two layers of glass separated by an insulating gas-filled space. The minimum standard for energy efficiency in Erie's climate." },
    { term: "Triple-Pane", definition: "Windows with three layers of glass and two insulating spaces. Provide superior insulation and noise reduction. Recommended for north-facing walls and lake-exposed Erie homes." },
    { term: "Argon Gas Fill", definition: "An inert gas sealed between window panes that provides better insulation than air. Standard in modern energy-efficient windows suited to Erie's cold winters." },
    { term: "ENERGY STAR", definition: "The EPA certification for energy-efficient products. ENERGY STAR windows for Erie must meet Northern Climate Zone criteria with U-factor of 0.25 or lower." },
    { term: "Vinyl Frame", definition: "Window frames made from PVC plastic. Vinyl frames resist moisture, do not conduct cold, and never need painting. The most popular and cost-effective option in Erie." },
    { term: "Fiberglass Frame", definition: "Window frames made from pultruded fiberglass. Stronger and more dimensionally stable than vinyl, with excellent insulation properties. A premium option for Erie's extreme temperature swings." },
    { term: "Weatherstripping", definition: "Flexible seals around doors and windows that block drafts. Erie's temperature cycles wear out weatherstripping faster than milder climates. Check and replace annually." },
    { term: "Condensation", definition: "Water droplets forming on window surfaces. Interior condensation indicates high indoor humidity or poor window insulation. In Erie's winters, persistent condensation signals the need for window upgrades." },
    { term: "Storm Door", definition: "A secondary exterior door installed in front of the entry door. Provides extra insulation, weather protection, and security. Popular in Erie for extending the life of entry doors." },
    { term: "Egress Window", definition: "A basement window large enough to serve as an emergency exit. Required by building code in all habitable basement rooms. Erie County enforces minimum size requirements for new installations." },
    { term: "Double-Hung Window", definition: "A window with two sashes that both slide vertically. The most common window style in Erie homes, offering good ventilation and easy cleaning." },
    { term: "Solar Heat Gain Coefficient (SHGC)", definition: "A measurement of how much solar heat passes through a window. In Erie, a moderate SHGC (0.25 to 0.40) balances winter solar heating with summer cooling needs." },
    { term: "Sash", definition: "The movable part of a window that holds the glass. A broken sash mechanism causes windows to slide down or not stay open." },
    { term: "Flashing (Window)", definition: "Waterproof material installed around window openings to direct water away from the frame and wall. Proper flashing prevents the water damage common around windows in Erie's wet climate." },
  ],

  moving: [
    { term: "Bill of Lading", definition: "The contract between you and the moving company that lists services, costs, and delivery details. Review it carefully before signing — it is your primary legal protection." },
    { term: "Binding Estimate", definition: "A written quote guaranteeing the total cost of your move. The mover cannot charge more than the estimate even if the actual weight or time exceeds projections." },
    { term: "Non-Binding Estimate", definition: "An estimate based on the mover's assessment of your belongings. The final cost may differ from the estimate. For Erie moves, always push for a binding estimate." },
    { term: "Valuation Coverage", definition: "The level of liability a mover accepts for your belongings. Basic coverage ($0.60 per pound) is included; Full Value Protection covers the actual replacement value at additional cost." },
    { term: "Full Value Protection", definition: "The highest level of mover liability, covering the full replacement value or repair cost of any damaged or lost items. Recommended for long-distance moves from Erie." },
    { term: "Tariff", definition: "The official rate schedule filed by a moving company with the PA PUC or FMCSA. Tariffs set the maximum rates a licensed mover can charge." },
    { term: "Access Fee", definition: "An additional charge when movers cannot park their truck directly at your door. Common in downtown Erie and older neighborhoods with narrow streets, steep driveways, or no loading zones." },
    { term: "Stair Carry", definition: "An extra charge for carrying items up or down stairs. Many Erie apartments and multi-story homes require stair carries, typically charged per flight." },
    { term: "Shuttle Service", definition: "Using a smaller truck to transport items between a large moving truck and your home when the big truck cannot access your street. Common in Erie's tighter historic neighborhoods." },
    { term: "PA PUC Registration", definition: "Registration with the Pennsylvania Public Utility Commission, required for all moving companies operating within Pennsylvania. Verify a mover's PUC status before hiring." },
    { term: "USDOT Number", definition: "A federal identification number required for moving companies that cross state lines. Check a mover's USDOT number on the FMCSA website for complaint history and insurance status." },
    { term: "Inventory List", definition: "A detailed list of every item loaded onto the moving truck, noting condition. Review and sign the inventory at pickup and delivery. Discrepancies form the basis for damage claims." },
    { term: "Tare Weight", definition: "The weight of the empty moving truck. The cost of a long-distance move is calculated from the difference between the truck's loaded weight and its tare weight." },
    { term: "Peak Season", definition: "The busiest period for movers, typically May through September. Erie moves during peak season cost more and require earlier booking. Moving in fall or winter saves money." },
    { term: "Packing Materials", definition: "Boxes, tape, bubble wrap, packing paper, and specialty containers (dish packs, wardrobe boxes) used to protect belongings. Most Erie movers offer packing services at additional cost." },
    { term: "Storage-in-Transit", definition: "Temporary storage of your belongings between pickup and delivery. Useful when Erie closing dates do not align or the new home is not ready for move-in." },
  ],

  "tree-service": [
    { term: "Arborist", definition: "A certified tree care professional trained in planting, maintenance, diagnosis, and removal of trees. ISA (International Society of Arboriculture) certification is the industry standard." },
    { term: "Crown", definition: "The upper portion of a tree including all branches and foliage. Crown health indicates overall tree vitality." },
    { term: "Crown Thinning", definition: "Selective removal of branches within the tree crown to improve light penetration and airflow. Reduces wind resistance during Erie's lake-effect storms." },
    { term: "Crown Raising", definition: "Removing lower branches to increase clearance beneath the tree. Common along Erie sidewalks, driveways, and over structures." },
    { term: "Deadwooding", definition: "Removing dead, dying, or diseased branches from a tree. Essential for safety in Erie where ice-laden dead branches fall during winter storms." },
    { term: "Stump Grinding", definition: "Using a machine to grind a tree stump below ground level. The remaining wood chips decompose over time. More affordable than full stump removal." },
    { term: "Cabling and Bracing", definition: "Installing steel cables or rods in a tree to support weak or split branches. Preserves valuable trees that might otherwise need removal due to structural weakness." },
    { term: "Hazard Tree", definition: "A tree with structural defects that make it likely to fail and strike a target (house, car, walkway). Erie's ice storms reveal hazard trees that appear healthy in summer." },
    { term: "Canopy", definition: "The outermost layer of a tree's branches and leaves. Erie's mature tree canopy in neighborhoods like Glenwood and Academy provides shade but requires regular maintenance." },
    { term: "Root Zone", definition: "The underground area where a tree's roots grow, typically extending 1 to 3 times the width of the canopy. Damage to the root zone (compaction, grade changes) can kill a tree." },
    { term: "Girdling Root", definition: "A root that wraps around the base of the trunk, restricting growth and nutrient flow. Common in improperly planted trees and can lead to tree failure." },
    { term: "Topping", definition: "The harmful practice of cutting large branches back to stubs. Topping weakens trees and creates hazardous regrowth. A reputable Erie arborist will never recommend topping." },
    { term: "Lot Clearing", definition: "Removing all or most trees and brush from a piece of land for construction or development. Requires heavy equipment and typically generates large volumes of debris." },
    { term: "Emergency Tree Service", definition: "After-hours response for fallen trees, hanging branches, or trees threatening structures and power lines. Demand peaks during Erie's winter ice storms and summer thunderstorms." },
    { term: "Hardiness Zone", definition: "The USDA plant hardiness classification for a region. Erie is Zone 6a (-10 to -5 degrees F minimum), which determines which tree species thrive here." },
    { term: "ISA Certification", definition: "Credentials from the International Society of Arboriculture verifying a tree care professional's knowledge and competency. The gold standard for arborists in Erie County." },
  ],

  "appliance-repair": [
    { term: "Compressor", definition: "The motor-driven pump in a refrigerator or freezer that circulates refrigerant. Compressor failure is the most expensive common refrigerator repair, often costing $300 to $600." },
    { term: "Thermostat (Appliance)", definition: "The temperature control device in ovens, refrigerators, and other appliances. A faulty thermostat causes inaccurate temperatures — your oven may run hot or your fridge too warm." },
    { term: "Heating Element", definition: "The component that generates heat in ovens, dryers, and dishwashers. Heating elements burn out over time and are relatively affordable to replace ($50 to $200)." },
    { term: "Control Board", definition: "The electronic circuit board that manages an appliance's functions. Modern smart appliances rely heavily on control boards, and replacement can be expensive ($200 to $500)." },
    { term: "Lint Trap/Filter", definition: "The screen in your dryer that catches lint from clothing. Clean after every load. A clogged lint system is a fire hazard and reduces drying efficiency." },
    { term: "Dryer Vent", definition: "The ductwork that carries hot, moist air from your dryer to the outside. Clogged dryer vents cause fires, reduce efficiency, and are a common maintenance item in Erie homes." },
    { term: "Gasket (Door Seal)", definition: "The flexible rubber seal around refrigerator, oven, and dishwasher doors. A worn gasket lets air leak in or out, reducing efficiency. Test by closing the door on a piece of paper." },
    { term: "Water Inlet Valve", definition: "The valve that controls water flow into washing machines, dishwashers, and ice makers. Mineral buildup from Erie's hard water can clog inlet valves over time." },
    { term: "Drain Pump", definition: "The pump that removes water from washing machines and dishwashers. Blockages from coins, debris, or mineral buildup cause standing water and error codes." },
    { term: "Evaporator Fan", definition: "The fan inside a refrigerator or freezer that circulates cold air. A noisy or failed evaporator fan causes uneven cooling and warm spots." },
    { term: "Self-Cleaning Oven", definition: "An oven feature that heats to extremely high temperatures (800-900 degrees F) to burn off food residue. Caution: the cleaning cycle can trigger failures in older ovens." },
    { term: "Condenser Coils", definition: "Coils on the back or bottom of your refrigerator that release heat. Dusty coils reduce efficiency and increase energy costs. Clean every 6 to 12 months." },
    { term: "Hard Water Scale", definition: "Mineral deposits (calcium and magnesium) that build up inside appliances using water. Erie's moderately hard water causes scale in dishwashers, washing machines, and water heaters." },
    { term: "Factory-Authorized Service", definition: "Repair service certified by the appliance manufacturer. Factory-authorized technicians have access to OEM parts and manufacturer-specific training." },
    { term: "Diagnostic Fee", definition: "The charge for a technician to diagnose the problem. Most Erie appliance repair companies charge $75 to $125, often applied as a credit toward the repair cost." },
    { term: "OEM Parts", definition: "Original Equipment Manufacturer parts — components made by or for the appliance manufacturer. OEM parts ensure proper fit and function, though they may cost more than generic alternatives." },
  ],

  foundation: [
    { term: "Hydrostatic Pressure", definition: "The force of water in saturated soil pressing against foundation walls. Erie's high water table and heavy precipitation create significant hydrostatic pressure, especially during spring snowmelt." },
    { term: "Efflorescence", definition: "White crystalline deposits on foundation walls caused by water carrying dissolved minerals through the concrete. A visible sign that moisture is penetrating your foundation." },
    { term: "Epoxy Injection", definition: "A repair method that fills foundation cracks with structural epoxy, restoring wall strength. Best for structural cracks in poured concrete foundations." },
    { term: "Polyurethane Injection", definition: "A flexible foam injection that fills and seals foundation cracks. Unlike rigid epoxy, polyurethane expands and can accommodate minor wall movement from Erie's freeze-thaw cycles." },
    { term: "Interior Drain System", definition: "A perforated pipe installed along the interior perimeter of the basement floor that channels water to a sump pump. The most common waterproofing solution for Erie basements." },
    { term: "Exterior Waterproofing", definition: "Excavating around the foundation and applying waterproof membranes and drainage to the exterior walls. The most thorough but also most expensive waterproofing approach." },
    { term: "Sump Pump", definition: "A pump installed in the lowest point of the basement that removes accumulated water. Essential for Erie homes with high water tables. Battery backups are strongly recommended." },
    { term: "Carbon Fiber Straps", definition: "High-strength carbon fiber strips bonded to bowed or cracking foundation walls to prevent further movement. A less invasive and more affordable alternative to wall anchors." },
    { term: "Wall Anchors", definition: "Steel plates connected by rods that extend from the foundation wall to an anchor buried in the yard. Used to stabilize and gradually straighten bowed basement walls." },
    { term: "Helical Pier", definition: "A steel shaft with helical plates screwed into stable soil beneath the foundation to support and lift a settling structure. Used when Erie's clay soils cannot support the building weight." },
    { term: "Crawl Space Encapsulation", definition: "Sealing a crawl space with a heavy-duty vapor barrier on floors and walls, plus a dehumidifier. Prevents moisture problems, mold, and pest issues in Erie homes with crawl spaces." },
    { term: "French Drain", definition: "A gravel-filled trench with a perforated pipe that redirects groundwater away from the foundation. Can be installed interior or exterior. A key component of Erie basement waterproofing." },
    { term: "Settling", definition: "The downward movement of a foundation when the underlying soil cannot support the weight. Signs include cracked walls, sticking doors, and uneven floors. Common in Erie's clay soils." },
    { term: "Bowed Wall", definition: "A basement wall that has curved inward due to lateral soil pressure. Erie's freeze-thaw cycles and saturated clay soils are primary causes. Requires stabilization before the bow worsens." },
    { term: "Vapor Barrier", definition: "A plastic sheet or membrane that prevents moisture from passing through floors and walls. Used in basements and crawl spaces to control humidity and prevent mold in Erie's wet climate." },
    { term: "Grading", definition: "The slope of the ground around your foundation. Proper grading (1 inch of drop per foot for at least 6 feet) directs water away from the foundation. The first line of defense against Erie basement leaks." },
  ],

  "home-security": [
    { term: "Monitored System", definition: "A security system connected to a professional monitoring center that contacts you and dispatches emergency services when an alarm triggers. Available 24/7 regardless of your location." },
    { term: "Self-Monitored System", definition: "A security system that sends alerts directly to your smartphone. You are responsible for contacting authorities. Less expensive monthly fees but requires you to respond personally." },
    { term: "Control Panel", definition: "The central hub of your security system that communicates with all sensors, cameras, and the monitoring center. Modern panels include touchscreens and voice control." },
    { term: "Motion Sensor", definition: "A device that detects movement within a defined area. PIR (passive infrared) sensors are most common. Pet-immune sensors ignore animals up to a set weight to reduce false alarms." },
    { term: "Door/Window Sensor", definition: "A two-piece magnetic sensor that triggers when a door or window is opened. The most basic and essential component of any home security system." },
    { term: "Smart Lock", definition: "An electronic lock that can be controlled via smartphone, keypad, or voice assistant. Allows remote locking/unlocking and guest access codes without physical keys." },
    { term: "Video Doorbell", definition: "A doorbell with a built-in camera that shows and records who is at your door. Sends alerts to your phone and allows two-way communication with visitors." },
    { term: "Cellular Backup", definition: "A cellular connection that keeps your security system communicating with the monitoring center during power or internet outages. Essential for Erie where storms disrupt utilities." },
    { term: "Battery Backup", definition: "An internal battery that keeps your security system running during power outages. Quality systems provide 4 to 24 hours of backup power." },
    { term: "False Alarm", definition: "A security alarm triggered by a non-emergency cause (pets, drafts, low batteries). Excessive false alarms can result in fines from Erie police and reduce response priority." },
    { term: "Night Vision (IR)", definition: "Infrared technology that allows security cameras to capture clear footage in complete darkness. Essential for Erie's short winter days and long nights." },
    { term: "NVR (Network Video Recorder)", definition: "A device that records and stores footage from IP security cameras. Offers higher resolution and more flexible storage than older DVR systems." },
    { term: "Geofencing", definition: "Using your smartphone's GPS to automatically arm or disarm your security system as you leave or arrive home." },
    { term: "Glass Break Sensor", definition: "A sensor that detects the specific sound frequency of breaking glass. Covers multiple windows in a room without requiring individual sensors on each window." },
    { term: "Z-Wave / Zigbee", definition: "Wireless protocols used by smart home security devices to communicate. These low-power signals allow sensors, locks, and lights to work together as a unified system." },
    { term: "UL Listed", definition: "A certification from Underwriters Laboratories indicating a security product or monitoring center meets safety and performance standards. Look for UL-listed equipment and monitoring." },
  ],

  concrete: [
    { term: "Air-Entrained Concrete", definition: "Concrete mixed with tiny air bubbles that absorb the expansion of freezing water. Essential for all exterior concrete in Erie to prevent cracking and spalling from freeze-thaw cycles." },
    { term: "PSI (Pounds per Square Inch)", definition: "The compressive strength rating of concrete. Residential driveways in Erie should use at least 4,000 PSI concrete; 4,500 PSI is recommended for extra durability." },
    { term: "Control Joint", definition: "A groove cut into fresh concrete that creates a predetermined weak point where cracking will occur in a straight line. Proper joint spacing (every 8 to 12 feet) is critical in Erie's climate." },
    { term: "Rebar", definition: "Steel reinforcement bars placed inside concrete to add tensile strength. Rebar helps Erie driveways and slabs resist cracking from heavy loads and freeze-thaw movement." },
    { term: "Wire Mesh", definition: "A grid of welded steel wire placed in concrete to help control cracking. Less effective than rebar but more economical for smaller Erie concrete projects like sidewalks." },
    { term: "Spalling", definition: "The flaking or peeling of the concrete surface caused by freeze-thaw damage and deicing chemicals. Extremely common on Erie driveways and sidewalks exposed to road salt." },
    { term: "Stamped Concrete", definition: "Concrete that is patterned and colored to resemble brick, slate, stone, or wood. A decorative option for Erie patios and walkways that costs more but adds visual appeal." },
    { term: "Concrete Sealer", definition: "A protective coating applied to concrete surfaces. Penetrating sealers protect against moisture, salt, and freeze-thaw damage. The single most important maintenance step for Erie concrete." },
    { term: "Curing", definition: "The chemical process by which concrete hardens and gains strength over time. Concrete reaches most of its strength in 28 days. Proper curing is critical — too fast or too cold weakens the result." },
    { term: "Mudjacking", definition: "A repair technique that lifts sunken concrete by pumping a slurry mixture beneath the slab. An alternative to replacement for settled sidewalks and driveways in Erie." },
    { term: "Polyfoam Leveling", definition: "A modern alternative to mudjacking that uses expanding polyurethane foam to lift sunken concrete. Lighter weight and more precise than mudjacking, with faster curing time." },
    { term: "Expansion Joint", definition: "A flexible material placed between concrete slabs or where concrete meets a structure. Allows for natural expansion and contraction during Erie's extreme temperature swings." },
    { term: "Finishing", definition: "The process of smoothing and texturing the concrete surface after it is poured. Options include broom finish (for traction), smooth trowel, exposed aggregate, and stamped patterns." },
    { term: "Ready-Mix Concrete", definition: "Concrete mixed at a batching plant and delivered by truck. Ensures consistent quality and proper air entrainment — important for exterior work in Erie's freeze-thaw climate." },
    { term: "Frost Heave", definition: "The upward movement of concrete slabs caused by freezing moisture in the soil beneath. Common in Erie, especially where drainage is poor. Proper base preparation and drainage prevent it." },
    { term: "Base Preparation", definition: "The gravel and compacted fill beneath a concrete slab that provides drainage and stability. In Erie, a minimum 4-inch compacted gravel base is standard for driveways and patios." },
  ],

  septic: [
    { term: "Septic Tank", definition: "An underground container where household wastewater collects, and solids settle out. Bacteria break down organic matter. Tanks are typically 1,000 to 1,500 gallons for Erie homes." },
    { term: "Drain Field (Leach Field)", definition: "A network of perforated pipes buried in gravel trenches where liquid effluent from the septic tank is distributed into the soil for natural filtration." },
    { term: "Effluent", definition: "The liquid wastewater that flows from the septic tank to the drain field after solids have settled. Effluent still contains contaminants that are filtered by soil in the drain field." },
    { term: "Scum Layer", definition: "The floating layer of grease, oils, and lightweight solids that forms at the top of a septic tank. The outlet baffle prevents scum from entering the drain field." },
    { term: "Sludge Layer", definition: "The layer of settled solids at the bottom of a septic tank. Pumping removes this sludge before it accumulates to the point of entering and clogging the drain field." },
    { term: "Baffle", definition: "A wall or partition inside the septic tank that directs flow and prevents solids and scum from leaving the tank. Damaged baffles are a common cause of drain field failure." },
    { term: "Perc Test (Percolation Test)", definition: "A soil test that measures how quickly water drains through the soil. Required before installing a new septic system in Erie County to ensure the soil can handle effluent." },
    { term: "Sewage Enforcement Officer (SEO)", definition: "A PA-certified official who inspects and permits septic systems. Erie County SEOs oversee all septic installations, repairs, and real estate transaction inspections." },
    { term: "Pump-Out", definition: "The process of removing accumulated solids (sludge and scum) from a septic tank using a vacuum truck. Erie County recommends pumping every 3 to 5 years." },
    { term: "Distribution Box", definition: "A small concrete or plastic box that evenly distributes effluent from the septic tank to multiple drain field lines. A failed distribution box causes uneven loading and field failure." },
    { term: "Effluent Filter", definition: "A filter installed at the septic tank outlet that prevents solids from reaching the drain field. Inexpensive insurance against drain field failure. Should be cleaned at each pumping." },
    { term: "Aerobic Treatment Unit", definition: "An advanced septic system that uses oxygen to accelerate waste breakdown. Produces cleaner effluent than conventional systems. Sometimes required in Erie County for challenging soil conditions." },
    { term: "Raised Bed System", definition: "A drain field built above the natural ground level using imported fill material. Used in Erie County areas where the water table is too high for conventional in-ground fields." },
    { term: "Holding Tank", definition: "A sealed tank with no drain field that stores all wastewater until pumped. A last-resort option in Erie County areas where soil conditions cannot support any treatment system." },
    { term: "Grease Trap", definition: "A plumbing device that intercepts fats, oils, and grease before they enter the septic system. Required for commercial kitchens and recommended for homes with heavy cooking." },
    { term: "Soil Profile", definition: "The layers and characteristics of soil at a building site. Erie County's clay-heavy soils and high water table significantly affect septic system design and drain field performance." },
  ],

  chimney: [
    { term: "Flue", definition: "The interior passage of a chimney through which smoke and combustion gases travel. A damaged flue liner is a serious fire and carbon monoxide hazard." },
    { term: "Flue Liner", definition: "A protective lining inside the chimney flue. Clay tile liners are common in older Erie homes; stainless steel liners are the modern replacement when the original liner fails." },
    { term: "Creosote", definition: "A flammable, tar-like residue that builds up inside chimneys from burning wood. Creosote is the leading cause of chimney fires. Regular cleaning removes it before it reaches dangerous levels." },
    { term: "Chimney Crown", definition: "The concrete or mortar top that seals the chimney around the flue. Erie's freeze-thaw cycles crack crowns, allowing water into the chimney structure. Regular inspection and repair are essential." },
    { term: "Chimney Cap", definition: "A metal cover installed over the flue opening that keeps rain, snow, animals, and debris out while allowing smoke to exit. Missing caps are a common cause of chimney water damage in Erie." },
    { term: "Tuckpointing", definition: "Removing deteriorated mortar from between bricks and replacing it with fresh mortar. Erie's freeze-thaw cycles erode mortar joints faster than milder climates, making tuckpointing a regular need." },
    { term: "Damper", definition: "A movable metal plate inside the chimney that controls airflow. Open it before lighting a fire, close it when the fireplace is not in use to prevent heat loss during Erie winters." },
    { term: "Firebox", definition: "The interior chamber of a fireplace where the fire burns. The firebox is lined with fire brick that can crack over time and needs periodic inspection." },
    { term: "Spark Arrestor", definition: "A mesh screen at the top of the chimney that prevents sparks and embers from escaping onto the roof. Required by many local fire codes." },
    { term: "Chimney Sweep", definition: "A professional who cleans and inspects chimneys. CSIA (Chimney Safety Institute of America) certification is the industry standard. Annual sweeping is recommended for Erie homes that burn wood." },
    { term: "Level 1 Inspection", definition: "A basic chimney inspection performed during routine cleaning. The sweep examines readily accessible portions for damage, blockages, and creosote buildup." },
    { term: "Level 2 Inspection", definition: "A more thorough inspection using a video camera to examine the flue interior. Required when selling a home, changing fuel types, or after a chimney fire or weather event." },
    { term: "Efflorescence (Chimney)", definition: "White mineral deposits on chimney bricks caused by moisture passing through the masonry. Indicates water infiltration that can cause serious structural damage during Erie's freeze-thaw cycles." },
    { term: "Chimney Flashing", definition: "Metal strips (typically aluminum or lead) installed where the chimney meets the roof to prevent water infiltration. Flashing failure is one of the most common causes of roof leaks around chimneys." },
    { term: "Waterproofing (Chimney)", definition: "Applying a breathable sealant to chimney masonry that repels water while allowing moisture vapor to escape. Extends chimney life significantly in Erie's wet, freeze-thaw climate." },
    { term: "Draft", definition: "The upward airflow in a chimney created by the difference between indoor and outdoor air temperatures. Proper draft ensures smoke exits the home. Erie's cold outdoor air generally produces strong draft." },
  ],
};

export function getGlossaryTerms(slug: string): GlossaryTerm[] {
  return GLOSSARY_DATA[slug] ?? [];
}
