export interface LocalNiche {
  slug: string;
  label: string;
  icon: string; // emoji
  description: string;
  searchTerms: string[];
  avgProjectValue: string;
  monthlyFee: number;
  exclusiveAvailable: boolean;
  subscriberSlug: string | null; // null = no exclusive subscriber yet
  subscriberName: string | null;
}

export const niches: LocalNiche[] = [
  { slug: "plumbing", label: "Plumbing", icon: "\uD83D\uDD27", description: "Emergency repairs, installations, drain cleaning, and water heater services", searchTerms: ["plumber", "plumbing", "drain", "water heater", "pipe repair"], avgProjectValue: "$150-$5,000", monthlyFee: 750, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "hvac", label: "HVAC", icon: "\u2744\uFE0F", description: "Heating, cooling, ventilation, and air quality services", searchTerms: ["hvac", "heating", "cooling", "air conditioning", "furnace"], avgProjectValue: "$200-$10,000", monthlyFee: 750, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "electrical", label: "Electrical", icon: "\u26A1", description: "Wiring, panel upgrades, lighting, and electrical repairs", searchTerms: ["electrician", "electrical", "wiring", "panel upgrade"], avgProjectValue: "$150-$8,000", monthlyFee: 700, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "roofing", label: "Roofing", icon: "\uD83C\uDFE0", description: "Roof repair, replacement, gutters, and storm damage restoration", searchTerms: ["roofer", "roofing", "roof repair", "gutters"], avgProjectValue: "$500-$15,000", monthlyFee: 1000, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "landscaping", label: "Landscaping", icon: "\uD83C\uDF3F", description: "Lawn care, landscape design, hardscaping, and seasonal maintenance", searchTerms: ["landscaper", "landscaping", "lawn care", "hardscape"], avgProjectValue: "$100-$5,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "dental", label: "Dental", icon: "\uD83E\uDDB7", description: "General dentistry, cosmetic procedures, orthodontics, and oral surgery", searchTerms: ["dentist", "dental", "orthodontist", "oral surgeon"], avgProjectValue: "$200-$5,000", monthlyFee: 1200, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "legal", label: "Legal", icon: "\u2696\uFE0F", description: "Personal injury, family law, criminal defense, estate planning, and immigration", searchTerms: ["lawyer", "attorney", "law firm", "legal"], avgProjectValue: "$500-$25,000", monthlyFee: 1500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "cleaning", label: "Cleaning", icon: "\u2728", description: "House cleaning, commercial cleaning, and deep cleaning services", searchTerms: ["cleaning", "maid service", "house cleaning", "janitorial"], avgProjectValue: "$100-$500", monthlyFee: 300, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "auto-repair", label: "Auto Repair", icon: "\uD83D\uDE97", description: "Mechanical repair, body work, oil changes, and diagnostics", searchTerms: ["auto repair", "mechanic", "car repair", "body shop"], avgProjectValue: "$100-$5,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "pest-control", label: "Pest Control", icon: "\uD83D\uDC1B", description: "Insect control, rodent removal, termite treatment, and prevention", searchTerms: ["pest control", "exterminator", "termite", "rodent"], avgProjectValue: "$100-$2,000", monthlyFee: 350, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "painting", label: "Painting", icon: "\uD83C\uDFA8", description: "Interior and exterior painting, staining, and wallpaper", searchTerms: ["painter", "painting", "house painting", "commercial painting"], avgProjectValue: "$500-$10,000", monthlyFee: 550, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "real-estate", label: "Real Estate", icon: "\uD83C\uDFE1", description: "Buyer and seller representation, property management, and appraisals", searchTerms: ["realtor", "real estate", "property", "homes for sale"], avgProjectValue: "$3,000-$15,000", monthlyFee: 1300, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  // ── New high-demand niches ────────────────────────────────────────
  { slug: "garage-door", label: "Garage Door", icon: "\uD83D\uDEAA", description: "Garage door repair, replacement, opener installation, and spring repair", searchTerms: ["garage door", "garage door repair", "garage door opener", "spring repair", "garage door installation"], avgProjectValue: "$150-$2,000", monthlyFee: 450, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "fencing", label: "Fencing", icon: "\uD83C\uDFD7\uFE0F", description: "Wood, vinyl, chain link, and iron fence installation and repair", searchTerms: ["fence", "fencing", "fence installation", "fence repair", "vinyl fence", "chain link fence"], avgProjectValue: "$1,500-$8,000", monthlyFee: 600, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "flooring", label: "Flooring", icon: "\uD83E\uDEB5", description: "Hardwood, tile, carpet, vinyl, and laminate flooring installation", searchTerms: ["flooring", "hardwood floors", "tile installation", "carpet", "laminate", "vinyl plank"], avgProjectValue: "$2,000-$12,000", monthlyFee: 1000, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "windows-doors", label: "Windows & Doors", icon: "\uD83E\uDE9F", description: "Window replacement, door installation, storm windows, and energy upgrades", searchTerms: ["window replacement", "door installation", "storm windows", "energy efficient windows", "entry door"], avgProjectValue: "$3,000-$15,000", monthlyFee: 1200, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "moving", label: "Moving", icon: "\uD83D\uDCE6", description: "Local and long-distance moving, packing, and storage services", searchTerms: ["moving company", "movers", "local moving", "long distance moving", "packing services", "storage"], avgProjectValue: "$500-$5,000", monthlyFee: 350, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "tree-service", label: "Tree Service", icon: "\uD83C\uDF33", description: "Tree removal, trimming, stump grinding, and emergency storm damage", searchTerms: ["tree service", "tree removal", "tree trimming", "stump grinding", "arborist", "storm damage"], avgProjectValue: "$300-$5,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "appliance-repair", label: "Appliance Repair", icon: "\uD83D\uDD0C", description: "Refrigerator, washer, dryer, dishwasher, and oven repair", searchTerms: ["appliance repair", "refrigerator repair", "washer repair", "dryer repair", "dishwasher repair", "oven repair"], avgProjectValue: "$100-$800", monthlyFee: 350, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "foundation", label: "Foundation & Waterproofing", icon: "\uD83E\uDDF1", description: "Foundation repair, basement waterproofing, crack sealing, and drainage", searchTerms: ["foundation repair", "basement waterproofing", "crack sealing", "drainage", "sump pump", "crawl space"], avgProjectValue: "$2,000-$15,000", monthlyFee: 1300, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "home-security", label: "Home Security", icon: "\uD83D\uDD10", description: "Security system installation, cameras, smart locks, and monitoring", searchTerms: ["home security", "security cameras", "alarm system", "smart locks", "security monitoring", "surveillance"], avgProjectValue: "$500-$5,000", monthlyFee: 800, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "concrete", label: "Concrete & Masonry", icon: "\uD83C\uDFD7\uFE0F", description: "Driveways, patios, sidewalks, retaining walls, and brick repair", searchTerms: ["concrete", "masonry", "driveway", "patio", "sidewalk", "retaining wall", "brick repair"], avgProjectValue: "$1,500-$12,000", monthlyFee: 700, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "septic", label: "Septic & Sewer", icon: "\uD83D\uDD27", description: "Septic pumping, sewer line repair, drain field maintenance", searchTerms: ["septic", "sewer", "septic pumping", "sewer line", "drain field", "septic tank", "sewer repair"], avgProjectValue: "$300-$10,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "chimney", label: "Chimney & Fireplace", icon: "\uD83D\uDD25", description: "Chimney cleaning, inspection, repair, liner installation, and fireplace service", searchTerms: ["chimney", "fireplace", "chimney cleaning", "chimney repair", "chimney liner", "chimney inspection"], avgProjectValue: "$150-$5,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  // ── Additional niches (batch 2) ──────────────────────────────────
  { slug: "pool-spa", label: "Pool & Spa Services", icon: "\uD83C\uDFCA", description: "Pool maintenance, repair, and installation", searchTerms: ["pool service", "spa repair", "pool maintenance", "hot tub", "pool installation", "pool cleaning"], avgProjectValue: "$200-$8,000", monthlyFee: 900, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "locksmith", label: "Locksmith Services", icon: "\uD83D\uDD11", description: "Emergency lockout, lock installation, key cutting", searchTerms: ["locksmith", "lockout", "lock installation", "key cutting", "lock repair", "rekey"], avgProjectValue: "$75-$500", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "towing", label: "Towing & Roadside Assistance", icon: "\uD83D\uDE9C", description: "Emergency towing, roadside help, vehicle recovery", searchTerms: ["towing", "tow truck", "roadside assistance", "vehicle recovery", "flatbed tow", "jump start"], avgProjectValue: "$75-$500", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "carpet-cleaning", label: "Carpet Cleaning", icon: "\uD83E\uDDF9", description: "Deep cleaning, stain removal, upholstery cleaning", searchTerms: ["carpet cleaning", "rug cleaning", "upholstery cleaning", "stain removal", "steam cleaning", "carpet cleaner"], avgProjectValue: "$100-$600", monthlyFee: 325, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "pressure-washing", label: "Pressure Washing", icon: "\uD83D\uDCA6", description: "Power washing, deck cleaning, exterior cleaning", searchTerms: ["pressure washing", "power washing", "deck cleaning", "driveway cleaning", "exterior cleaning", "house washing"], avgProjectValue: "$150-$800", monthlyFee: 375, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "drywall", label: "Drywall & Plastering", icon: "\uD83E\uDDF1", description: "Drywall repair, installation, texturing", searchTerms: ["drywall", "drywall repair", "plastering", "drywall installation", "texturing", "sheetrock"], avgProjectValue: "$200-$5,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "insulation", label: "Insulation Services", icon: "\uD83C\uDFE0", description: "Attic insulation, spray foam, energy efficiency", searchTerms: ["insulation", "attic insulation", "spray foam", "blown-in insulation", "energy efficiency", "insulation contractor"], avgProjectValue: "$500-$5,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "solar", label: "Solar & Energy", icon: "\u2600\uFE0F", description: "Solar panel installation, energy audits, battery storage", searchTerms: ["solar panels", "solar installation", "energy audit", "battery storage", "solar energy", "solar contractor"], avgProjectValue: "$5,000-$30,000", monthlyFee: 1500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "gutters", label: "Gutter Services", icon: "\uD83C\uDFDA\uFE0F", description: "Gutter installation, cleaning, gutter guards", searchTerms: ["gutter", "gutter cleaning", "gutter installation", "gutter guards", "gutter repair", "seamless gutters"], avgProjectValue: "$150-$3,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "handyman", label: "Handyman Services", icon: "\uD83D\uDD28", description: "General repairs, odd jobs, home maintenance", searchTerms: ["handyman", "home repair", "odd jobs", "maintenance", "fix-it", "handyman service"], avgProjectValue: "$75-$1,000", monthlyFee: 350, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "veterinary", label: "Veterinary Services", icon: "\uD83D\uDC3E", description: "Pet healthcare, emergency vet, wellness exams", searchTerms: ["veterinarian", "vet", "animal hospital", "pet doctor", "emergency vet", "pet wellness"], avgProjectValue: "$100-$3,000", monthlyFee: 800, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "chiropractic", label: "Chiropractic Care", icon: "\uD83E\uDDB4", description: "Spinal adjustments, pain relief, wellness care", searchTerms: ["chiropractor", "chiropractic", "spinal adjustment", "back pain", "neck pain", "chiropractic care"], avgProjectValue: "$50-$500", monthlyFee: 700, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "accounting", label: "Accounting & Tax", icon: "\uD83D\uDCCA", description: "Tax preparation, bookkeeping, financial planning", searchTerms: ["accountant", "tax preparation", "bookkeeping", "CPA", "financial planning", "tax services"], avgProjectValue: "$200-$5,000", monthlyFee: 900, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "photography", label: "Photography Services", icon: "\uD83D\uDCF7", description: "Portraits, events, real estate photography", searchTerms: ["photographer", "photography", "portraits", "event photography", "real estate photography", "headshots"], avgProjectValue: "$150-$3,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "pet-grooming", label: "Pet Grooming", icon: "\uD83D\uDC15", description: "Dog grooming, cat grooming, pet spa", searchTerms: ["pet grooming", "dog grooming", "cat grooming", "pet spa", "dog groomer", "pet haircut"], avgProjectValue: "$40-$200", monthlyFee: 300, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "snow-removal", label: "Snow Removal", icon: "\u2744\uFE0F", description: "Snow plowing, de-icing, commercial snow removal", searchTerms: ["snow removal", "snow plowing", "de-icing", "ice removal", "snow clearing", "commercial snow removal"], avgProjectValue: "$100-$2,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "restoration", label: "Water Damage Restoration", icon: "\uD83C\uDF0A", description: "Flood cleanup, mold remediation, fire restoration", searchTerms: ["water damage", "restoration", "flood cleanup", "mold remediation", "fire restoration", "disaster recovery"], avgProjectValue: "$1,000-$20,000", monthlyFee: 1200, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "glass", label: "Glass & Glazing", icon: "\uD83E\uDE9F", description: "Window repair, glass replacement, shower enclosures", searchTerms: ["glass repair", "glass replacement", "glazier", "shower enclosure", "window glass", "glass company"], avgProjectValue: "$150-$3,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "irrigation", label: "Irrigation & Sprinklers", icon: "\uD83D\uDCA7", description: "Sprinkler installation, irrigation repair, winterization", searchTerms: ["irrigation", "sprinkler", "sprinkler installation", "irrigation repair", "lawn sprinkler", "winterization"], avgProjectValue: "$200-$5,000", monthlyFee: 450, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "demolition", label: "Demolition & Excavation", icon: "\uD83D\uDE9C", description: "Building demolition, site clearing, excavation", searchTerms: ["demolition", "excavation", "site clearing", "building demolition", "excavator", "demolition contractor"], avgProjectValue: "$2,000-$25,000", monthlyFee: 900, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
];

export function getNicheBySlug(slug: string): LocalNiche | undefined {
  return niches.find(n => n.slug === slug);
}
