export interface LocalNiche {
  slug: string;
  label: string;
  icon: string; // emoji
  description: string;
  searchTerms: string[];
  avgProjectValue: string;
  monthlyFee: number;
  exclusiveAvailable: boolean;
  subscriberSlug: string | null; // null = no exclusive subscriber yet
  subscriberName: string | null;
}

export const niches: LocalNiche[] = [
  { slug: "plumbing", label: "Plumbing", icon: "\uD83D\uDD27", description: "Emergency repairs, installations, drain cleaning, and water heater services", searchTerms: ["plumber", "plumbing", "drain", "water heater", "pipe repair"], avgProjectValue: "$150-$5,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "hvac", label: "HVAC", icon: "\u2744\uFE0F", description: "Heating, cooling, ventilation, and air quality services", searchTerms: ["hvac", "heating", "cooling", "air conditioning", "furnace"], avgProjectValue: "$200-$10,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "electrical", label: "Electrical", icon: "\u26A1", description: "Wiring, panel upgrades, lighting, and electrical repairs", searchTerms: ["electrician", "electrical", "wiring", "panel upgrade"], avgProjectValue: "$150-$8,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "roofing", label: "Roofing", icon: "\uD83C\uDFE0", description: "Roof repair, replacement, gutters, and storm damage restoration", searchTerms: ["roofer", "roofing", "roof repair", "gutters"], avgProjectValue: "$500-$15,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "landscaping", label: "Landscaping", icon: "\uD83C\uDF3F", description: "Lawn care, landscape design, hardscaping, and seasonal maintenance", searchTerms: ["landscaper", "landscaping", "lawn care", "hardscape"], avgProjectValue: "$100-$5,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "dental", label: "Dental", icon: "\uD83E\uDDB7", description: "General dentistry, cosmetic procedures, orthodontics, and oral surgery", searchTerms: ["dentist", "dental", "orthodontist", "oral surgeon"], avgProjectValue: "$200-$5,000", monthlyFee: 800, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "legal", label: "Legal", icon: "\u2696\uFE0F", description: "Personal injury, family law, criminal defense, estate planning, and immigration", searchTerms: ["lawyer", "attorney", "law firm", "legal"], avgProjectValue: "$500-$25,000", monthlyFee: 1000, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "cleaning", label: "Cleaning", icon: "\u2728", description: "House cleaning, commercial cleaning, and deep cleaning services", searchTerms: ["cleaning", "maid service", "house cleaning", "janitorial"], avgProjectValue: "$100-$500", monthlyFee: 300, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "auto-repair", label: "Auto Repair", icon: "\uD83D\uDE97", description: "Mechanical repair, body work, oil changes, and diagnostics", searchTerms: ["auto repair", "mechanic", "car repair", "body shop"], avgProjectValue: "$100-$5,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "pest-control", label: "Pest Control", icon: "\uD83D\uDC1B", description: "Insect control, rodent removal, termite treatment, and prevention", searchTerms: ["pest control", "exterminator", "termite", "rodent"], avgProjectValue: "$100-$2,000", monthlyFee: 350, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "painting", label: "Painting", icon: "\uD83C\uDFA8", description: "Interior and exterior painting, staining, and wallpaper", searchTerms: ["painter", "painting", "house painting", "commercial painting"], avgProjectValue: "$500-$10,000", monthlyFee: 350, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "real-estate", label: "Real Estate", icon: "\uD83C\uDFE1", description: "Buyer and seller representation, property management, and appraisals", searchTerms: ["realtor", "real estate", "property", "homes for sale"], avgProjectValue: "$3,000-$15,000", monthlyFee: 600, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  // ── New high-demand niches ────────────────────────────────────────
  { slug: "garage-door", label: "Garage Door", icon: "\uD83D\uDEAA", description: "Garage door repair, replacement, opener installation, and spring repair", searchTerms: ["garage door", "garage door repair", "garage door opener", "spring repair", "garage door installation"], avgProjectValue: "$150-$2,000", monthlyFee: 450, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "fencing", label: "Fencing", icon: "\uD83C\uDFD7\uFE0F", description: "Wood, vinyl, chain link, and iron fence installation and repair", searchTerms: ["fence", "fencing", "fence installation", "fence repair", "vinyl fence", "chain link fence"], avgProjectValue: "$1,500-$8,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "flooring", label: "Flooring", icon: "\uD83E\uDEB5", description: "Hardwood, tile, carpet, vinyl, and laminate flooring installation", searchTerms: ["flooring", "hardwood floors", "tile installation", "carpet", "laminate", "vinyl plank"], avgProjectValue: "$2,000-$12,000", monthlyFee: 600, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "windows-doors", label: "Windows & Doors", icon: "\uD83E\uDE9F", description: "Window replacement, door installation, storm windows, and energy upgrades", searchTerms: ["window replacement", "door installation", "storm windows", "energy efficient windows", "entry door"], avgProjectValue: "$3,000-$15,000", monthlyFee: 600, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "moving", label: "Moving", icon: "\uD83D\uDCE6", description: "Local and long-distance moving, packing, and storage services", searchTerms: ["moving company", "movers", "local moving", "long distance moving", "packing services", "storage"], avgProjectValue: "$500-$5,000", monthlyFee: 350, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "tree-service", label: "Tree Service", icon: "\uD83C\uDF33", description: "Tree removal, trimming, stump grinding, and emergency storm damage", searchTerms: ["tree service", "tree removal", "tree trimming", "stump grinding", "arborist", "storm damage"], avgProjectValue: "$300-$5,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "appliance-repair", label: "Appliance Repair", icon: "\uD83D\uDD0C", description: "Refrigerator, washer, dryer, dishwasher, and oven repair", searchTerms: ["appliance repair", "refrigerator repair", "washer repair", "dryer repair", "dishwasher repair", "oven repair"], avgProjectValue: "$100-$800", monthlyFee: 350, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "foundation", label: "Foundation & Waterproofing", icon: "\uD83E\uDDF1", description: "Foundation repair, basement waterproofing, crack sealing, and drainage", searchTerms: ["foundation repair", "basement waterproofing", "crack sealing", "drainage", "sump pump", "crawl space"], avgProjectValue: "$2,000-$15,000", monthlyFee: 800, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "home-security", label: "Home Security", icon: "\uD83D\uDD10", description: "Security system installation, cameras, smart locks, and monitoring", searchTerms: ["home security", "security cameras", "alarm system", "smart locks", "security monitoring", "surveillance"], avgProjectValue: "$500-$5,000", monthlyFee: 600, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "concrete", label: "Concrete & Masonry", icon: "\uD83C\uDFD7\uFE0F", description: "Driveways, patios, sidewalks, retaining walls, and brick repair", searchTerms: ["concrete", "masonry", "driveway", "patio", "sidewalk", "retaining wall", "brick repair"], avgProjectValue: "$1,500-$12,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "septic", label: "Septic & Sewer", icon: "\uD83D\uDD27", description: "Septic pumping, sewer line repair, drain field maintenance", searchTerms: ["septic", "sewer", "septic pumping", "sewer line", "drain field", "septic tank", "sewer repair"], avgProjectValue: "$300-$10,000", monthlyFee: 500, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
  { slug: "chimney", label: "Chimney & Fireplace", icon: "\uD83D\uDD25", description: "Chimney cleaning, inspection, repair, liner installation, and fireplace service", searchTerms: ["chimney", "fireplace", "chimney cleaning", "chimney repair", "chimney liner", "chimney inspection"], avgProjectValue: "$150-$5,000", monthlyFee: 400, exclusiveAvailable: true, subscriberSlug: null, subscriberName: null },
];

export function getNicheBySlug(slug: string): LocalNiche | undefined {
  return niches.find(n => n.slug === slug);
}
